### ISSUE TITLE
[CS] mirv_input improvement

### ISSUE THREAD

**Issue by eirisocherry** [ripieces/advancedfx#1000]
# Issue

**Teleporting to a chosen campath point takes a huge amount of time:**
1. `mirv_campath print`
2. Find and copy position of the point
3. `mirv_input position <xyz>`
4. Copy fov
5. `mirv_input fov <fov>`
6. Copy angles
7. `mirv_input angles <angles>`
8. Copy tick
9. `demo_goto <tick>`

**CS2 console changes make it even worse:**
- Click+Hold Click starts moving your console (when I try to quickly select text by double-clicking it, the console starts moving)
- They replaced word wrapping with a horizontal scroll (i don't like it)
- If you close and then open a console it won't reset the input (sounds cool, but in reality it's annoying, I used to empty the input by toggling the console and then getting a previous command with upper_arrow, but now I have to additionally press ctrl + a, backspace)
- You can resize a console only by holding bottom right corner (another bad idea, in csgo you could do it from every possible 360 degree angle)
-  `clear` command ignores the order, when adding `clear` command to a config before echo commands, it just doesn't care and clears either all of them or half of them, it's unpredictable and unusable now
(now you have to manually clear console, and if you don't accidental Click+Hold Click will throw you into the abyss)

**Yes, there is a workaround for teleporting to a chosen campath point.**
**If you have a campath you can just type `demo_goto <tick>` and it will teleport you to the campoint, but:**
1. You must exit free camera (i usually dont want to)
2. You need to copy a campoint tick (means you need to do mouse interactions with this ugly console, `mirv_campath print` -> Copy tick -> `demo_goto <tick>`)
3. In CS2 after typing `demo_goto <tick>` you also need to playback a demo a bit, otherwise the tick won't be updated (this bug/another_bad_idea makes it almost impossible to set the camera into exact campoint position, since when you playback the demo the camera moves) 
4. If you don't have a campath (ex: you have cubic interpolation and only 3 points), you won't be able to use this workaround.
5. Not flexible. What if i want to take only position from selected point? I can't do it the fast way. 

# Solution

This command will save a lot of time and nerves:
`mirv_input point position|angles|fov|tick` - Set position|fov|angles|tick of the selected campath point

**For example, I've created this campath:**
```
passed? selected? id : tick[offset](approximate!) , demoTime[offset](approximate!) , gameTime[offset] -> ( x y z ) fov ( pitch yaw roll )
Y n 0 : 2135 , 00m33s , 40.631699 -> ( -658.218384  -1466.074219  -30.255140 ) 77.039978 ( 24.591436  -63.525227  0.000000 )
Y n 1 : 2169 , 00m34s , 41.156700 -> ( -735.571655  -1576.032104  -28.181789 ) 81.540024 ( 16.131447  31.586748  0.000000 )
Y n 2 : 2205 , 00m34s , 41.715023 -> ( -727.998840  -1666.749512  -73.133873 ) 87.540085 ( 4.179459  53.690739  0.000000 )
Y Y 3 : 2238 , 00m35s , 42.231720 -> ( -605.875122  -1751.225098  -140.876389 ) 94.440155 ( -11.345703  122.630615  0.000000 )
----
Current tick: 2237, Current demoTime: 00m35s, Current gameTime: 42.233025
Current ( x y z ) fov ( pitch yaw roll ): ( -574.399353  -1857.846191  -107.142151 ) 94.440155 ( 8998.819336  3355.545410  0.000000 )
```

**Case1:**
If I select campath point №0 `mirv_campath select #0 #0`
and then type in `mirv_input point position`
it will activate `mirv_input position -658.218384  -1466.074219  -30.255140` automatically

**Case2:**
If I select campath point №1 `mirv_campath select #1 #1`
and then type in `mirv_input point fov`
it will activate `mirv_input fov 81.540024` automatically

**Case3:**
If I select campath point №2 `mirv_campath select #2 #2`
and then type in `mirv_input point angles`
it will activate `mirv_input angles 4.179459  53.690739  0.000000` automatically

**Case4:**
If I select campath point №3 `mirv_campath select #3 #3`
and then type in `mirv_input point tick`
it will activate `demo_goto 2238` automatically

**Case5:**
I've created a shortcut
alias "pAll" "mirv_input point position; mirv_input point fov; mirv_input point angles; mirv_input point tick"

If I select campath point №3 `mirv_campath select #3 #3`
and then type in `pAll`
it will activate `mirv_input position -605.875122  -1751.225098  -140.876389; mirv_input fov 94.440155; mirv_input angles -11.345703  122.630615  0.000000; demo_goto 2238` automatically

**Case6:**
If selection=none/all or more than 1 point selected echo an error

**Since this is the 1000th anniversary issue 🎉, I think this has to be implemented :D**

**Comment by ChetdeJong** [comment]
Hi, 

It's possible to do this sort of functionality in CS2 using mirv-script, you can register custom command with whatever logic you like. 

I can do script for you, when I have time. Maybe in coming days, but don't count on that.
If you want to do it yourself, then you can find available API here:
https://github.com/advancedfx/advancedfx/tree/main/misc/mirv-script/src/types

Example:
https://github.com/advancedfx/advancedfx/blob/main/misc/mirv-script/src/snippets/mirv_script_fov.ts
then just transpile typescript to javascript and you can load script in game, using `mirv_script_load`

mirv-script is still under development and there are caveats due lack of plugin system (e.g. commands can interfere with each other, etc.), but it's usable.

However if you need it in CSGO, then there is no mirv-script, unfortunately.

**Comment by eirisocherry** [comment]
imho, mirv_script should be used only for low-priority/specific tasks or experimenting with stuff before implementing it
The command I suggested `mirv_input point position|angles|fov|tick` is from high priority category and should be built-in

### Let me explain (it might be subjective, but it is what it is)

At some point you start thinking about making some cinematics, the reasons could be various:
- you got bored from merging game clips (povs)
- you got inspired by edits/movies
...

You start googling on "how to make cinematics in csgo" and that's how you find out about HLAE.

HLAE - a tool originally designed to automate the creation of campath, since making them using the game's built-in features is tedious.

### HLAE features

I. Free camera & Campath  
1. [Campath basics] free camera basics -> add/remove a campath -> playback a campath 
2. [Campath editing] campoint selection -> shift campoint tick -> shift campoint pos/ang/fov -> linear/cubic interp -> save/load campath
3. [Campath advanced] mirv_calcs -> mirv_aim -> camio

II. Streams
1. [Screen recording] custom tga output folder -> ffmpeg -> customizable killfeed
2. [Streams] reshade -> mirv_streams (depth, greenscreens) -> .cam import/export scripts 

III. Advanced stuff
1. [mirv_script] 
2. [AGR] agr

### Implementation priorities based on typical learning curve (highest to lowest)

I_1: allows you to create simple medium/long shot cinematics without any efforts
I_2: allows you to create complex close-ups/long cinematics which require a lot of points
II_1: significantly sped ups the process of recording
I_3: allows you to make more unique cinematics
II_2: allows you to make interesting effects
III_1: it seems useful for
- Experimenting with stuff before making it built-in
- Writing complex scripts such as:
- - Camera live-link for 3d software
- - Batch demo recording
- - UI?
- Writing specific small scripts that are not worth implementation

III_2: 3d


And since the suggested command `mirv_input point position|angles|fov|tick` automates the following process ->(shift campoint tick -> shift campoint pos/ang/fov from the highest priority category I_2)
it's better to be implemented as a built-in command (that is available for all source games), not as an exclusive plugin for cs2 only (mirv_script)

**Comment by ChetdeJong** [comment]
Well, I see your point and thanks for putting effort into elaborating, but I personally do not agree on that.

Considering https://github.com/advancedfx/advancedfx/issues/896 and the fact that CS2 now is mostly relevant, mirv-script makes perfect sense in that matter.

> is from high priority category and should be built-in

I think it's up to maintainer (dtugend) to decide or you can make pull request (because of https://github.com/advancedfx/advancedfx/issues/896), if you wish to.

**Comment by eirisocherry** [comment]
I don't mind to have this feature in CS2 only, but this game is still not ready for editing: laggy 3rd person animations + #999

**Comment by ChetdeJong** [comment]
Hi @eirisocherry , 

I did the snippet for mirv-script. It should work similarly to what you described.
[Release.zip](https://github.com/user-attachments/files/17609802/Release.zip)

Replace dll in x64 folder and put snippet into `path-to-HLAE\resources\AfxHookSource2\snippets`. If https://github.com/advancedfx/advancedfx/pull/1005 gets merged, then this snippet will be there with every HLAE release. 

In game do `mirv_script_load "path-to-HLAE\resources\AfxHookSource2\snippets\mirv-script-point.js"` and then you should have `mirv_script_point` command. Enter it without arguments to see description/help.

Some useful binds:
```
bind q "mirv_script_point all prev 1"
bind e "mirv_script_point all next 1"
bind c "mirv_campath edit position current; mirv_campath edit angles current; mirv_campath edit fov current"
```

**Comment by eirisocherry** [comment]
TYSM, works like charms!  

Is it normal that it says undefined? Even so all the scripts work tho  
![image](https://github.com/user-attachments/assets/84539d49-44cd-4359-ac6d-60094adb1c44)

**Comment by ChetdeJong** [comment]
yeah its normal, don't mind it
