### ISSUE TITLE
Error - AfxHooksource2, Problem in: c:\source\advancedfx\AfxHookSource2\ViewModel.cpp:75

### ISSUE THREAD

**Issue by Zackwithaq** [ripieces/advancedfx#1003]
CS2 Crashes on the loading screen when I try opening it through HLAE

I have the most recent version of CS2
I have the most recent version of HLAE, and have re-installed it 
I verified the integrity of game files on steam and have re-installed CS2 on steam

idk wtf i am doing wrong, any help is appreciated

**Comment by SandmX** [comment]
Unfortunately, the same problem was happened to me

**Comment by ChetdeJong** [comment]
update will be out in few hours, but you can use this build for now (replace file in x64 folder)

[AfxHookSource2.zip](https://github.com/user-attachments/files/17566380/AfxHookSource2.zip)

**Comment by dtugend** [comment]
https://github.com/advancedfx/advancedfx/releases/tag/v2.175.0
