### ISSUE TITLE
Launching CS2 using HLAE resulted in a crash

### ISSUE THREAD

**Issue by SandmeyerX** [ripieces/advancedfx#1012]
(Please search existing **open and closed** issues first to verify this is a new bug report.)
Hlae 2.177.0.0
![image](https://github.com/user-attachments/assets/00885b80-82c0-41f9-9319-64634debb215)

The game crashes and exits after launching

**Comment by Dechno1337** [comment]
Do you have any anti-cheat software running in the background?

**Comment by dtugend** [comment]
https://support.faceit.com/hc/en-us/articles/9394666828188-What-is-FACEIT-Anti-cheat-and-how-does-it-work
> In our latest versions of the FACEIT Anti-cheat, you are given more control over the driver operation. **In particular, you can go to the Anti-cheat tray icon and choose “disable driver”.** This will allow you to unload our driver without uninstalling the Anti-cheat. Please keep in mind that if you do disable the driver, you will be asked to restart your PC before being able to play any of the games we protect.

**Comment by SandmeyerX** [comment]
Thank you for answer, it works. Maybe because I didn't restart my pc after I closed anti-cheat

**Comment by dtugend** [comment]
It depends on the anti cheat you are using, what you need to do to disable it.
E.g. FaceIT can be disabled at runtime, but after reboot it's back.
