### ISSUE TITLE
[TF2] HLAE Running With Lawena Returns Error Code 13 

### ISSUE THREAD

**Issue by Wannacri** [ripieces/advancedfx#1014]
Hey, so firstly when I use HLAE on its own, the newest version I can load AfxHookSource.dll perfectly fine into TF2 using "/developer/custom-loader" and use hlae perfectly fine. But when using another recording tool, like lawena in my issue, it returns a Code 13 "Dll cannot be loaded". Ive tried everything I can, asking questions, downloading the latest version of both, tweaking the paths folder, disabling anti-virus, using x64 ""fixes"". But nothing, can anyone help?

Also just another addition, I cant seem to find anywhere inside of HLAE to save my custom loader settings and have to re-enter everytrime I run, which is stupidly annoying.
![image3](https://github.com/user-attachments/assets/c2829e99-ad38-4f22-80ff-94b2b41636ee)
![image2](https://github.com/user-attachments/assets/84faff34-9ab3-4df4-b77b-74a640ee807f)
![image](https://github.com/user-attachments/assets/cde291fc-f21e-4b32-a71f-5c35e92f1c92)

**Comment by dtugend** [comment]
How to fix Lawena & HLAE being broken by the TF2 64 bit update
https://www.youtube.com/watch?v=YBGwEzPEe54

**Comment by dtugend** [comment]
You might have copied and renamed the wrong tf_64.exe (wrong, this is the 64 bit one) to hl2.exe, you need to copy and rename the tf.exe (correct, this is the 32 bit one) instead.

This tutorial usually works if followed correctly:
How to fix Lawena & HLAE being broken by the TF2 64 bit update
https://www.youtube.com/watch?v=YBGwEzPEe54

Maybe right click properties of TF2 in Steam Library -> Local Files Tab -> Let it verify and download any files required before you try again.

**Comment by dtugend** [comment]
Regarding the custom loader settings, if HLAE is correctly installed with all files from the installer as recommended in the tutorial it should save your custom loader settings just fine when closed. However maybe lawena overrides them or you used the zip version and extracted it incorrectly (?)

**Comment by dtugend** [comment]
Also please make sure to update your HLAE to the latest version and that you are not using a mix of ZIP and Installer version, please.

**Comment by Dechno1337** [comment]
Is it solved, @Wannacri?

**Comment by Wannacri** [comment]
Yes, I solved the issue, thank you to you guys @Dechno1337 @dtugend
