### ISSUE TITLE
AGR CSS/TF2

### ISSUE THREAD

**Issue by Devostated** [ripieces/advancedfx#714]
If you type mirv_agr you get these two CSGO specific commands:
mirv_agr recordPlayerCameras [...]
mirv_agr recordViewmodels [...]

and mirv_agr recordViewmodel [...] is missing, but works

CSS:
in a test recording the viewmodel Deagle was rotated wrong:
![image](https://user-images.githubusercontent.com/30211694/134731033-196d5376-6624-404e-979e-ffd537107f62.png)

word model Deagle has a broken magazine:
![image](https://user-images.githubusercontent.com/30211694/134731098-4fa3e8dd-3c3c-4cfb-ba2a-f1121d352bb2.png)

TF2: 
Missing viewmodels weapons:
![image](https://user-images.githubusercontent.com/30211694/134731723-07c4f416-4422-4185-a718-7b462c40a9b1.png)

Maybe some broken viewmodels (could be a weapon where you can't see the hands)
![image](https://user-images.githubusercontent.com/30211694/134732042-c01ffec5-c15a-412b-a476-3b4eb1d64afe.png)

**Comment by dtugend** [comment]
Consider providing the demo files, time / pov info for reference.

1) About which CSS version are we walking?

2) What's your cl_righthand value? It should be set to 1 to avoid similar problems.
Also some models might be always left-handed / mirrored and AGR can not represent that accurately (e.g. the CSS knife maybe).

> and mirv_agr recordViewmodel [...] is missing, but works

That's missing on puropose, it's replaced by recordViewmodels -1 and just there so old configs continue working.

> in a test recording the viewmodel Deagle was rotated wrong:

What HLAE version was used and what afx-blender-scripts version?

>word model Deagle has a broken magazine:

Does it even have one in the demo at all? Maybe it's just recorded too much?

> Missing viewmodels weapons:
> Maybe some broken viewmodels (could be a weapon where you can't see the hands)

Might be related to 1) as well.

**Comment by Devostated** [comment]
> About which CSS version are we walking?

CSS v34, the only AGR supported version

> What's your cl_righthand value?

Should be set to 0, only the deagle was wrong. The other two weapons used in this recording was fine.

> That's missing on puropose, it's replaced by recordViewmodels -1 and just there so old configs continue working.

recordViewmodels and recordPlayerCameras is CSGO specific. They never worked for TF2, CSS or GoldSrcs. They still use recordViewmodel without s and only if you are viewing in PoV.

> What HLAE version was used and what afx-blender-scripts version?

Both are on the latest version.

> Does it even have one in the demo at all? Maybe it's just recorded too much?

A Deagle should always have a magazine. The magazine glitch happened after the character swapped from Deagle to knife to Deagle.

**Comment by Devostated** [comment]
Testings were made with 3 different settings in PoV and Freecam:

Config1:
> mirv_agr recordPlayerCameras -1
mirv_agr recordViewmodels -1
mirv_agr recordViewmodel 0

Config2:
> mirv_agr recordPlayerCameras 1
mirv_agr recordViewmodels 1
mirv_agr recordViewmodel 0

Config3:
> mirv_agr recordPlayerCameras 1
mirv_agr recordViewmodels 0
mirv_agr recordViewmodel 1

Only Config3 recorded viewmodels while being in PoV.
recordPlayerCameras 1/-1 didn't record any cameras, just as expected, cause it was made and tested only for CSGO back then.

**Comment by dtugend** [comment]
recordViewmodel front-entds recordViewmodels, so setting it to 0 will set that to 0 as well.
recordViewmodels -1 should be used instead.

**Comment by Devostated** [comment]
That is false. recordViewmodels and recordPlayerCameras just don't do anything, else I would have gotten a camera from recordPlayerCameras in any of my 6 recordings.

**Comment by dtugend** [comment]
I only talked about recordViewmodel(s), and explained the problem with config 1 and 2, please read again.

**Comment by Devostated** [comment]
Tested in TF2 free camera

> mirv_agr recordViewmodels -1
mirv_agr recordViewmodel 1

every single viewmodel is at 0 location
![image](https://user-images.githubusercontent.com/30211694/134773776-f5836b4c-f0af-4205-bac2-39370c2814fa.png)

Why would recordViewmodel 1 even be required. It is not listed as a command if you enter mirv_agr in console.

**Comment by Devostated** [comment]
Tested in CSS v34 free camera:
> mirv_agr recordViewmodels -1
mirv_agr recordViewmodel 1

Not a single viewmodel
![image](https://user-images.githubusercontent.com/30211694/134776228-f84831c9-b49a-44b3-b082-2fb00323f26a.png)

Tested in CSS v34 pov:
> mirv_agr recordViewmodels -1
mirv_agr recordViewmodel 1

only pov got recorded, as expected.
![image](https://user-images.githubusercontent.com/30211694/134776267-1ae08702-d756-4313-aff2-db6eb024e621.png)

**Comment by dtugend** [comment]
- Is TF2 POV or 3rd person?
- You only need `mirv_agr recordViewmodels -1`
- CSS v34 doesn't support recording 3rd person viewmodels like CS:GO.

**Comment by Devostated** [comment]
> Is TF2 POV or 3rd person?

Free camera

> You only need mirv_agr recordViewmodels -1 

you just told me to use recordViewmodel 1, this whole issue is NOT about CSGO. It's about CSS and TF2.

**Comment by dtugend** [comment]
> Free camera

Please try 1st person POV to get viewmodels in TF2, 3rd person viewmodels is a CS:GO only feature.

> you just told me to use recordViewmodel 1

I suggested to use recordViewmodels -1 _instead_, I only wanted to explain that recordViewmodel front-ends the recordViewmodels command and is only there for legacy reasons and thus not listed.

**Comment by Devostated** [comment]
> Please try 1st person POV to get viewmodels in TF2, 3rd person viewmodels is a CS:GO only feature.
pov record:
> mirv_agr recordViewmodels -1
mirv_agr recordViewmodel 1

missing weapon and rest viewmodels are at 0 location.
![image](https://user-images.githubusercontent.com/30211694/134777296-6e7fa708-a9bf-4f71-a9fd-440e2729b914.png)

![image](https://user-images.githubusercontent.com/30211694/134777286-ca86aa49-0b01-4940-96f6-22ff771a6f8e.png)

if 3rd person viewmodels is a CS:GO only feature, then why don't we just do only the classic recordViewmodel 0/1 ? This makes no sense otherwise.

**Comment by Devostated** [comment]
What I would like to be changed for AGR:

CSS/TF2/GoldSrcs:

Remove:
>mirv_agr recordPlayerCameras [...]
mirv_agr recordViewmodels [...]

Add: 
>mirv_agr recordViewmodel 0/1

So it's like legacy version:
>mirv_agr enabled 0/1
mirv_agr recordCamera 0/1
mirv_agr recordPlayers 0/1
mirv_agr recordWeapons 0/1
mirv_agr recordProjectiles 0/1
mirv_agr recordViewmodel 0/1
mirv_agr recordInvisible 0/1
mirv_agr debug [...]
mirv_agr start
mirv_agr stop


CSS:
> certain weapons have wrong animations first person and third person (e.g. Deagle)
tested with CSS v34 decompiled models and CSS steam decompiled models.

TF2:
> missing viewmodel weapons

GoldSrcs:
> entering mirv_agr in console only shows mirv_agr start and mirv_agr stop, are there other options?

**Comment by dtugend** [comment]
Can we open an separate issue for the unsresolved CSS issues and close this one?

Edit: As discussed in discord it's because some models are mirrored and the data we get from the engine from demo tools can't represent that with vec + quat. So there's no easy solition with current system.
