### ISSUE TITLE
afxhook source problem in C:\source\advanced\AfxHookSource\addresses.cpp:592

### ISSUE THREAD

**Issue by lxgxnd4ry** [ripieces/advancedfx#715]
https://prnt.sc/1tkdmq2

**Comment by Devostated** [comment]
Make sure HLAE and CS are up to date and that you have the correct path to CSGO. Happens a lot that people have two CSGOs installed without knowing.

**Comment by dtugend** [comment]
This is probably solvable by Devostated's reply above, so I am closing the issue for now. If you still need further help, just reply here with more information.
