### ISSUE TITLE
AGR - mirrored viewmodels / distorted models / ...

### ISSUE THREAD

**Issue by Devostated** [ripieces/advancedfx#716]
A few weapons in CSS are mirrored, which causes viewmodels glitching out.

Following weapons are righthanded instead of righthanded:
v_rif_galil
v_rif_famas
v_mach_m249
v_knife_t

Example:
![WzPwjzq1i8](https://user-images.githubusercontent.com/30211694/135904886-aad12850-8a80-483e-b694-643c0a36da2f.gif)

**Comment by dtugend** [comment]
This probably needs an updated AGR version that can handle bone matrices and an updated HLAE that gets the bone matrices directly from the models.

**Comment by dtugend** [comment]
This is fixed in https://github.com/advancedfx/advancedfx/commit/7a8f566b06849c1efd9428f858f21b2a92a74667

**Comment by dtugend** [comment]
https://github.com/advancedfx/advancedfx/releases
