### ISSUE TITLE
AGR - Unused viewmodels

### ISSUE THREAD

**Issue by Devostated** [ripieces/advancedfx#717]
Fixing the recording of unused viewmodels of other players.
Can be fixed in HLAE or in Blender. I'd suggest doing it in Blender and skip the import, if the armature doesn't have any rotation and location while reading the AGR.

![image](https://user-images.githubusercontent.com/30211694/135907054-9765e4ba-f619-41ff-b66e-2f009ac1cd10.png)

**Comment by dtugend** [comment]
@Devostated  Seems like we fixed it in CS:GO accidentally, do you know which other games we need to fix it still?

**Comment by dtugend** [comment]
In the light of CS:GO moving to CS2 that supports SFM, allowing for better export / tools / scripts than AGR can deliver, we currently don't plan to continue to work on AGR.
