### ISSUE TITLE
AGR - recordViewmodel/s and viewmodel spawns

### ISSUE THREAD

**Issue by Devostated** [ripieces/advancedfx#719]
The game spawns a new viewmodel, when ever a character switches to another weapon. The recordWeapons option places all the weapons in the players hand to have one constant animation. 
I can imagine that less people would overwhelmed by the amount of "random" weapons everywhere, if this could be applied to viewmodels aswell.

**Comment by dtugend** [comment]
does this apply to CS:GO, can you provide more details please?
if they are mergeable it should do that, at least for recordInvisible 0?
(recordInvisible 1 is not recommended)

**Comment by Devostated** [comment]
That the world weapons stay in the characters hands happens in TF2 and CSGO, probably in CSS aswell. IIRC this was actually a bug, but we decided to keep it that way, cause it was quite handy. Spawning new viewmodels happens in every AGR, doesn't matter which recordInvisible setting you use.

**Comment by dtugend** [comment]
In the light of CS:GO moving to CS2 that supports SFM, allowing for better export / tools / scripts than AGR can deliver, we currently don't plan to continue to work on AGR.
