### ISSUE TITLE
"-afxDetourPanorama" launch option causes error when launching CS:GO

### ISSUE THREAD

**Issue by suemos** [ripieces/advancedfx#723]
```
ENGINE ERROR | 
Unable to load layout file 'file://[resources]/layout/hud/hudmissionpanel.xml'/ 
This may indicate a problem witth your local install files and validating 
your install through the Steam client may resolve the issue.
```

What I did: When launching CS:GO through HLAE with [the launch option '-afxDetourPanorama',](https://i.imgur.com/epx2muv.png) the error message above is [spit out by CS:GO](https://i.imgur.com/qClL7Ha.png) and subsequently closes.

Removing the launch option allows the game to start up with HLAE as usual, just without adjusted Panorama configs. The only thing I had adjusted in the Panorama configs was [the colors of the killfeed in 'huddeathnotice.css'.](https://i.imgur.com/8zjMbuf.png)

**Comment by dtugend** [comment]
This is not a HLAE bug, please read the notes section at the end of this article:
https://github.com/advancedfx/advancedfx/wiki/How-to-change-Panorama-UI

If you modify Panorma UI, it's your responsibility to update your modifciations properly or re-apply them from scratch properly upon updates, the notes should give a hint how to do that.

**Comment by dtugend** [comment]
Hint on how to re-apply.

Start once without -afxDetourPanorama. Delete all folders that are inside the panoram.org.zip created after that step from the panorama UI folder in csgo folder. After that verify game cache just in case. Then start from Step 1 again in the guide linked above. That should fix it.

**Comment by dtugend** [comment]
Sorry if my first reply is harsh or offensive, it was not your fault, was just in a bad mood. Sorry.

**Comment by suemos** [comment]
all good! ty for the help 😄

**Comment by dtugend** [comment]
Is it solved or still problems?

**Comment by suemos** [comment]
working good! sorry for not following up with an actual status, thanks for the pointer
