### ISSUE TITLE
failed start with HLAE after panorama ui manual

### ISSUE THREAD

**Issue by say1j** [ripieces/advancedfx#724]
After step 9 of https://github.com/advancedfx/advancedfx/wiki/How-to-change-Panorama-UI tutorial, csgo failed to start.
![image](https://user-images.githubusercontent.com/31889581/136713483-338eb408-119a-471c-8b9b-099b325db396.png)
Want to change inspect UI and add green screen into there, but can't even start with this tutorial, is it working now?

**Comment by dtugend** [comment]
Please read the notes section at the end of this article:
https://github.com/advancedfx/advancedfx/wiki/How-to-change-Panorama-UI

If you modify Panorma UI, you need to update your modifciations properly or re-apply them from scratch properly upon updates.

Hint on how to re-apply:

Start once without -afxDetourPanorama and then once again with -afxDetourPanorama.
Delete all folders that are also inside the panoram.org.zip created after that from the Panorama UI folder in the csgo folder.
After that verify game cache just in case.
Then start from Step 1 again in the guide linked above.

**Comment by say1j** [comment]
ty, now csgo runned with -panorama -afxDetourPanorama
i can change files in panorama.org.zip or directly in game folder panorama to take effect and start game successfully?

**Comment by dtugend** [comment]
The easiest way as (hoepfull) written in the guide above is to place the chnaged files inside the CS:GO pnaorma folder in the right folders, that way you can easily change them.
