### ISSUE TITLE
cpp error

### ISSUE THREAD

**Issue by cutieion** [ripieces/advancedfx#726]
Error - AfxHookSource
Problem in c:\source\advancedfx\afxhooksource\addresses.cpp:1819

**Comment by dtugend** [comment]
1. Make sure you have and are using the latest HLAE version.
2. Verify your  game cache in Steam (right click CS:GO -> Properties -> Local Files tab -> Verify button, let it verify and download).
3. Some people end up with more than one CS:GO install after a while, you have to chose the right one in HLAE, you can find the right one in Steam (right click CS:GO -> Properties -> Local Files tab -> Browse local files button, click in explorer address bar to reveal full path and append `\csgo.exe`).
