### ISSUE TITLE
AGR high FPS snapshots

### ISSUE THREAD

**Issue by Devostated** [ripieces/advancedfx#727]
Taking snapshots during AGR. 
Example: running at 120 FPS and snapshotting at about 30 e.g
This would fix animation speed in CSS:

https://user-images.githubusercontent.com/30211694/138657757-bd785f88-69e0-43f1-80dc-9b39c7f186e6.mp4

It could fix low fps deformation in CSGO, but could glitch out viewmodel recording on higher fps  (not sure if it still glitches out, last test was before viewmodel recording update).

**Comment by dtugend** [comment]
In the light of CS:GO moving to CS2 that supports SFM, allowing for better export / tools / scripts than AGR can deliver, we currently don't plan to continue to work on AGR.
