### ISSUE TITLE
Ability to suppress demo commands

### ISSUE THREAD

**Issue by lupusbytes** [ripieces/advancedfx#730]
If a player in a POV demo changes volume through a bind, the volume will also change for the demo viewer.
Another example is demo_togglepause, which does nothing while recording, but will pause the demo for the viewer.

There is probably more examples where commands baked into the demo will mess with the playback.
A command/flag to suppress these commands would be a nice feature, but is not critical.

**Comment by dtugend** [comment]
Added in HLAE 2.124.0.

Changelog had wrong syntax at first, correct syntax is:
```
mirv_block_commands add 5 "volume\*"
```
