### ISSUE TITLE
AGR for GoldSrcs import blender gets convulsion? 

### ISSUE THREAD

**Issue by 591280714** [ripieces/advancedfx#734]
Frame 60
![image](https://user-images.githubusercontent.com/45847377/143032741-130fd689-6e33-45c7-9dcf-51f70f553313.png)
Frame 61
![image](https://user-images.githubusercontent.com/45847377/143032813-189380d8-2759-4244-b45e-d0a791fd8c34.png)
and evey few frames will happen once.
This is my import setup,
![image](https://user-images.githubusercontent.com/45847377/143033293-e5fef2db-6be2-431a-9f6e-3a10526c4b83.png)
I have been tested all the combinations, nothing changed. Three person view did not see this situation though..
HLAE Version: 2.124.0 HLAE commands used:
mirv_movie_filename "c:\HLAE"
mirv_movie_fps 30
mirv_movie_export_sound 1
mirv_recordmovie_start
mirv_recordmovie_stop
mirv_agr start "c:\HLAE\Untitled.agr"
mirv_agr stop

**Comment by dtugend** [comment]
Can you please provide a short AGR file and the demo in question and more information, please?

Edit: also are you sure it's not just the 3rd person model getting into view upon weapon switching?

Edit2: https://github.com/advancedfx/advancedfx/wiki/GoldSrc%3Amirv_agr
> Known problems: Some special effects on models (e.g. the distortion on the hologram or left-handed models) will not be accurate, because they can't be accurately represented in AGR version 5.

**Comment by 591280714** [comment]
> Can you please provide a short AGR file and the demo in question and more information, please?
> 
> Edit: also are you sure it's not just the 3rd person model getting into view upon weapon switching?
> 
> Edit2: https://github.com/advancedfx/advancedfx/wiki/GoldSrc%3Amirv_agr
> 
> > Known problems: Some special effects on models (e.g. the distortion on the hologram or left-handed models) will not be accurate, because they can't be accurately represented in AGR version 5.
[Demo and Map.zip](https://github.com/advancedfx/advancedfx/files/7593407/Demo.and.Map.zip)
Please.
And what does this mean?
![image](https://user-images.githubusercontent.com/45847377/143191950-83415aee-3041-4463-a23c-931ed605beb3.png)
It is saying I have to decompile HD and Normal models to a same folder? Frist normal, and second HD? Won't it be overwrite?

**Comment by dtugend** [comment]
> It is saying I have to decompile HD and Normal models to a same folder? Frist normal, and second HD? Won't it be overwrite?

Yes, but thats intended, since not all models have hires versions.

Edit: The download doesn't contain an AGR file, can you provide the AGR file, please?

**Comment by 591280714** [comment]
> > It is saying I have to decompile HD and Normal models to a same folder? Frist normal, and second HD? Won't it be overwrite?
> 
> Yes, but thats intended, since not all models have hires versions.

But isn't that sync with the model when you record AGR is fine? Like If I use HD models, and I have to choose HD models's folder when I import Blender, If I use normal models, Then choose normal models's folder when import Blender.
And I tested all folders, Still got this issue..
Basically, it can be confirmed is not the weapon switching, And choose the wrong models's folder.

**Comment by 591280714** [comment]
> > It is saying I have to decompile HD and Normal models to a same folder? Frist normal, and second HD? Won't it be overwrite?
> 
> Yes, but thats intended, since not all models have hires versions.
> 
> Edit: The download doesn't contain an AGR file, can you provide the AGR file, please?
[AGR.zip](https://github.com/advancedfx/advancedfx/files/7593797/AGR.zip)
I thought maybe you record AGR will be the best, But, Anyway,

**Comment by dtugend** [comment]
I can reproduce the problem.
I think I found the problem, not sure if there's an easy solution:

to quote from the changelog a part that's missing in the Wiki (will edit it in):
> Please note that the in-eye model of the CS 1.6 knife will be wrong, which is because the engine mirrors the model with cl_righthand 1 and the current AGR format can not express that (same problem you would have for other v_models with cl_righthand 0).
This probably also applies e.g. to the hologram in Half-Life hazard course training when it is distored.

Basically the problem is AGR expects you to record with cl_righthand 1, since it can not express the mirroring of the model animations in it's version 5 format.
But even if you did that it would still not work properly, because the awp v_model like the deagle one is mirrored (left-handed originally) with cl_righthand 1.

**Comment by 591280714** [comment]
> I can reproduce the problem. I think I found the problem, not sure if there's an easy solution:
> 
> to quote from the changelog a part that's missing in the Wiki (will edit it in):
> 
> > Please note that the in-eye model of the CS 1.6 knife will be wrong, which is because the engine mirrors the model with cl_righthand 1 and the current AGR format can not express that (same problem you would have for other v_models with cl_righthand 0).
> > This probably also applies e.g. to the hologram in Half-Life hazard course training when it is distored.
> 
> Basically the problem is AGR expects you to record with cl_righthand 1, since it can not express the mirroring of the model animations in it's version 5 format. But even if you did that it would still not work properly, because the awp v_model like the deagle one is mirrored (left-handed originally) with cl_righthand 1.

so, will be upgrade to version 6 format or something?
But now, How do I fix?

**Comment by dtugend** [comment]
1. Try with cl_righthand 0 as you did.
2. Untick the "Add interpolated keyframes" option on the importer dialogue in Blender.

If 2. solves the issue (it did for me), then please tell us, we might need to fix a problem in the AGR Blender importer script then.

**Comment by dtugend** [comment]
Wait it was something else that must have fixed it, above doesn't work.

**Comment by 591280714** [comment]
> Wait it was something else that must have fixed it, above doesn't work.

I am waiting

**Comment by dtugend** [comment]
I was just lucky, apparently this is related to a bug in GoldSrc AGR: Under some conditions it's reading wrong / uninitialized data (infinity / nan), which the importer silently corrects to default rotation.

**Comment by 591280714** [comment]
> I was just lucky, apparently this is related to a bug in GoldSrc AGR: Under some conditions it's reading wrong / uninitialized data (infinity / nan), which the importer silently corrects to default rotation.

So, we got 2 issues here, AGR format and AGR Blender importer script.

**Comment by dtugend** [comment]
Well the script is not exactly wrong, it just tries to do s.th. to solve it.
I will try to investigate why the data is wrongly derieved in AfxHookGoldSrc.

**Comment by dtugend** [comment]
Can you confirm if this DLL produces the data for cl_righthand 0 correctly (it does for me, just replace the one in HLAE folder with this one, then record again):
[AfxHookGoldSrc.zip](https://github.com/advancedfx/advancedfx/files/7594387/AfxHookGoldSrc.zip)

Edit:
> So, we got 2 issues here

Yes:
1. AGR format not being able to express more than vector + quaternion for bones, while e.g. mirroring or other distortion (matrix might be required).
2. The other one was wrong data derieved for the quaternion (that I tried to fix in the DLL above).

**Comment by 591280714** [comment]
> Can you confirm if this DLL produces the data for cl_righthand 0 correctly (it does for me, just replace the one in HLAE folder with this one, then record again): [AfxHookGoldSrc.zip](https://github.com/advancedfx/advancedfx/files/7594387/AfxHookGoldSrc.zip)

I try

**Comment by 591280714** [comment]
> Can you confirm if this DLL produces the data for cl_righthand 0 correctly (it does for me, just replace the one in HLAE folder with this one, then record again): [AfxHookGoldSrc.zip](https://github.com/advancedfx/advancedfx/files/7594387/AfxHookGoldSrc.zip)
> 
> Edit:
> 
> > So, we got 2 issues here
> 
> Yes:
> 
> 1. AGR format not being able to express more than vector + quaternion for bones, while e.g. mirroring or other distortion (matrix might be required).
> 2. The other one was wrong data derieved for the quaternion (that I tried to fix in the DLL above).

Looks like problem solved! Thank you!

**Comment by dtugend** [comment]
The mirroring problem and the distorted hologram problem can not be solved without swichting AGR to matrices instead of vectors + quaternion in version 6+, I will open a separate issue for that.

Thanks for reporting the problem(s).

Edit: Apprently the matrix problem is already tracked in #716

**Comment by 591280714** [comment]
> The mirroring problem and the distorted hologram problem can not be solved without swichting AGR to matrices instead of vectors + quaternion in version 6+, I will open a separate issue for that.
> 
> Thanks for reporting the problem(s).
> 
> Edit: Apprently the matrix problem is already tracked in #716

You mean ARG format version 6?

**Comment by dtugend** [comment]
> You mean ARG format version 6?

Yes, we'd need to increment the version when adding that feature to solve issues shown in #716

**Comment by 591280714** [comment]
> > You mean ARG format version 6?
> 
> Yes, we'd need to increment the version when adding that feature to solve issues shown in #716

Sounds amazing! I am looking forward to it! Till then will be HLAE 3.0?

**Comment by dtugend** [comment]
I don't know if it will be before that or not, sorry. You can subscribe to notifications in that issue, so you'd be notified when it's solved / closed.

**Comment by 591280714** [comment]
> I don't know if it will be before that or not, sorry. You can subscribe to notifications in that issue, so you'd be notified when it's solved / closed.

Already subscribed! you guys are amazing!

**Comment by dtugend** [comment]
> Already subscribed! you guys are amazing!

I meant #716, because I will close thise one.

**Comment by dtugend** [comment]
Forgot to notify you that HLAE GoldSrc supports it now since HLAE 2.126.0 (2022-03-11T22:36Z) or newer (needs updated afx-blender-scripts too.
