### ISSUE TITLE
Can you add support for Alien Swarm: Reactive Drop?

### ISSUE THREAD

**Issue by Dumbstep** [ripieces/advancedfx#735]
Alien Swarm: Reactive Drop is a modified version of Alien Swarm, which is also released on Steam.

**Comment by dtugend** [comment]
I currently want to focus on HLAE 3 and other things when having time, so this might not happen soon.

The support would be limited to those items that are listed with "several" or "+ ?" in the command refreence of AfxHookSource in the Wiki.

If the modfication is compatible with Alien Swarm, there's a launch parameter to make HLAE treat it like Alien Swarm depsite other options (e.g. different `-game blah` option):   
`-afxGame swarm` - for more options for the `-afxGame` option that you can try, see this code snippet:
https://github.com/advancedfx/advancedfx/blob/6eca310e147b4e8a7b7a829ab56973313b2350b1/AfxHookSource/main.cpp#L2282-L2307

**Comment by dtugend** [comment]
Currently not planned.
