### ISSUE TITLE
Latest CS:GO Update (December 10/11) Broke mirv_pov

### ISSUE THREAD

**Issue by Dechno1337** [ripieces/advancedfx#737]
Problem in
C:\source\advancedfx\AfxHookSource\addresses.cpp:959 / 1751 / 1986(?) / 2047

However, after clicking OK on all of them, HLAE still hooks in-game, but mirv_pov seems to not work atm:

_] mirv_pov
Not supported for your engine / missing hooks!_

**Comment by TommyShen2021** [comment]
Same issue, please verify and help to fix.

Thanks a lot

**Comment by Dechno1337** [comment]
Those who don't want or can't wait for an update, downgrading CS:GO to version 1.38.1.0 will work with `mirv_pov`
