### ISSUE TITLE
MIRV_POV CRASHING

### ISSUE THREAD

**Issue by kaidos1** [ripieces/advancedfx#738]
After new update mirv_pov is crashing. Is this just for me or anyone have this problem too.

**Comment by dtugend** [comment]
What's the version in your HLAE title bar is it already 2.124.**4**?
If you are already on .4 then exactly which size in bytes is your AfxHookSource.dll (right click properties dialog, ther first smaller number of size in bytes of both).

**Comment by dtugend** [comment]
It's not crashing for me on 2.124.4, please provide a demo link and tick / time + mirv_pov value so we can investigate.

**Comment by kaidos1** [comment]
Will send a video what happend, please wait.

**Comment by kaidos1** [comment]
There is a video: https://streamable.com/z853cb
As you can see, it just crashed... "i needed to hide desktop but you can see what is going on." (EVERY DEMO NOT WORK FOR ME)

**Comment by dtugend** [comment]
Please first verify CS:GO game cache and let it download if it needs to at the end.
If that doesn't fix it, please provide one of the demos that crashes.

**Comment by kaidos1** [comment]
okay :)

**Comment by dtugend** [comment]
Also check you are on right version of CS:GO:
```
] version
Protocol version 13812 [1396/1396]
Exe version 1.38.1.2 (csgo)
Exe build: 12:18:39 Dec 10 2021 (8434) (730)
Windows version 6.2
Steam beta name: 
```

**Comment by kaidos1** [comment]
Thanks :) i just needed to verify the game files. thanks for the help <3

**Comment by dtugend** [comment]
Please leave it open, I just found a demo that crashes on my end.

**Comment by kaidos1** [comment]
will.

**Comment by Tycacto** [comment]
I'm just like you, when I use the mirv_pov command, my game is immediately out.

**Comment by dtugend** [comment]
https://github.com/advancedfx/advancedfx/releases/tag/v2.124.5

**Comment by kaidos1** [comment]
Again started crashing, i will try to download new version and tell you.

**Comment by dtugend** [comment]
2.124.5 is still bugged, needs another release.

**Comment by kaidos1** [comment]
i can see yes

**Comment by dtugend** [comment]
https://github.com/advancedfx/advancedfx/releases/tag/v2.124.6
