### ISSUE TITLE
Map info in .agr file.

### ISSUE THREAD

**Issue by ghost** [ripieces/advancedfx#744]
It would be very handy if the map's name was saved as metadata of the .agr file. It becomes a big problem when importing recordings from games that have a lot of maps, as your only way to know which one to load, is to either write them down manually, or to re-open the demo on which the .agr was recorded.

**Comment by Dechno1337** [comment]
Don't you need to name it anyway before recording? Might as well add the map to that name then?

**Comment by ghost** [comment]
That is what I am doing right now, however writing it into the metadata of the file would be more convinient.

**Comment by Devostated** [comment]
You would still have to read each file one by one, while you could just look at the name. What about having multiple games on the same map? Yet you wouldn't know which is the correct one.
In my opinion the best would be just to name your files like this.
`mirv_agr start <FilePath\<WhatHappens>_<PlayerName>_<Map>.agr>`

**Comment by dtugend** [comment]
In the light of CS:GO moving to CS2 that supports SFM, allowing for better export / tools / scripts than AGR can deliver, we currently don't plan to continue to work on AGR.
