### ISSUE TITLE
 can't use reshade and nskinz at the same time!!

### ISSUE THREAD

**Issue by Tycacto** [ripieces/advancedfx#746]
I use custom tool then I can use reshade, but for making movies I need the nskinz skin mod, I run the launchcsgo file, I can use nskinz but I can't use reshade, and vice versa when I use custom launch I use nskinz can't, hope you improve the software better. thank

**Comment by dtugend** [comment]
I don't see how this is an HLAE / advandedfx problem, also you are not supposed to directly inject nSkinz.dll, see your other issue here: https://github.com/advancedfx/nSkinz/issues/21#issuecomment-1003527193
