### ISSUE TITLE
More gameTime Dependent Commands in CS1.6

### ISSUE THREAD

**Issue by DuKeM-CSGO** [ripieces/advancedfx#750]
Without `demo_gototick` or `mirv_skip tick to`, it seems to lose a way to control CS1.6's demo's time exactly. However, using the shared files( _shared/MirvCampath.*_ ) , the command `mirv_campath` could certainly work. So is there a way to develop commands like `mirv_cmd` `mirv_skip time (to)` `mirv_time` in CS1.6, which is just similar to CSGO and work by `gameTime` of CS1.6 demo?

**Comment by dtugend** [comment]
Small Note: Not sure if you already know, but at least `mirv_campath` is already available in GoldSrc with the same command interface as in Source: https://github.com/advancedfx/advancedfx/wiki/GoldSrc%3Amirv_campath

**Comment by DuKeM-CSGO** [comment]
:)Yeah I have known that. But the other commands...

**Comment by Dechno1337** [comment]
I think people were usually using -demoedit in the launch options to enable the demo UI for the built-in campath system, but you also have access to a command scheduler in there if I recall correctly? After you add events, you can also use them to go to that exact demo time they are set for.

I think you can also already create campaths when the demo is paused (mirv_time equivalent in CS:GO) but I don't remember the exact process; if you had to wait for the campath to start playing and then pause the demo straight after? :thinking:

**Comment by Dechno1337** [comment]
P.S. GoldSrc also seems to have (not sure if recently added) `dem_jump` which can adjust the demo time in seconds, and also works with negative values to jump back in time.

**Comment by dtugend** [comment]
Hi. Thank you for your suggestion. The implementation of this feature in a reasonable time-frame is currently not realistic for me. After considering that together with issue #896 I am closing this request as not planned for now, since it would block other things I would like to still get done before that. Sorry for the copy pasta.
