### ISSUE TITLE
error 13 afxHook errorDescription Hook errorDescription

### ISSUE THREAD

**Issue by sonda1y** [ripieces/advancedfx#754]
https://github.com/advancedfx/advancedfx/discussions/categories/q-a
```
AfxError #13: 
Title: AfxHook errorDescription: Hook errorDescription```
what can i do? it gives me this every time. everything is up to date

**Comment by dtugend** [comment]
https://github.com/advancedfx/advancedfx/wiki/FAQ#common-error-codes-with-possible-solutions

**Comment by sonda1y** [comment]
> https://github.com/advancedfx/advancedfx/wiki/FAQ#common-error-codes-with-possible-solutions

ty

**Comment by Dechno1337** [comment]
Did it help? What caused it?

**Comment by sonda1y** [comment]
> Did it help? What caused it?

I think it was an extraction problem. reinstaled hlae and it worked perfectly
