### ISSUE TITLE
mirv_agr recordPlayerCameras not working anymore

### ISSUE THREAD

**Issue by Devostated** [ripieces/advancedfx#755]
mirv_agr recordPlayerCameras is not doing anything.
I tried using mirv_streams record agr, -1 and playerindex, HLAE 2.124.6 and 2.124.5, different demos and different Blender versions.

**Comment by dtugend** [comment]
<tt>mirv_agr recordPlayerCameras 0|&lt;iEntIndex&gt;|-1 - Disable (0), all (-1, default) or entity index of player camera to record. **_Needs recordPlayers enabled to work._**</tt>
