### ISSUE TITLE
sv_skyname is not working when watching a demo

### ISSUE THREAD

**Issue by janneheusler** [ripieces/advancedfx#762]
Hi, 

ive been trying to record some clips for a fragmovie with HLAE and i usually change the Sky to a different sky (vertigoblue_hdr) when recording but for some reason it doesnt change when i put the sv_skyname command in the console. When i just go onto aim_botz for example it works just fine, only in the demo it doesnt change. I also tried it with sv_cheats 1 and 0. 

Thanks in advance!

*edit: when i type it in the console the following messages occur:
Requesting texture value from var "$hdrbasetexture" which is not a texture value (material: skybox/vertigoblue_hdrrt)
Requesting texture value from var "$hdrbasetexture" which is not a texture value (material: skybox/vertigoblue_hdrlf)
Requesting texture value from var "$hdrbasetexture" which is not a texture value (material: skybox/vertigoblue_hdrbk)
Requesting texture value from var "$hdrbasetexture" which is not a texture value (material: skybox/vertigoblue_hdrft)
Requesting texture value from var "$hdrbasetexture" which is not a texture value (material: skybox/vertigoblue_hdrup)
Requesting texture value from var "$hdrbasetexture" which is not a texture value (material: skybox/vertigoblue_hdrdn)

**Comment by dtugend** [comment]
You already solved it(?)

**Comment by janneheusler** [comment]
Not really, but it seems like the issue is only vertigo. 

I could change the sky on all maps but vertigo, tried it on 3 different demos too. Seems like its no a coincidence but dont know why it doesnt work on one map. 

 
 

Gesendet: Freitag, 18. März 2022 um 16:25 Uhr
Von: "Dominik Tugend" ***@***.***>
An: "advancedfx/advancedfx" ***@***.***>
Cc: "apixcs" ***@***.***>, "State change" ***@***.***>
Betreff: Re: [advancedfx/advancedfx] sv_skyname is not working when watching a demo (Issue #762)


 

You already solved it(?)

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dtugend** [comment]
I think newer versions of vertigo have a skydome, while older version / demos don't.

To fix it you need to find the skydome material and hide it with mirv_streams actionFilter:

See background info:
https://github.com/advancedfx/advancedfx/wiki/Tutorial%3A-CS%3AGO%3A-Replace-sky-with-mirv_streams-on-nuke---inferno---train#background-info

For at tutorial regarding the picker see:
https://www.youtube.com/watch?v=KNj4CmUoWIs

**Comment by dtugend** [comment]
Hi, I tested it and the instructions are the as same for cobblestone sky and clouds (I updated the Wiki article):
https://github.com/advancedfx/advancedfx/wiki/Tutorial:-CS:GO:-Replace-sky-with-mirv_streams-on-nuke---inferno---train

List of skies:
https://developer.valvesoftware.com/wiki/Counter-Strike:_Global_Offensive_Sky_List

**Comment by dtugend** [comment]
(I assume my last reply solved it for you.)

**Comment by janneheusler** [comment]
Oh, sorry for not responding, i didnt use HLAE since then but will try it out in the coming weeks probably.

Thanks for sending me a possible Fix, i guess it will solve it.

 
 

Gesendet: Donnerstag, 24. März 2022 um 21:10 Uhr
Von: "Dominik Tugend" ***@***.***>
An: "advancedfx/advancedfx" ***@***.***>
Cc: "apixcs" ***@***.***>, "State change" ***@***.***>
Betreff: Re: [advancedfx/advancedfx] sv_skyname is not working when watching a demo (Issue #762)


 

(I assume my last reply solved it for you.)
