### ISSUE TITLE
Fix binds causing stutters in demo

### ISSUE THREAD

**Issue by viasux** [ripieces/advancedfx#763]
I believe this is an engine issue, but it appears that every time I press a key (all my binds are bound to change my crosshair color), it causes a stutter in the demo (not ingame). Possibly this is something HLAE could develop a fix for?

The exact bind for reproducibility is `+forward; toggle cl_crosshaircolor 1 2 3 4 5; r_cleardecals`

and +forward would be replaced with whichever bind :)

**Comment by dtugend** [comment]
I can not reproduce the issues, I get no stutters when executing that command in the demo.

If you mean demos recorded with that are causing the issue, then you can use [mirv_block_commands](https://github.com/advancedfx/advancedfx/wiki/Source%3Amirv_block_commands) to block commands from demos.

More likely your graphic settings in demos and in-game differ in an important aspect, meaning if they were the same it would stutter in-game too.

**Comment by viasux** [comment]
> I can not reproduce the issues, I get no stutters when executing that command in the demo.
> 
> If you mean demos recorded with that are causing the issue, then you can use [mirv_block_commands](https://github.com/advancedfx/advancedfx/wiki/Source%3Amirv_block_commands) to block commands from demos.
> 
> More likely your graphic settings in demos and in-game differ in an important aspect, meaning if they were the same it would stutter in-game too.

This is likely the issue, thank you!
