### ISSUE TITLE
CSGO AGR no animations

### ISSUE THREAD

**Issue by Devostated** [ripieces/advancedfx#764]
Latest HLAE version causes characters and weapons to have no animations, just position data.
![image](https://user-images.githubusercontent.com/30211694/163724471-7b9e4dd2-3290-4191-81eb-d4f1b11e550f.png)

Recorded in first person and free cam mode.
```
mirv_streams record agr enabled 1
mirv_streams record agr recordCamera 0
mirv_streams record agr recordPlayers 1
mirv_streams record agr recordProjectiles 0
mirv_streams record agr recordPlayerCameras 0
mirv_streams record agr recordViewmodels 0
mirv_streams record agr recordInvisible 0
mirv_streams record agr recordWeapons 1
```
 Didn't test other games yet.

**Comment by dtugend** [comment]
Thank you for reporting the issue.

As a workaround renable player cameras or view models until it's fixed.

Sorry.

Edit: other game's AGR is not affected, problem is CS:GO only.
