### ISSUE TITLE
hide_render is always False in CSS V34 and Steam CSS AGR.

### ISSUE THREAD

**Issue by filiperino** [ripieces/advancedfx#765]
Blender version: 3.1.2
Blender Source Tools version: 3.2.0
afx-blender-scripts version: 1.14.1
HLAE version: 2.128.2.0

Note: I only tested 2 demos in CSS V34 using latest HLAE version, but looking through the code i've come to the conclusion that the issue is also present in Steam CSS.

When importing CSS V34 AGR into Blender, I noticed on every armature's hide_render channel, keyframes are always set to 1.0 (False).

I looked through the commits and it seems in function CClientToolsCssV34::OnPostToolMessageCssV34, a line setting variable "wasVisible" to "pBaseEntityRs->m_bVisible" was removed. Then Steam CSS AGR got added and the same problem happens there. wasVisible is written to file but isn't set to anything, thus staying False. That's in contrast to TF2 or CSGO, where "wasVisible" is set to "pBaseEntityRs->m_bVisible || isViewModel".

If that's the issue then great, I'm just blindly guessing.

Here are two .zip files containing the demo, .agr file and .blend file each.
[bky_111000_4K_FAMAS_with_dbl.zip](https://github.com/advancedfx/advancedfx/files/8521226/bky_111000_4K_FAMAS_with_dbl.zip)
[MrFeldtz-35k-4kawp-double-d2.zip](https://github.com/advancedfx/advancedfx/files/8521217/MrFeldtz-35k-4kawp-double-d2.zip)

AGR settings used:
```
mirv_agr recordCamera 1
mirv_agr recordPlayers 0
mirv_agr recordWeapons 0
mirv_agr recordProjectiles 0
mirv_agr recordViewmodel 1
mirv_agr recordInvisible 0
```

**Comment by filiperino** [comment]
Issue persists when I record players or weapons, guessing it also affects projectiles and when recordInvisible is 1.

**Comment by dtugend** [comment]
https://github.com/advancedfx/advancedfx/releases/tag/v2.128.3
This should restore the old / intended behaviour.
