### ISSUE TITLE
CSGO Playdemo Crash with Current HLAE Version

### ISSUE THREAD

**Issue by DuKeM-CSGO** [ripieces/advancedfx#775]
After CSGO's update on 06/23/2022, I launched it through HLAE as usual:
```
HLAE.exe -csgoLauncher -autoStart -noGui -csgoExe ... ... ... ...
```
And CSGO launched without any error message boxes. Then I played a demo as usual:
```
playdemo "path\to\demo"
```
Then here's the loading interface, but before the progress bar completed, the game crashed and there's nothing wrong in the console.
I tried launching the game from Steam, then all worked right. So I guess there's something wrong with the HLAE.

**Comment by dtugend** [comment]
sorry forgot to mention there was an update
