### ISSUE TITLE
mirv_campath draw enabled 1 - breaks when opening video settings

### ISSUE THREAD

**Issue by dtugend** [ripieces/advancedfx#779]
opening video settings changes mat_queue_mode to -1, causing bugs or even crashes, since mirv_campath can not handle that.

**Comment by Dechno1337** [comment]
Couldn't you temporarily "disable" the preview when a user is opening a menu? And then re-enable it again when they exit any menus? Either by letting HLAE detect if a menu is open and change `mirv_campath draw enabled` to 0 or some other way. 😃
