### ISSUE TITLE
Demo skipping after mirv_camio import causes CSGO frozen

### ISSUE THREAD

**Issue by DuKeM-CSGO** [ripieces/advancedfx#782]
After a .cam file imported and viewed:
```
// Spawned the .cam file by the Blender addon
mirv_camio import start "path\to\file.cam"
```
Sometimes I want to replay it. So I just skip to where it started:
```
mirv_skip tick to ****** // Or demo_gototick
```
Then the game can randomly become frozen, and then be killed. It can sometimes work well, too.
I met this situation many times. Is it a HLAE or CSGO bug? Is it because my .cam file is so large(200+ KB), or `host_framerate` is set to 0, 600 or 700?

**Comment by dtugend** [comment]
For how long is it frozen, are you using `demo_index 1`?

Please first make sure that you are on the lastest HLAE version.
If in doubt please copy & paste the output of `__mirv_info` here.

If possible zip a .cam file that exposes the issue and provide it as example.
If you have further instructions for re-creating the issue, please also note them.

Edit: If possible please also check if the crash can be reproduced when not using camio too.

**Comment by DuKeM-CSGO** [comment]
Yes `demo_index` is enabled. Edit: It was frozen until I killed it by Windows Task Manager. Sometimes frozen little of seconds and worked as usual.
```
] __mirv_info
|
| AfxHookSource (Jul  8 2022 09:05:15)
| http://advancedfx.org/
|
| VClient: VClient018 (CS:GO)
| VEngineClient: VEngineClient014 (CS:GO)
| VEngineCvar: VEngineCvar007 (CS:GO)
| GameDirectory: H:\Program Files\Steam\steamapps\common\Counter-Strike Global Offensive\csgo
|
```
And what I found new is that I didn't execute `mirv_camio import end` before `mirv_skip`. This issue can be reproduced especially when the .cam played totally, but the camio didn't end.
I don't think `mirv_skip` or `demo_gototick` can make the game crashed, without camio. _I only met it on some `de_inferno` demos, thinking there's a wrong .dix file, which causes that a jump to a specific round(maybe round 2) crash the game._
The .cam file is [here](https://github.com/advancedfx/advancedfx/files/9136568/de_.mirage.zip). It did just the same issue with `mirv_skip tick to 44800`.

**Comment by dtugend** [comment]
Thank you. I can reproduce the issue.

**Comment by Skyfalllish** [comment]
What export settings do you use? My .cam file is only 4-9 kb and when i use mirv_camio import start i have just black screen in csgo
