### ISSUE TITLE
CSSv34 demo playback crash with mirv_campath draw enabled 1

### ISSUE THREAD

**Issue by INZAME** [ripieces/advancedfx#783]
In CSS v34 if there's any completed campath and it's visible `mirv_campath draw enabled 1` after pressing `Goto` in `Demo player` to previous ticks game crashes.
If `mirv_campath draw enabled` is `0` everything is ok.

**Comment by dtugend** [comment]
Is your HLAE 2.132.1 or newer or older than that? (says in title bar of GUI)

**Comment by dtugend** [comment]
https://github.com/advancedfx/advancedfx/releases/tag/v2.132.5
