### ISSUE TITLE
Sounds inconsistently recorded to the .wav file?

### ISSUE THREAD

**Issue by Markxy** [ripieces/advancedfx#785]
Hello!
The sound timings for separate audio events like gunshots for example are off in some cases. Multiple gunshot sounds put into one audio frame it sounds like.

Seems to depend on `host_framerate` and the playback speed/render speed.
I'm doing these basic commands + everything in the smoother demo guide and more.
```
host_timescale 0
mirv_snd_timescale 1
host_framerate 60
```
Started to notice this when render speed is close to realtime and `host_framerate` is 60.

I don't know the exact cause is so it's hard to consistently produce good/bad results.
What else can i look for?

Comparing 4 different runs on the same part of the demo:
![image](https://user-images.githubusercontent.com/25804528/181490920-63d6d30b-5304-421a-aa0e-6c05a26f7fe2.png)

Attaching a worst case example (bottom one in the above image, example at 3-6s and more at 50s+) 
There's also a good case example for it in there.
[soundcheck.zip](https://github.com/advancedfx/advancedfx/files/9208889/soundcheck.zip)

Also understand if it's the built in wav recorder for csgo that's causing the issue.
In this case, is there anything i can do to mitigate this issue except for recording at a higher framerate?

Another thought i had was fluctuations in the render speed over the recording period - could that affect it?

**Comment by dtugend** [comment]
how do you record sound / how do you record?

Edit: There's two ways to record with sounds nowadays:
1) mirv_streams
2) startmovie

Please also try the other way and check if it has same problem(s), because they should be similar unless Valve changed s.th. related to that.

Edit2:
1. Yes sound is framerate dependent, it's only mixed per frame.
2. I hope render speed doesn't affect it too much, but I can not rule that out atm.

**Comment by Markxy** [comment]
Recorded with mirv_streams

Tested with `startmovie` now. It seems to work the same way but i can't seem to replicate the worst case example on purpose where host_framerate is 60.
Also for 2 AK47 gunshots to sound at the same time, one shots sound would have to skip about ~6 frames?
600rpm = 10 rounds per sec = 6 frames per round @ 60fps

Forgot to add - in the above image, the top 3 are on my pc, with under different background loads each run. The bottom one is on a different PC, but don't know exactly what was going on at the time, total run was close to realtime.

**Comment by dtugend** [comment]
If possible for you, can you check if leaving host_timescale on 1 has a positive effect onto the sound?
(I know that will make slow recordings more laggy.)
I remember researching some issue that was caused by host_timescale 0, but don't remember what it was / if it was related to sound or not.

**Comment by Markxy** [comment]
Tested with host_timescale 1, recording configurations etc between the runs are identical. host_framerate 60 
![image](https://user-images.githubusercontent.com/25804528/181743320-12850d02-7964-4010-9bca-92abc37d2f01.png)


Seems to have the same issues where there is a discrepancy between timings.
Tried running with a cpu+gpu stress test. Note the bottom run's last section's waveform looks vastly different here.

Another thought - could i/o write speed limitations affect wav file composition?

**Comment by dtugend** [comment]
I will try to reproduce the issue in case I have time today or tomorrow.

However I noticed you only mentioned a share of the commands of the smoother demos guide (it has been updated quite a while ago):
> Execute these commands **after the demo has been loaded**:
```
sv_cheats 1
host_timescale 0
mirv_snd_timescale 1
cl_clock_correction 0
```
https://github.com/advancedfx/advancedfx/wiki/Source%3ASmoother-Demos#3

Are you using these commands completely and set them after the demo has been loaded (you didn't mention sv_cheats 1 and cl_clock_correction)?
Are you also giving some grace demo time for the interpolation system to sync to the new settings before you start recording?

**Comment by dtugend** [comment]
A general note: I am only worrying about sound quality problems here, if you record based on tick and especially after jumping, then the actual recording can shift several frames as you might know, due to the way the engine and interpolation system works, not much I can do about that random shift in time.

**Comment by dtugend** [comment]
I tried to reproduce the problem:

host_framrerate 60, only recorded sound
1. no sd guide, full speed
2. no sd guide, host_sleep 100
3. sd guide, full speed
4. sd guide, host_sleep 100

In all cases I did get no quality problems, however of course they are all randomly a bit shorter or longer, which is because of demo_gototick / tick based stuff being inaccurate with the interpolation system.

**Comment by Markxy** [comment]
[drive link here](https://drive.google.com/drive/folders/1BAAvTQDv1hjAu8yVZeSj569-xPmccFSa?usp=sharing)
^^ the csgodm_movie.cfg file has the above mentioned commands
it jumps to 2s before recording, plays 2s, then records.

If it's interpolation, it would go away after some time, correct? (the first examples had the same issue at 50s into recording without jumping in between)

It is curious because I haven't had this issue before with the same approach regarding demo + vdm.
Some variables have changed like host_framerate and hardware it runs on.

**Comment by dtugend** [comment]
btw what are your values for

snd_mixahead
snd_mix_async

when in the demo in question?

mine are 
snd_mix_async 1 (tried 0 as well now, no notable change)
snd_mixahead = 0.025

**Comment by Markxy** [comment]
I dont have these defined. I assume they are at default values?
edit:
seems they are also `snd_mix_async 1` and `snd_mixahead 0.025`

**Comment by dtugend** [comment]
Can you please do `soundinfo` in console:

```
] soundinfo 
XAudio2 Sound Device: Lautsprecher (Realtek High Definition Audio)
Channels:	2
Bits/Sample:	16
Rate:		44100
total_channels: 126
[....]
```

I suspect you might be using s.th. else than XAudio2 like me.

**Comment by dtugend** [comment]
Also this might be helpful to compare too
![image](https://user-images.githubusercontent.com/3610128/181751857-e1125c75-19a9-4f8b-bb44-52b15bbf32dc.png)

**Comment by Markxy** [comment]
on my pc it's the same XAudio2.
On the more troublesome device, it's this:
```
] soundinfo 
Direct Sound Device
Channels:	2
Bits/Sample:	16
Rate:		44100
total_channels: 101
  98: +ui\panorama\bg_chlorine_01.wav
  100: %music\valve_csgo_01\mainmenu.mp3

```
and the settings:
![image](https://user-images.githubusercontent.com/25804528/181753593-ff57e132-42b6-4b95-a677-adfb50c93a67.png)
i see the difference in "Play audio when game in background". Could this be it?

**Comment by dtugend** [comment]
> i see the difference in "Play audio when game in background". Could this be it?

I don't know tbh, the cvar is `snd_mute_losefocus 0`.

Edit: seems to have no effect for me.

**Comment by dtugend** [comment]
I tried with the files you provided, also with `-directsound` at various speeds (very fast, slow, ...) no problems sadly.
Even regardless of different engine_no_focus_sleep and snd_mute_losefocus values.

Maybe we can compare the CS:GO launch options you use (especially on problematic PC)?
Espeically anything with regards to direct sound / sound / threading / number of course / queues:

![image](https://user-images.githubusercontent.com/3610128/181756453-24a4e514-cd26-492c-b848-610916926341.png)

Edit: also consider to use mmcfg folder feature like me, to start with an otherwise clean config (some demos can mess up configs!) - but keep the old one, so if it helps we can try to find what caused it by comparing.

**Comment by Markxy** [comment]
I tried to confirm that it's based on hardware/system.
The recording is done programmatically in Sandboxes (Sandboxie), so I just ran the same program on the bad machine VS my pc - 3 different examples with same demo+vdm+csgo configuration.

The audio issue is consistent on the bad machine so seems it's a system configuration problem.

I updated the drive with examples folder for you to see.

**Comment by dtugend** [comment]
When you have time later or next week, can you try with a clean new, clean different mmcfg folder on the "bad" machine, please?

For example for using it from commandline see here:
https://github.com/advancedfx/advancedfx/wiki/HLAE-Interfaces#csgo-launcher

**Comment by Markxy** [comment]
Currently the game is launched using the -customLoader variant
```
"E:\HLAE\HLAE.exe" -customLoader -noGui -autoStart -hookDllPath "E:\HLAE\AfxHookSource.dll" -programPath "C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo.exe" -cmdLine "-steam -game csgo -insecure -applaunch 730 -novid -w 1920 -h 1080 -high -threads 4 -windowed -noborder -console -allow_third_party_software +exec launch_exec.cfg"
```
launch_exec looks like this:
```
con_logfile console.log
engine_no_focus_sleep 0
ui_popup_weaponupdate_version "2109"
mirv_block_commands add 5 "\*"
```

Then after game launches, playdemo is issued and rest comes from vdm + csgodm_movie

**Comment by dtugend** [comment]
For customLoader you can use `-addEnv "USRLOCALCSGO=C:\path\to\your\mmcfg-folder"`

**Comment by dtugend** [comment]
Also consider removing these for testing as said earlier: `-high -threads 4` since they affect the threading.

Edit: changes nothing regartding sound for me at least :(

**Comment by Markxy** [comment]
removing `-high -threads 4` didnt change much for me either unfortunately.
With the mmcfg folder, did you have anything specific in mind?

I've tested the whole process on 3 machine types: my pc ("normal" computer), one type of VM, and another type of VM. The issue only persists in the last type so i don't think it's a matter of game configuration/setup/runtime?

It probably has to do something with the audio device for that VM type which the recorded audio has to go through.
Tried installing a virtual audio device and setting `sound_device_override 2` before loading the demo, but issue still persists. Perhaps something else on a lower level in the system. Or trying to get XAudio2 enabled? hmm..

I will keep digging, will post updates if i get anywhere. Also thank you so much @dtugend , you've been so helpful so far ❤️

**Comment by dtugend** [comment]
> With the mmcfg folder, did you have anything specific in mind?

The point is to make it start with a clean cfg by setting an empty fresh folder (e.g. on your desktop), otherwise it can be already tainted from the one already on the machine or even the one tied to the Steam account downloaded from the cloud.

**Comment by dtugend** [comment]
Another note additionally to the one above:

I am not sure, but I don't think it's the DirectSound causing the problem: I started with `-directsound` in CS:GO launch params and that makes it use DirectSound as well and I had no problems (but you can try that to see if you get problems on your machine, maybe mine is too old).

I'd presonally look into the number of CPU cores and more importantly threads on the machine that has probelms, as well as the OS used (though the latter shouldn't have a negative effect on sound).

**Comment by Markxy** [comment]
With the `-directsound` option on my PC, it produces the same "double gunshot" audio issue.

The hardware+os is similar for both cases so it does makes sense. 5900x/5950x + 3080/Ti + Win10

**Comment by Markxy** [comment]
Installed a package of directx (2010) from here: https://www.microsoft.com/en-us/download/details.aspx?id=8109
so the "bad" machine uses XAudio2 now as default - no "double gunshot" audio issue anymore!

Thanks again @dtugend!

**Comment by dtugend** [comment]
Please leave the issue open, I will try to reproduce the issue one more time (we got one a complaint about s.th. similar a while ago and were not able to reproduce it back then).

**Comment by Markxy** [comment]
Of course, let me know if i can help/run any tests for you.
For ref, 2 runs for me where the only difference is the `-directsound` launch option:
[XAudio2_directsound.zip](https://github.com/advancedfx/advancedfx/files/9235711/XAudio2_directsound.zip)

**Comment by dtugend** [comment]
It's probably a multithreading issue when the sound is mixed asychnonously on a separate thread.

**Comment by dtugend** [comment]
It's multithreading issues that are mostly observable with `-directsound` launch option and `snd_mix_async 1` cvar.

**Comment by Markxy** [comment]
Interesting. So these minor timing deviations/inconsistencies i recorded earlier have the same root cause?

**Comment by dtugend** [comment]
> Interesting. So these minor timing deviations/inconsistencies i recorded earlier have the same root cause?

I can not answer that yet.

However I noticed that you have host_timescale on 1 in your config, while the Smoother Demos guide requires it on 0.
This will lead to lags upon slow recordings / record jitter.

**Comment by dtugend** [comment]
<strike>Also if you can test if `snd_mix_async 0` fixes most of the problems, would be great.
Edit: results might be better with additionally `mirv_cvar_unhide_all; snd_noextraupdate 1`</strike>

**Comment by Markxy** [comment]
> However I noticed that you have host_timescale on 1 in your config, while the Smoother Demos guide requires it on 0.

It was `0` normally, it seems i hadn't switched it back from previous testing in this thread when i uploaded the cfg to drive.

**Comment by dtugend** [comment]
> Interesting. So these minor timing deviations/inconsistencies i recorded earlier have the same root cause?

Apparently multiple wave form and loudness issues yes, small time shifting issues due to interpolation and demo_gototick inaccuracies no.

I found that startmovie alone with `snd_mute_losefocus 0`  (when NOT using additionaly mirv_streams!) generates acceptable results apart from the timeshift (at least I don't know a method yet to avoid the timeshift, maybe cl_interpolate 0 and then cl_interpolate 1 on a tick enough time before would solve that, but I didn't test that).

I will try to get the startmovie sound (that is fixed nowadays) into mirv_streams sound when I have time.

Here's an example (don't forget to rename the test to test2, test3, test4 and so on and to delete the many test*.tga files in csgo folder afterwards in case you  test it).
[003562642938586464269_0357571491.vdm.txt](https://github.com/advancedfx/advancedfx/files/9259985/003562642938586464269_0357571491.vdm.txt)

**Comment by dtugend** [comment]
https://github.com/advancedfx/advancedfx/releases/tag/v2.133.0

**Comment by Markxy** [comment]
Tested `-directsound` + `mirv_streams record start` with version 2.133 prerelease.
Sounds great!
[133_directsound.zip](https://github.com/advancedfx/advancedfx/files/9261872/133_directsound.zip)
