### ISSUE TITLE
mirv_calcs handle add or

### ISSUE THREAD

**Issue by Markxy** [ripieces/advancedfx#791]
Taking **priusfx** as example:
```
mirv_calcs handle add localPlayer priusfxLocalPlayer
mirv_calcs handle add observerTarget priusfxObserverTarget priusfxLocalPlayer
...
```
The above works with GOTV demos.

But that doesnt work with `mirv_pov` or POV demos as observerTarget doesn't work, it would be just (for the following calc vecAngs to work):
 ```
mirv_calcs handle add localPlayer priusfxObserverTarget
```

Would be convenient if i could just add an OR statement for the base handle to be one or the other handle if the first is false, similar to `mirv_calcs vecAng add or`
Like this:
```
mirv_calcs handle add localPlayer priusfxLocalPlayer
mirv_calcs handle add observerTarget priusfxObserverTarget priusfxLocalPlayer

mirv_calcs handle add or myNewHandle priusfxObserverTarget priusfxLocalPlayer
```
^^ and then following vecAngs can use `myNewHandle` instead

**Comment by dtugend** [comment]
Did it work?! ( https://github.com/advancedfx/advancedfx/releases/tag/v2.137.2 )

**Comment by Markxy** [comment]
Yes, `mirv_calcs handle add or` works perfectly! Thanks a lot!
Allows me to have the same vecAng calcs for both cases instead of keeping duplicate vecAngs based on the 2 different base handles. Saves a lot of time.
