### ISSUE TITLE
[Goldsrc] mirv_voice_block doesn't work 

### ISSUE THREAD

**Issue by SanAntonio2** [ripieces/advancedfx#792]
I would like to record the voice of a specific player, but unfortunately several players were speaking at that moment. I found the id of the players I don't want to hear. Through "mirv_voice_block add 11(random player's id number)" I added them to list of blocked entity ids, but I keep hearing them in the game. The command just doesn't work.

Cstrike version:
Protocol version 48
Exe version 1.1.2.7/Stdio (cstrike)
Exe build: 19:53:27 Aug  3 2020 (8684)

Hlae version: 2.137.2

**Comment by dtugend** [comment]
Hello.

Please provide an example demo download / link and list the exact relevant commands used please, so we can try to reproduce the issue.

**Comment by dtugend** [comment]
If you don't want to share the demo publically, you can also email a download (link) to contact@advancedfx.org.

**Comment by SanAntonio2** [comment]
> If you don't want to share the demo publically, you can also email a download (link) to [contact@advancedfx.org](mailto:contact@advancedfx.org).

I'm sorry, I haven't been home for a few days, I'll try to send and explain everything to you.
Is it okay if I send you not just demo but the archive with demo (mb also with cfg and readme)?

**Comment by SanAntonio2** [comment]
[Voice_block.zip](https://github.com/advancedfx/advancedfx/files/9440234/Voice_block.zip)

**Comment by dtugend** [comment]
This will be fixed in next release, if you don't want to wait until that, here's the fixed AfxHookGoldSrc.dll (just replace the latest one with this one).
[AfxHookGoldSrc.zip](https://github.com/advancedfx/advancedfx/files/9446481/AfxHookGoldSrc.zip)

Thank you very much for your detailed issue report and sorry it too me long to reply.

**Comment by dtugend** [comment]
https://github.com/advancedfx/advancedfx/releases/tag/v2.137.3
