### ISSUE TITLE
Extra function for "mirv_streams print" command

### ISSUE THREAD

**Issue by eirisocherry** [ripieces/advancedfx#797]
Let's say "mirv_streams print more" (yeah, a new command so people who get used to the old command don't get confused)
With the new formatting you don't have to strain your eyes finding what layers are on/off + it also shows recording preset that is currently set for a certain layer (very useful). Different ideas require different layers and the new menu will save a lot of time, trust me. 

![yes](https://user-images.githubusercontent.com/115040224/193914899-83c5382a-de0e-49e6-8850-93f95d0fcd36.png)

**Comment by eirisocherry** [comment]
I think this Rikki guy is suggesting a good feature, can't wait to see what streams are set to record without eyes strain!

**Comment by dtugend** [comment]
This will be available similar to what you suggested in the next upcoming release as
```
mirv_streams print2
```

**Comment by Dechno1337** [comment]
If you adjust the afxDefault setting, shouldn't it say which preset you are using on that? Now it only mentions which preset you use if you edit the recording setting of each stream individually.

```] mirv_streams print2
============================================================
index: name (recording preset)

[R] RECORD ON
0: base (afxDefault)
1: depth (afxDefault)

==== Total streams: 2 ====
] mirv_streams settings edit afxDefault settings
mirv_streams settings edit afxDefault settings <settingsName> - Use settings with name <settingsName> as default settings.
Current value: "huffyuv"

**Comment by dtugend** [comment]
I don't plan recursion, I think it's ok the way it is.
