### ISSUE TITLE
Deathmsg

### ISSUE THREAD

**Issue by keyo0o** [ripieces/advancedfx#799]
Hello, I'm asking for help with editing CSGO montage. When I set deathmsg config for it to look different than the default one, it won't record with the "mirv_streams record" command. It's visible in the demo, but it won't record afterwards. I don't want to record screen with a recording software, because I prefer to work with 3 layers (world, matte and depth). Does anyone know how to fix it?

**Comment by dtugend** [comment]
```
mirv_streams edit <yourStreamNameHere> drawHud -1
```
This will make the HUD behave as the game would by default on the stream named `<yourStreamNameHere>`.

It's also possible to separte the HUD perfectly for later composing:
https://github.com/advancedfx/advancedfx/wiki/Tutorials#tutorial-csgo-separate-hud-stream

**Comment by dtugend** [comment]
If you are new to HLAE and still need more help, checkout the other tutorials linked on same page and if you want also try the Discord chat linked here: https://www.advancedfx.org/support/
