### ISSUE TITLE
Added support for Titanfall 2

### ISSUE THREAD

**Issue by SinOfHyped** [ripieces/advancedfx#800]
Hi, i come from the titanfall 2 community, you probably know it is also a source game.
we have many aspiring and existing titanfall 2 editors, who would love to create creative content like CS:GO is able to
personally, i love the features HLAE has with seperating depth maps, gun clips, world layers and with options to rewind and go forward in demos in the most User-friendly manner as possible.
I would like to request on behalf to add titanfall 2 support to HLAE, as this would prove very useful and we would be very grateful, HLAE team, I love the effort you have put into this tool
Thank you,
Regards,
Sin

**Comment by dtugend** [comment]
Currently not planned.
