### ISSUE TITLE
Error-AfxHookSoource When opening CSGO with HLAE.

### ISSUE THREAD

**Issue by 15590090090** [ripieces/advancedfx#801]
Hi guys this pop up when I trying to open CSGO with HLAE. Does it relate to the update of CSGO Major today?
(1) I'm using 'Launch CS: GO' from the HLAE menu. 
(2) And I'm sure I'm using the right path of 'csgo.exe', Same as the Steam 'Browse Local Files' Button shows.
Please let me know how to fix it. Thanks a lot.

![QP{H L7~GFARS6DC0 @OS}3](https://user-images.githubusercontent.com/45844576/197324660-3fab43bb-be26-406a-83ad-b38a832b554c.png)

**Comment by dtugend** [comment]
This is due to the CS:GO update.
We are trying to work on a HLAE update.
No ETA atm.

**Comment by 15590090090** [comment]
> This is due to the CS:GO update. We are trying to work on a HLAE update. No ETA atm.

Thank you very much. Please let us know when the update is released.

**Comment by dtugend** [comment]
A new Release will come in about 30 minutes from now.

**Comment by dtugend** [comment]
https://github.com/advancedfx/advancedfx/releases/tag/v2.141.0

**Comment by 15590090090** [comment]
Thanks a lot.
