### ISSUE TITLE
HLAE

### ISSUE THREAD

**Issue by zekeestar** [ripieces/advancedfx#802]
AfxError #2002:
Help me pleas,i already turned off anti-cheat
Name: The loader cannot create the requested process. Description: GetLastWin32Error = 5: Permission denied Solution: Don't forget to close ESEA Client, FACEIT Client, Challengeme.gg, etc. anti-cheats. before using HLAE.```

**Comment by dtugend** [comment]
https://github.com/advancedfx/advancedfx/wiki/FAQ#common-error-codes-with-possible-solutions
