### ISSUE TITLE
AfxHookSource error

### ISSUE THREAD

**Issue by kaidovina** [ripieces/advancedfx#803]
Hello, after update i still get this error.
![image_2022-10-22_194520364](https://user-images.githubusercontent.com/102692815/197355197-84f98896-b32e-4cf3-a8c4-83ad9ffc55cf.png)

 How can i fix it?

**Comment by dtugend** [comment]
https://github.com/advancedfx/advancedfx/wiki/FAQ#common-error-codes-with-possible-solutions

**Comment by kaidovina** [comment]
I tried everything but its still not working. "Dll can't be found."

**Comment by dtugend** [comment]
is the AfxHookSource.dll even there?
What are your settings?
Conisder asking in our Discord chat for support, we might be able to reply faster there.
