### ISSUE TITLE
Improvements to collisionClip 

### ISSUE THREAD

**Issue by Markxy** [ripieces/advancedfx#804]
Hello!

Ref to original feature request: https://github.com/advancedfx/advancedfx/issues/713

The collisionClip mirv_calcs method does what it's supposed to well, but there are a couple common cases where the outcome looks glitchy at times:
- camera is collisionClipped against a wall, player moves along the wall/ceiling, camera follows along wall/ceiling, but if the surface is uneven, making the camera jump back and forth.
- camera is collisionClipped and following a player, then the spectated or other players throws or unequips a weapon/bomb. The item crosses the collisionClip path for a short time, making the camera jump back and forth.

The "ideal" that i have in mind is how 3rd person (`thirdperson` command) or the third person camera behaves as a spectator. They seem to behave similarly.

First wall/ceiling tracking issue could be solved by smoothly going back to the max collisionClip distance. (similarly how csgo's builtin thirdperson cams do).
If collision detected, move closer immediately (maybe also have a delay before moving back?), then smoothly go back towards max distance or until collision is detected.

Second issue could be solved by having an option to essentially ignore all entities except the world and other players? Or ignore all equippable entities? (currently ignoring just one handle which is usually `observerTarget`).

`thirdperson` also has some rotation smoothing options with `cam_ideallag`. Not essential to have something similar to that here and I cant imagine how difficult it is to implement, but would also help smooth out anything "too fast".

Link to video where these issues are seen (not worst cases but just to get the idea): https://drive.google.com/file/d/1kaRp42kRf-q6My7qGXiehdB-TpUc0QQO/view?usp=sharing

**Comment by dtugend** [comment]
[AfxHookSource.zip](https://github.com/advancedfx/advancedfx/files/10073343/AfxHookSource.zip)

To use the new options you will need to edit your collisionClip calc:
```
mirv_calcs vecAng edit collisionClipNameHere ignoreSome 1
mirv_calcs vecAng edit collisionClipNameHere sleepTime 1.0
mirv_calcs vecAng edit collisionClipNameHere smoothTime 5.0
```
Time is in seconds, i used a bit extreme values for testing (sleepTime 0.5 and smoothTime 2.5 seems better in practice).

For smoothing the rotation etc, condier to:
- Use mirv_cam options to turn off roll override, so the camera won't roll anymore: `mirv_cam source anglesUse 0 1 1`
- Maybe smooth the input calcs with other mirv_calcs.

**Comment by Markxy** [comment]
Works wonders!
Thanks @dtugend ! ❤️ 

Will try to mess around with the rotation smoothing soon
