### ISSUE TITLE
Sometimes no video/audio output after 2.133

### ISSUE THREAD

**Issue by Markxy** [ripieces/advancedfx#806]
I've had the recording process using `mirv_streams` done the same way for a while now and it has worked well.

After Aug 4th, it's a very low % of the runs, but does happen quite consistently - sometimes it doesn't output video or audio anymore.
The https://github.com/advancedfx/advancedfx/releases/tag/v2.133.0 update was at that time.
Attatched an example vdm which can cause this.
[example.zip](https://github.com/advancedfx/advancedfx/files/9950814/example.zip)

One possibility that came to mind was that the `mirv_streams record end` and `quit` commands are executed in the .vdm file at the same tick. And that the 2.133 update made some changes regarding (async) audio/video processing.
Is it possible that the recording isnt wrapped up fast enough and writing the output is aborted?

And in general, is it generally the case that recording is wrapped up while the `mirv_streams record end` command is processed?
(i.e a case where `mirv_streams record end` is @ tick 1000 and `mirv_streams record start` is @ tick 1001 for a new take)

The .vdm file ending would look something like this:
```
"9"
{
	factory	"PlayCommands"
	name	"spec"
	commands	"mirv_streams record end"
	starttick	"89880"
}
"10"
{
	factory	"PlayCommands"
	name	"spec"
	commands	"quit"
	starttick	"89880"
}
```

Another clue i have is that when this happens (no output), the end of CSGO logs look like this (after csgo is closed):
```
Starting recording ... done.
Recording to "C:\output\HLAEOUT\take0000".
```
When it's successful, should be like:
```
Starting recording ... done.
Recording to "C:\output\HLAEOUT\take0000".
Finishing recording ... done.
Host_Shutdown
(... what it usually does when csgo quits)
```
In this case i'm not sure how it's related to the update but may be mentionworthy.

**Comment by dtugend** [comment]
> it doesn't output video or audio

Can you please elaborate which of these happen (mabye all?):
- no video
- no audio
- no video and no audio

Also please check if the files are just broken or actually really missing in disk (they should be just broken).

Hi. There were indeed changes to the audio recording, but I suspect it's more likely due to either a CS:GO update that changes the way it shuts down or due to a change in your config settings when we worked on fixing the sound bugs for DirectSound audio devices and not due to the changes themselves, but I am not sure yet. and need to investigate.

> Another clue i have is that when this happens (no output), the end of CSGO logs look like this (after csgo is closed):

This could actually indicate a problem that can trouble HLAE recordings:  
Recordings are finalized when a new recording is started or alternatively recording is ended (both should print "Finishing recording ... done.").

If this is skipped it can have severe effects:  
- The wav header will not be correctly updated, and while the file is not empty it will report a null size / length in that case / be broken.
- If ffmpeg is used and terminated too early, it could lead to missing frames at best and broken or slow files at worst.

----

I will try to investigate the problem as soon as I have time, in the meantime you could test if using `mat_queue_mode 0` affects the problem or not (default -1. 0 is slower (depending on hardware up to 50% slower), since it doesn't queue new renderings while the old data is rendered, but instead does it without queueing).

**Comment by Markxy** [comment]
So the method that checks these outputs is Python's `os.path.exists()` method which returns `False` for one or both of the files on this issue. I assume the file is not there.

I believe I didn't change anything on my end, nor does there seem to be a csgo update on Aug 4th, this is just where i ended up looking for the cause atm.

Because of the order of operations and current logging on my end, I can confirm that these cases can happen:
- no video output (don't know about audio in this case)
- no video and no audio

To clarify, on Aug 1st I started using XAudio2 in all cases after installing necessary directx prerequisites to solve the audio issue, but this case arose on the 4th (after switching to HLAE 2.133). Ref to [related audio issue for posterity](https://github.com/advancedfx/advancedfx/issues/785)

I'll try to test with `mat_queue_mode 0` but it'll take some time

**Comment by dtugend** [comment]
Which HLAE version are you using?
I am having trouble recreating it, but maybe it's sort of random?

I am using 2.142.2 for the testing.

**Comment by dtugend** [comment]
Also please check if there's crashdumps (*.mdmp or *.dmp) from when it was missing files in the following folders:
- C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive
- C:\Program Files (x86)\Steam\dumps

**Comment by dtugend** [comment]
Here is a HLAE / AfxHookSource.dll version like the latest HLAE v2.142.2, but with the old sound system for testing as you/we suggested:
Source: https://github.com/advancedfx/advancedfx/tree/old-sound-sys
<strike>Compiled AfxHookSource.dll: [AfxHookSource-old-sound-sys.zip](https://github.com/advancedfx/advancedfx/files/9991287/AfxHookSource-old-sound-sys.zip)</strike>

**Comment by dtugend** [comment]
Hi. There was an address uninitizalized that the old sound system needs, I pushed the fix and here is a new compiled version:
[AfxHookSource-old-sound-sys-2.zip](https://github.com/advancedfx/advancedfx/files/10003002/AfxHookSource-old-sound-sys-2.zip)

**Comment by acrossoffwest** [comment]
I just updated HLAE from v2.132.5 to v2.142.2 and HLAE wasn't record video, after I had add your last AfxHookSource.dll everything works fine, thank you.

**Comment by dtugend** [comment]
@acrossoffwest
It might help us very much with fixing in case you can easily reproduce the problem on v2.142.2,  
if you can provide us with information about your setup / way you can reproduce it, e.g.:
- What does not record mean? Does it crash / close or just not record? Any error messages?
- HLAE launch options, especially CS:GO command line options
- CPU / number of cores/threads
- GPU
- What you can do to trigger the problem (e.g. relevant parts of movie-making config if possible).

The reason I am asking this, is because the new sound recording system is superior in sound mix quality compared to the old one (when it does work), so I'd prefer to fix the new one instead of having to revert to the old one.

**Comment by dtugend** [comment]
I fixed some potential threading issues that could happen when starting the recording / recording was started / when hooking upon starting recording:
https://github.com/advancedfx/advancedfx/commit/32bc0414e6b3e6cbb6afce4efe3cd3b1d3498404
If someone could test if the error rate is the same as old sound system or still higher would be very helpful.
(Hint the failure rate is 0.5% (read 1 of 200) with current the official version in number of sessions, but it should be close to or even at 0% if I found the right problem.)

**Comment by dtugend** [comment]
Uploaded wrong one, here is the new one: 
[AfxHookSource-20221117T1518Z.zip](https://github.com/advancedfx/advancedfx/files/10032927/AfxHookSource-20221117T1518Z.zip)

**Comment by Markxy** [comment]
For posterity, from my testing, the [old sound system build](https://github.com/advancedfx/advancedfx/issues/806#issuecomment-1313630044) worked as it did before 2.133. This issue wasn't present anymore.

Using the [new sound system build](https://github.com/advancedfx/advancedfx/issues/806#issuecomment-1318799031), it started occurring again.

It's quite random - multiple runs on the same demo/vdm can produce it on one run, but not in other runs.
Failure rate is also low, around or less than 0.5% or so.

**Comment by dtugend** [comment]
I found a mistake, the CL_StartMovie wrapper is not properly balanced stack-wise and thus smashes some stack memory, so randomly it might lead to problems, depepnding on the values smashed in:
https://github.com/advancedfx/advancedfx/blob/main/AfxHookSource/csgo_Audio.cpp#L157
Will fix it. Worst Part is that wrapping code is not even needed, especially not the way I did it.

**Comment by dtugend** [comment]
Yesterday I let it do 33 recordings of an example demo I got automatically.
All had audio.wav, however the second and third recording lacked the video.mp4.
If possible for you and when you have time (e.g. next week), it would be helpful if you could add info for the failed runs about which of the two files are actually missing (none/both/video/audio).
In case you restart the VM / PCs, it would also be helpful to count which number of run it is after restarting.

**Comment by Markxy** [comment]
Like i posted previously, i can confirm that these cases happen:
> no video output (don't know about audio in this case)
> no video and no audio

I can add more logging next week to get more detailed info

**Comment by dtugend** [comment]
[AfxHookSource_20221115T1137Z.zip](https://github.com/advancedfx/advancedfx/files/10092415/AfxHookSource_20221115T1137Z.zip)
Edit: messed up the date in the filename but it's from today.

I found an possible issue when mirv_streams recording is restarted on the engine thread while the capturing did not finish yet on the drawing thread.

The build above has that issue addressed and also includes the current previously commited features (such as collisionClip improvements etc).

However it might be not the main offender.
Nevertheless if possible when testing again when you have time in a few days, please use this build unless there's a newer one available by then of course.

**Comment by dtugend** [comment]
[AfxHookSource_20221201T1507Z.zip](https://github.com/advancedfx/advancedfx/files/10133513/AfxHookSource_20221201T1507Z.zip)

Thanks to @Markxy from Allstar.gg for helping to track down and debug this particular issue, we found one problem in the CS:GO code.
Hopefully the workaround is able to fix it already (if I did no notable mistakes myself).

**Comment by dtugend** [comment]
Ther was a mistake in the fix: https://github.com/advancedfx/advancedfx/commit/4eb827bb930d4b6f9dde75a56f87ca0277a493f7
Also fixed a few other small things.
[AfxHookSource_20221202T1552Z.zip](https://github.com/advancedfx/advancedfx/files/10142441/AfxHookSource_20221202T1552Z.zip)

**Comment by dtugend** [comment]
https://github.com/advancedfx/advancedfx/commit/089c0f25bd2b1a71be509f1c2e2523135e5a9a11

[AfxHookSource_20221212T1814Z.zip](https://github.com/advancedfx/advancedfx/files/10211296/AfxHookSource_20221212T1814Z.zip)

```
mirv_block_commands logFile "hlae_cmd_log.csv"
```

**Comment by dtugend** [comment]
I am closing this issue until further info is available:
1. The cause identified related to startmovie has been fixed / a workaround applied.
2. The remaining issues don't have a crashdump available or a unrelated to this issue.

Please reopen this issue or open a new issue when more information becomes available.
