### ISSUE TITLE
Does and will this have support for macOS? 

### ISSUE THREAD

**Issue by Rchan0100** [ripieces/advancedfx#811]
I tried wine stable and it doesn't seem to download... if it does work for Mac, how should I go about this?

**Comment by dtugend** [comment]
Sadly I don't know if it can work on Mac. I only know that it can be made to work on x86 comptabilbe CPUs with wine and winetricks (to install .NET 4.5 framework) on serveral Linux distros (e.g. Debian and ArchLinux). For it to work you would also have to install Steam + CS:GO in Wine and use the CS:GO wine version with HLAE.

What do you mean by "it doesn't seem to download"?

**Comment by dtugend** [comment]
To answer the other part of your question: we don't plan a native Mac OS port of HLAE so far, but you might be able to get it to run in wine similar to Linux.
