### ISSUE TITLE
mirv_spec_player key

### ISSUE THREAD

**Issue by JJoTech** [ripieces/advancedfx#815]
Introduce '**mirv_spec_player key**' which will allow live observers to swap seamlessly between a campath and a active player without having to setup multiple custom binds or use 3rd party software such as autohotkey to achieve the same result.

Theory: Grab the existing player IDs from the server and assign them so that they can be called upon using the default observing number keys 0-9.

Usage: **mirv_spec_player '0|9'** would be combined with '**mirv_campath clear** or **mirv_campath enabled 0**' to reset the campath mid flight and select the desired player.

Example: 

**Campath Start**
'spec_mode 6;mirv_campath enabled 1;mirv_campath clear;mirv_campath load AnubisCTA;mirv_campath edit start' 

**Campath Clear & Switch to Player** 
'mirv_campath clear;spec_mode 4;mirv_spec_player 1'

Camera will exit the active campath and switch to the player marked as "1" on the HUD.

**Comment by dtugend** [comment]
Scheduled for the upcoming release, here is a test compile:
[AfxHookSource_20221204T1742Z.zip](https://github.com/advancedfx/advancedfx/files/10149124/AfxHookSource_20221204T1742Z.zip)
