### ISSUE TITLE
Make local axes mouse movement

### ISSUE THREAD

**Issue by eirisocherry** [ripieces/advancedfx#817]
When you `rolling the camera (z/x)` you can clearly see, that your mouse uses world axes. It's super hard to get the right position with such thing.

It will be x100 better if the mouse could use local axes as `camera position binds (w/a/s/d/f/r)` do.

**Comment by dtugend** [comment]
`mirv_input cfg rotLocalSpace 1`

**Comment by eirisocherry** [comment]
THANK YOU! I tried it out, it works as I expected.
It's even fun to use when you're not making an upside down cinematic. I mean when you fly and move the mouse at the same time the camera automatically rolls, I really enjoy it.
