### ISSUE TITLE
HUD occasionally break when using mirv_pov in CS:GO

### ISSUE THREAD

**Issue by Dibberdini** [ripieces/advancedfx#821]
The HUD will occasionally get stuck in the 'weapon picked up' animation.

Example: [https://youtu.be/mjtNTtSvXhE?t=1207](https://youtu.be/mjtNTtSvXhE?t=1207)

Unsure of specific requirements to reproduce, but it only seems to be happening with dropped weapons. Specifically when a teammate drops a weapon to the POV-player during freezetime.

Also only appears to happen when using mirv_pov.

**Comment by dtugend** [comment]
The bug happens for instant-buy quick-dropped weapons, in that case the first person crosshair is missing in GOTV mode (or the animation loops for mirv_pov) and in 3rd person the weapon is missing.

This is not an HLAE bug, this is an CS:GO bug, please report it instead to CSGOTeamFeedback@valvesoftware.com.
Be aware that it even happens in live matches on GOTV regardless of HLAE and observers already reported it multiple times to them, so good luck.

**Comment by dtugend** [comment]
https://twitter.com/FrostyOBS/status/1396812803445567489

**Comment by Dibberdini** [comment]
Ah sucks, that they haven't fixed it. Thanks!
