### ISSUE TITLE
mirv_skip time toGame

### ISSUE THREAD

**Issue by ChetdeJong** [ripieces/advancedfx#823]
mirv_skip to go to certain gametime (e.g. 3057.632813), not demotime

**Comment by dtugend** [comment]
https://github.com/advancedfx/advancedfx/commit/2755e271788ba00a9b763d648d71b55dad6e6728
[AfxHookSource_20230126T2140Z.zip](https://github.com/advancedfx/advancedfx/files/10513583/AfxHookSource_20230126T2140Z.zip)

**Comment by ChetdeJong** [comment]
Thank you!
