### ISSUE TITLE
is there any workaround to get playerIndex by steamid?

### ISSUE THREAD

**Issue by qo** [ripieces/advancedfx#824]
i know it's gonna be one of the v3 features (https://github.com/advancedfx/advancedfx/issues/322) but i'm still wondering if there is some way to do it now

**Comment by Dechno1337** [comment]
Isn't that what the XUID is?
https://github.com/advancedfx/advancedfx/wiki/Source%3Amirv_deathmsg#selection-of-players

Though, I don't remember if it's limited to specific commands. 🤔

**Comment by qo** [comment]
yeah it would be awesome to be able to pass XUID to mirv_pov, but it needs playerIndex. i can find it by running mirv_listentities isPlayer=1, but i'd like to somehow get the playerIndex by this player's XUID without playing the demo. is there any way to make it happen?

**Comment by qo** [comment]
basically what i'm trying to do here is automatic demo recorder. i'm storing my steamid (it's called xuid/guid in hlae) in some config file and have a demo. i want to know my playerIndex before hlae even starts, so i can set "+mirv_pov myPlayerIndex" as hlae custom launch option

**Comment by dtugend** [comment]
Hi.

The playerindex should usually be avaiable too when parsing the demo with a demo parser.

I am sorry to inform you that HLAE currently can't do mirv_pov by steamid, but only player / slot index.

The reason for that is, that the player slot can switch theorertically when a player rejoins a server [doesn't happen with public matches and MM demos, but can happen under other conditions], and it's only possilbe to prepare the demo for 1 slot and not easily possilbe to make it avaialble for different slots at the same time.
So I don't think that feature will come for HLAE 3 either.

**Comment by qo** [comment]
update! i found a way to do it

so i looked at the output from mirv_listentities isPlayer=1 and noticed how every player info entry starts with "playerInfo" like it's some kind of a struct or a class. i googled "playerInfo.xuid" and found demo file dump in demo parser repo on valve github (https://github.com/ValveSoftware/csgo-demoinfo/blob/master/demoinfogo/demofiledump.cpp). i didn't know demo parser was a thing though.

i found player_info_t struct in demofiledump.h and started looking for playerIndex. there wasn't such a thing but there was an entityID (which was also called entity index in the comment above).

i figured out that player is an entity (i thought it would be logical cause we have mirv_listentities isPlayer=1 command which literally prints info about entities which happen to be a player). that way i started thinking that entityID is probably what is called playerIndex.

then i started looking for a node.js demo parser and found this repo - https://github.com/saul/demofile. i looked up some examples and that's what i have now:

```
import * as fs from "fs";
import { DemoFile, Player } from "demofile";

const filePath = process.argv[2]!;
const stream = fs.createReadStream(filePath);
const demoFile = new DemoFile();

demoFile.entities.on("create", e => {

    // We're only interested in player entities being created.
    if (!(e.entity instanceof Player)) {
        return;
    }

    console.log(`${e.entity.index}\t${e.entity.userId}\t${e.entity.name}\t${e.entity.steamId}\t${e.entity.steam64Id}\t`);
});

// Start parsing the stream now that we've added our event listeners
demoFile.parseStream(stream);

```

it prints out entity indexes along with info that mirv_listentities isPlayer=1 provides and it works as intented. so entityId is playerIndex indeed.

**Comment by qo** [comment]
> Hi.
> 
> The playerindex should usually be avaiable too when parsing the demo with a demo parser.
> 
> I am sorry to inform you that HLAE currently can't do mirv_pov by steamid, but only player / slot index.
> 
> The reason for that is, that the player slot can switch theorertically when a player rejoins a server [doesn't happen with public matches and MM demos, but can happen under other conditions], and it's only possilbe to prepare the demo for 1 slot and not easily possilbe to make it avaialble for different slots at the same time. So I don't think that feature will come for HLAE 3 either.

yep i actually witnessed entityId changing for the same player while playing faceit demos. thanks for your help!
