### ISSUE TITLE
[ReShade] CS:GO didn't launch. (AfxHook error 13)

### ISSUE THREAD

**Issue by thtr6vl1** [ripieces/advancedfx#825]
![Screenshot 2023-02-16 193343](https://user-images.githubusercontent.com/88669233/219430162-60232e91-5645-41af-a364-ab26775fae55.png)
![Screenshot 2023-02-16 193328](https://user-images.githubusercontent.com/88669233/219430166-ddb61f5b-ed0f-493f-8baa-f67d35c78672.png)

**Comment by thtr6vl1** [comment]
Today we download HLAE and we tried to launch ReShade as you can see on my screenshots. My friend and me getting this code 13 issue. Both of us getting this issue.

**Comment by thtr6vl1** [comment]
Today we download HLAE and we tried to launch ReShade as you can see on my screenshots. My friend and me getting this code 13 issue. Both of us getting this issue.

I misclicked.

**Comment by dtugend** [comment]
Hi.
Most likely Windows Defender deleted the ReShade32.dll, so it's really not there anymore.
Please add an exception for the ReShade32.dll in Windows Defender (check the reports in the notification area and allow it), then re-extract it and try again.

> Reshade detected as virus  
> Sometimes ReShade can be identified as a False Positive by some antivirus (typically those using Heuristic Analysis) or even by > other protection systems, like Windows Defender or Browsers' anti malwares. Like anti-cheats, also security softwares have to whitelist newest ReShade versions, so it's common to have this problem when a new update is release
https://reshade.me/forum/troubleshooting/5227

**Comment by thtr6vl1** [comment]
I have nothing anormal with Windows Defender. And my friend cannot run this software with ReShade too. Both of us cannot run AfxHookSource.dll

**Comment by dtugend** [comment]
Does AfxHookSource.dll work without ReShade and d3d9.dll?
If not: What's it's exact size in bytes?
Please tell me the exact "Size" (smaller number, not the "Size on Disk") in Bytes (the long one in the parenthesis).

Edit: Also which version of ReShade are you using?

**Comment by thtr6vl1** [comment]
Without ReShade and d3d9.dll, AfxHookSource is working. This is the main issue. With ReShade except d3d9.dll we getting the same error code 13 description is "DLL can't be found"

The version of the ReShade is: 5.6.0

**Comment by dtugend** [comment]
How did you get the ReShade32.dll?
It's exact size should be: 3.157.504 bytes (extracted with 7-zip: https://www.7-zip.org/)

**Comment by thtr6vl1** [comment]
![resim](https://user-images.githubusercontent.com/88669233/219445258-1c526eb9-eafe-4fa3-9aa9-03a7589d4b14.png)

I downloaded the exe version and extracted it to the "reshade" folder on my documents with winrar.

**Comment by dtugend** [comment]
I used "Download ReShade 5.6.0 with full add-on support", but the other one works fine for me to.

Did you upgrade reshade only recently?
If yes please remove Addons, Shaders, Textures folder and redo them.
Same for C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\ReShade.ini.
Also check ReShade*.log files in C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive, they might have hints.

**Comment by dtugend** [comment]
Btw which operating system are you on?

**Comment by thtr6vl1** [comment]
Windows 10

**Comment by thtr6vl1** [comment]
![resim](https://user-images.githubusercontent.com/88669233/219448458-c7549d96-0965-46e4-b1f8-dd257b90d598.png)
And i didn't upgrade ReShade.

Edit: I cant find any log file and .ini file on CS:GO directory.

**Comment by dtugend** [comment]
is it possilbe for you to join the HLAE discord, maybe we can investigate the issue together there when you have time, as said it works fine for me, but then again I am on Windows 11

**Comment by dtugend** [comment]
You could meanwhile check the Application Events log in Windows Event viewer if there's anything useful:
https://www.howtogeek.com/123646/htg-explains-what-the-windows-event-viewer-is-and-how-you-can-use-it/
Edit: fixed link

**Comment by thtr6vl1** [comment]
Thanks.

I'm joining the discord server.

**Comment by dtugend** [comment]
Additionally we don't recommend to run HLAE as admin, but if that fixes it, then it's a permission issue.

**Comment by thtr6vl1** [comment]
I tried running as admin didn't work.

**Comment by dtugend** [comment]
For one of the two persons using HLAE zip version on Windows 10 solved it, installer didn't work.
For the other person using HLAE zip version + pre 5.x reshade version solved it.

Will try to investigate if I can reproduce the problem in a Windows 10 VM.

**Comment by dtugend** [comment]
Can confirm there's a problem with ReShade 5.6 and HLAE installer version on Windows 10 (got more reports), trying to investigate.

**Comment by dtugend** [comment]
Hello.

Thanks to @xNWP and Rikki we managed to track down the issue:
https://github.com/advancedfx/ReShade_advancedfx/wiki#reshadeini-in-csgoexe-folder-important

Basically make sure that there's an ReShade.ini file next to the csgo.exe (can be empty), if in doubt use the one from the ZIP provided in the new WiKi article.
