### ISSUE TITLE
AGR feature in single-player (HL2)

### ISSUE THREAD

**Issue by SHUTDOWNOfficial** [ripieces/advancedfx#830]
Hey, I recently found out about this tool while looking for ways to import Source demos into SFM. However, I was looking to use it on single-player games like Half-Life 2 and it seems there isn't any support for those, since AFAIK the AGR feature is only supported in CS:Source, GO, and TF2. Is there some difference that may be the reason? Thanks in advance.

**Comment by dtugend** [comment]
Yes the games have differences as you can see here at alliedmodders, that have different SDK branches for different games:
https://github.com/alliedmodders/hl2sdk/branches/all

There's often also differencies between different versions of the game.

There's also different falvours of the HL2 SP, e.g. for the episodes.

Also I am not sure if the current Half-Life 2 Single Player branch in SDK 2013 already supports the ToolFramework interfaces usually used by HLAE to get easy access to the data.
I would need to download HL2 from Steam and test that to be able to answer it.

If the game engines had no differences, we'd have less features limited to specific games only (e.g. CS:GO).

**Comment by SHUTDOWNOfficial** [comment]
I see, thank you very much! 
I did try it on HL2, and other games like GMOD, but it says that the feature is not supported.
However, I'm not sure if this is due to it not supporting the ToolFramework interfaces.
I think it'd be super cool to be able to record and edit single player demos, could definitely lead to some nice content being made haha

**Comment by SHUTDOWNOfficial** [comment]
Sorry, accidentally pressed that button lol. You're free to close it if there's nothing else though

**Comment by dtugend** [comment]
I assume this is a feature request: Please don't expect anything any time soon (unless someone else contributes it), when doing HLAE I am currently focusing on other parts mostly. Sorry for the incovenience.

**Comment by dtugend** [comment]
Currently not planned. Maybe if someone else contributes it, but not sure if HL2 single player already has the IClientEngineTools_001 interface classes with the PostToolMessage function that would make that easier.
