### ISSUE TITLE
"mirv_streams end" makes csgo freeze

### ISSUE THREAD

**Issue by watdahel** [ripieces/advancedfx#831]
If I have 3+ layers in mirv_streams and use mirv_streams end csgo freezes and crash.

Layers I used:
myWorld
myMatte
myDepth
hudWhite
hudBlack

**Comment by watdahel** [comment]
I'm not sure how I fixed it but I think its because of my ffmpeg settings or layer settings.

**Comment by dtugend** [comment]
Please provide more information:

- output of  `__mirv_info` command
- Settings used to load the game in HLAE
- HLAE version used
- For how long does it freeze? Or does it crash.
- Other information that might be helpful (e.g. FFMPEG settings if used)

**Comment by watdahel** [comment]
It occasionally crashes now, for some reason using an older version of ffmpeg fixes it a bit

| AfxHookSource (Feb 24 2023 15:23:54)
| http://advancedfx.org/
|
| VClient: VClient018 (CS:GO)
| VEngineClient: VEngineClient014 (CS:GO)
| VEngineCvar: VEngineCvar007 (CS:GO)
| GameDirectory: D:\Games\Steamapps\steamapps\common\Counter-Strike Global Offensive\csgo
|



settings I used, -novid -untrusted -insecure -window -tickrate 128 +cl_cmdrate 128 +cl_updaterate 128 - high -console
I'm currently using HLAE 2.144.3
It freezes forever unless i click anything and forces to crash
I'm using ffmpeg-20190701-e51cc7e-win64-static


(ffmpeg settings I used)
"-c:v libx264 -preset 1 -crf 4  -qmax 20 -g 300 -keyint_min 1 -pix_fmt yuv444p -x264-params ref=3:me=hex:subme=3:merange=12:b-adapt=1:aq-mode=2:aq-strength=0.9:no-fast-pskip=1 {QUOTE}{AFX_STREAM_PATH}.mp4{QUOTE}"

**Comment by dtugend** [comment]
I tested with HLAE 2.144.4 (I think you mean that - at least the __mirv_info output points at that version and not 2.144.3?) and I am unable to reproduce issue.

I am using the default FFMPEG version that comes with the HLAE_Setup.exe installer ( fmpeg version n5.1.2-8-g5746987bad-20221130 ):
[ffmpeg-n5.1.2-8-g5746987bad-win64-gpl-5.1.zip](https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2022-11-30-12-36/ffmpeg-n5.1.2-8-g5746987bad-win64-gpl-5.1.zip) (from here https://github.com/BtbN/FFmpeg-Builds/releases/tag/autobuild-2022-11-30-12-36)

This is the config I used:
```
mirv_streams settings add ffmpeg myFfmepg "-c:v libx264 -preset 1 -crf 4 -qmax 20 -g 300 -keyint_min 1 -pix_fmt yuv444p -x264-params ref=3:me=hex:subme=3:merange=12:b-adapt=1:aq-mode=2:aq-strength=0.9:no-fast-pskip=1 {QUOTE}{AFX_STREAM_PATH}.mp4{QUOTE}"
mirv_streams settings edit afxDefault settings myFfmepg
exec afx/updateWorkaround
mirv_streams add hudBlack hudBlack
mirv_streams add hudWhite hudWhite
mirv_streams remove myDepthWorld
```

This is how I recorded:
```
host_framerate 30
mirv_streams record start
// ... wait a bit
mirv_streams record end
```

A short freezing is normal upon start / end, but if it's long it's not normal of course.


I used a 1280 x 720 resolution for testing.


If that FFMPEG doesn't solve your issue, please provide more information:
- how do you stop / start recording (e.g. which keys / binds used, especially if the stop bind changes host_framerate)?
- where did you get FFMPEG from?
- anything I might have missed that might be helpful for reproducing the issue
- Edit: wha'ts your `mat_queue_mode` value?

**Comment by watdahel** [comment]
I tried the same ways I normally do to record in 3 different demo's with the ffmpeg you sent It doesn't seem to freeze or crash csgo now.

There must be some sort of error in my hlae or csgo and I think I accidentally fixed the issue.

though I get this error now, probably because of the ffmpeg settings I use.

> [rawvideo @ 0000028bfca95cc0] [warning] Stream #0: not enough frames to estimate rate; consider increasing probesize

binds I used

> N = "toggle cl_draw_only_deathnotices 0 1"
> , = "host_timescale 0 ;host_framerate 300; echo POV record"
> k = "mirv_streams record start"
> L = "mirv_streams record end"

I got the ffmpeg from: [https://ia801705.us.archive.org/10/items/zeranoe/win64/static/](https://ia801705.us.archive.org/10/items/zeranoe/win64/static/)

mat_queue_mode value is 0

Thank you. I'll be closing this now


if you still want to try to recreate the crash this is the things I do in sequence when I record.

```
sv_cheats 1
host_timescale 0
cl_clock_correction 0
mirv_fix playerAnimState 1
 
cl_draw_only_deathnotices 1
 
exec afx/updateworkaround
mirv_streams add hudblack hudBlack
mirv_streams add hudwhite hudWhite
mirv_streams remove myDepthWorld

mirv_streams settings add ffmpeg CURRENT "-c:v libx264 -preset 1 -crf 4 -qmax 20 -g 300 -keyint_min 1 -pix_fmt yuv444p -x264-params ref=3:me=hex:subme=3:merange=12:b-adapt=1:aq-mode=2:aq-strength=0.9:no-fast-pskip=1 {QUOTE}{AFX_STREAM_PATH}.mp4{QUOTE}"

host_timescale 0
host_framerate 300

mirv_streams record name "D:\CSGO_FILE"
mirv_streams record start
mirv_streams record end
```
