### ISSUE TITLE
CS:GO : command to remove screen space bluring when using scopes in demos 

### ISSUE THREAD

**Issue by michaelpaulsen** [ripieces/advancedfx#833]
I've noticed that the screen blurs when scoping, the AUG scope is particularly bad. I've looked spent some time looking for a Cvar that could be changed the general consensus seems to be that the only way to do this would be to mod the game. I've even looked at all of CS:GO Cvars (https://developer.valvesoftware.com/wiki/List_of_CS:GO_Cvars). 
If this is outside of the scope of this project it would be nice to know if you have a few recommendations of mods that get rid of it.

**Comment by dtugend** [comment]
You can easily hide the scope blur by using mirv_streams actionFilter on a baseFx stream, to find it use the mirv_streams picker (mat) feature.

https://github.com/advancedfx/advancedfx/wiki/Tutorials#mirv_streams-picker-tool---hiding-materials-entities-and-more
https://www.youtube.com/watch?v=KNj4CmUoWIs (use "noDraw" instead of "mask")

**Comment by Dechno1337** [comment]
I think `vguiAction` affects it (but not sure if other elements will be affected as well):
https://github.com/advancedfx/advancedfx/wiki/Source%3Amirv_streams#stream-properties-reference-list

**Comment by dtugend** [comment]
@Dechno1337 The blur is not part of the vgui I think

**Comment by michaelpaulsen** [comment]
> You can easily hide the scope blur by using mirv_streams actionFilter on a baseFx stream, to find it use the mirv_streams picker (mat) feature.
> 
> https://github.com/advancedfx/advancedfx/wiki/Tutorials#mirv_streams-picker-tool---hiding-materials-entities-and-more https://www.youtube.com/watch?v=KNj4CmUoWIs (use "noDraw" instead of "mask")

thank you so much. 
I assume that the name of the mat is constant (please correct me if I'm wrong). That being said is there another reason that there's not a command that is alias for 
``
mirv_streams add baseFx RB;
mirv_streams edit RB actionFilter add "dev/scope_bluroverlay" noDraw
`` 
or even have the mirv_campath enable do this automatically, I don't see why you would want scope blur if you're using the camera... and if you do you could remove the noDraw filter...

**Comment by dtugend** [comment]
This material should be always the same.
For GOTV demos this is not needed, since you can switch into thirdperson there (spec_mode 6 or press space until you are in free-look), this is only needed for POV demos, which are not used often by movie makers afaik.

**Comment by dtugend** [comment]
Btw you can just make yourself an alias:
```
alias noblur "mirv_streams remove RB; mirv_streams add baseFx RB; mirv_streams edit RB actionFilter add dev/scope_bluroverlay noDraw; mirv_streams preview RB"
```
Then enter noblur into console.
