### ISSUE TITLE
Deathnotice fade-in speed

### ISSUE THREAD

**Issue by qinapz** [ripieces/advancedfx#838]
Starting with 2.145.x.x versions the speed of fade-in for deathnotice has been much slower than with old 2.144.4.0 version. While the latest (2.145.2) is much faster than the 2.145.0, it is still noticably slower than with the old version.

**Comment by dtugend** [comment]
This is not a bug, at least in latest 2.145.2 it works as intended, it's a feature:
It's supposed to match the behavior as when playing the demo in real time at normal speed.
It used to be too fast before (and too slow with 2.145.1), but now it's been corrected (it affects all HUD elements btw).

If needed and it helps you we can add a variable / command to control the behavior (alternatively finish the current movie on older HLAE version), but I assumed it would be fine for almost everyone in terms of being better than before :S

**Comment by qinapz** [comment]
Okay, now I get it. I think I'm just used to how it looked before with the fade-in being faster than intended. The variable would be very much welcome, as the slower fade in makes it look bit odd when adding slowmo on the footage where you can clearly see the person is dead already but the deathnotice is slowly fading in.

So I'd say for me it could either be edited to the previous value that was "too fast" or be controlled via accessible variable/command.

Thanks for the reply!

**Comment by dtugend** [comment]
The previous value actually depended on your recording speed (since Panorma UI without the fix just uses real time for animations).
I will try to make a mirv_cfg panormaUiTimeFix <fValueHere> command, 0 will be old behavior and anything else will be multiplied with the actual speed.
Please understand it might be not before the weekend.

**Comment by qinapz** [comment]
it's okay, the update will be very much welcome whenever it's shipped :-)
as of now I'll be using the old HLAE, as it works just fine

Thanks!

**Comment by dtugend** [comment]
https://github.com/advancedfx/advancedfx/releases/tag/v2.145.3

Enter mirv_fix panoramaTiming for more info, there's multiple options (on / off / on with factor / fixed framerate or fps).
