### ISSUE TITLE
transitions between campath are not linear PROBLEM

### ISSUE THREAD

**Issue by AtomInSpace** [ripieces/advancedfx#840]
When i make my scene and and the campath is finalized and is played the lines between the cameras are not leanear instead they are curving and its making campath go trough walls when its not intended for that to happen.
ny command i should know to fix this? or is there a fix to this at all?

**Comment by Dechno1337** [comment]
The default interpolation is not linear, and you would have to change it manually. See the FAQ:
https://github.com/advancedfx/advancedfx/wiki/FAQ#why-does-my-campath-make-sharp-turns-or-fly-through-walls

**Comment by dtugend** [comment]
If you don't plan to create the paths with HLAE anyway, then you might also want to also look into mirv_camio:
https://github.com/advancedfx/advancedfx/wiki/Source%3Amirv_camio
