### ISSUE TITLE
Ffmpeg hlae recording csgo

### ISSUE THREAD

**Issue by tylercai3** [ripieces/advancedfx#846]
https://github.com/advancedfx/advancedfx/discussions/categories/q-a
when i use ffmpeg to record csgo demo on viewmodel stream ，i only can receive a full video for original stream and a short video for viewmodel.
AFXERROR: Failed writing image for str eamAFXERROR: Failed writing image for stream viewmodel.

**Comment by Dechno1337** [comment]
What does the console say before those errors?

What are your FFmpeg settings in-game, and how do you apply them?

**Comment by tylercai3** [comment]
> What does the console say before those errors?
> 
> What are your FFmpeg settings in-game, and how do you apply them?

mirv_streams settings add ffmpeg p2     "-c:v libx264 -preset veryfast  -crf 10 -qmax 30 -g 2400 -keyint_min 2400 -rc-lookahead 1200 -pix_fmt yuv420p -x264-params ref=3:me=hex:subme=3:merange=12:b-adapt=1:aq-mode=2:aq-strength=0.9:no-fast-pskip=1 {QUOTE}{AFX_STREAM_PATH}.mp4{QUOTE}"
and i have set "mirv_hostframerate 300"
Before those errors console only said recording start...

**Comment by Dechno1337** [comment]
> 
> "mirv_hostframerate 300" Before those errors console only said recording start...

I assume you mean `host_framerate 300`? 😀 

How do you apply the p2 preset to the streams?

**Comment by tylercai3** [comment]
Yes,i mean host_....
I'm sorry that I'm not really understand"apply the p2 preset to the streams".i download a cfg
Here is my sequence:exec hlae;f11;f2;f4;f7;exec ffmpeg;host_framerate 300;↑；
Here is the cfg download link:https://api.upup.cool/get/csgo-cfg
It's00.57am in here i must go to sleep now,i will reply maybe after 9h.
thx;)

**Comment by tylercai3** [comment]
> > "mirv_hostframerate 300" Before those errors console only said recording start...
> 
> I assume you mean `host_framerate 300`? 😀
> 
> How do you apply the p2 preset to the streams?

Yes,i mean host_....
I'm sorry that I'm not really understand"apply the p2 preset to the streams".i download a cfg
Here is my sequence:exec hlae;f11;f2;f4;f7;exec ffmpeg;host_framerate 300;↑；
Here is the cfg download link:https://api.upup.cool/get/csgo-cfg
It's00.57am in here i must go to sleep now,i will reply maybe after 9h.
thx;)

**Comment by dtugend** [comment]
Please first do this:
- Check that the hard disk you are saving to is not full.
- Make sure your HLAE version is the latest public version.
- Make sure your FFMPEG for HLAE is up to date too if possible.

**Comment by tylercai3** [comment]
> > 
> > "mirv_hostframerate 300" Before those errors console only said recording start...
> 
> I assume you mean `host_framerate 300`? 😀 
> 
> How do you apply the p2 preset to the streams?
> 
> 

![IMG_20230605_130923.jpg](https://github.com/advancedfx/advancedfx/assets/134572345/220612bd-2c04-42f1-a45f-79764edb0063)

this is the errors before it

**Comment by tylercai3** [comment]
> Please first do this:
> - Check that the hard disk you are saving to is not full.
> - Make sure your HLAE version is the latest public version.
> - Make sure your FFMPEG for HLAE is up to date too if possible.

the version of hlae is 2.145.6.0
ffmpeg ：2023-5-31-git-baa9f8d-full_build-www.gyan.dev
My hard disk is enough.

**Comment by tylercai3** [comment]
if i only record stream raw ，it works.![IMG_20230605_140821.jpg](https://github.com/advancedfx/advancedfx/assets/134572345/7161e5db-fe73-4437-9435-096c2d99e573)

When I start recording, it starts recording normally, but it freezes right away, and after that, layered recording doesn't work![IMG_20230605_141224.jpg](https://github.com/advancedfx/advancedfx/assets/134572345/66a512e9-5cf1-4a2f-a26c-6897e659c52e)
Only the stream RAW  ends up with a normal-sized video, and the other stream stop when they freeze.

**Comment by dtugend** [comment]
You said you are using the FFMPEG build from gyan.dev - we never use that one to be honest.
Can you test with the one that HLAE_Setup.exe would use, please:
https://github.com/BtbN/FFmpeg-Builds/releases/tag/autobuild-2023-04-30-12-46
You can use one of these two:
[ffmpeg-n6.0-18-g27205c0b47-win64-gpl-6.0.zip ](https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2023-04-30-12-46/ffmpeg-n6.0-18-g27205c0b47-win64-gpl-6.0.zip) - That's the one I use most of the time.
[ffmpeg-n6.0-18-g27205c0b47-win64-gpl-shared-6.0.zip](https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2023-04-30-12-46/ffmpeg-n6.0-18-g27205c0b47-win64-gpl-shared-6.0.zip)

**Comment by tylercai3** [comment]
> You said you are using the FFMPEG build from gyan.dev - we never use that one to be honest.
> Can you test with the one that HLAE_Setup.exe would use, please:
> https://github.com/BtbN/FFmpeg-Builds/releases/tag/autobuild-2023-04-30-12-46
> You can use one of these two:
> [ffmpeg-n6.0-18-g27205c0b47-win64-gpl-6.0.zip ](https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2023-04-30-12-46/ffmpeg-n6.0-18-g27205c0b47-win64-gpl-6.0.zip) - That's the one I use most of the time.
> [ffmpeg-n6.0-18-g27205c0b47-win64-gpl-shared-6.0.zip](https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2023-04-30-12-46/ffmpeg-n6.0-18-g27205c0b47-win64-gpl-shared-6.0.zip)

![IMG_20230605_145112.jpg](https://github.com/advancedfx/advancedfx/assets/134572345/c25071ee-3ff3-4fa4-b9e9-a9d72b5dbbb9)

it still doesn't work.😞
Is it a problem with my system?I'm win11.

**Comment by dtugend** [comment]
I am currently on Windows 10, but was on Windows 11 a (few) month(s) ago and had no such problem.

1. Can you try to change the order of the streams with `mirv_streams move`, to see if hat has any effect or if the same streams fail regardless of order?
2. Can you do `mirv_streams print2` - this should show the actual settings used on the streams.
3. After 2 please do `mirv_streams settings edit <settingNameHere> options` to show the current options set for the setting(s) used replace `<settingNameHere>` with the name of the setting given from `mirv_streams print2`.

At one point the Purple.cfg had hardware accelerated settings in it, and those can fail, you can only have like 2 streams hardware accelerated on many PC systems, due to GPU / driver limitations. And I already noticed you don't use the latest purple.cfg probably, because e.g. p2pro setting is not in newer ones.

**Comment by tylercai3** [comment]
> I am currently on Windows 10, but was on Windows 11 a (few) month(s) ago and had no such problem.
> 
> 1. Can you try to change the order of the streams with `mirv_streams move`, to see if hat has any effect or if the same streams fail regardless of order?
> 2. Can you do `mirv_streams print2` - this should show the actual settings used on the streams.
> 3. After 2 please do `mirv_streams settings edit <settingNameHere> options` to show the current options set for the setting(s) used replace `<settingNameHere>` with the name of the setting given from `mirv_streams print2`.
> 
> At one point the Purple.cfg had hardware accelerated settings in it, and those can fail, you can only have like 2 streams hardware accelerated on many PC systems, due to GPU / driver limitations. And I already noticed you don't use the latest purple.cfg probably, because e.g. p2pro setting is not in newer ones.

Thank u very much!Thank you so much, I can now show the full video. The problem should be with purple's cfg, which I solved immediately after updating the cfg file. Finally, thank you.
