### ISSUE TITLE
MP4 corrupted if csgo is quit before recording stopped

### ISSUE THREAD

**Issue by MaverickMSG** [ripieces/advancedfx#847]
When recording from a demo with ffmpeg outputting to an mp4, sometimes the mp4 will become corrupt if csgo is closed out without calling `mirv_streams record end`:

ffmpeg version git-2022-10-25-9bed814-ffmpeg-windows-build-helpers Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 10.2.0 (GCC)
<snip>
  libavutil      57. 39.101 / 57. 39.101
  libavcodec     59. 51.100 / 59. 51.100
  libavformat    59. 34.101 / 59. 34.101
  libavdevice    59.  8.101 / 59.  8.101
  libavfilter     8. 49.101 /  8. 49.101
  libswscale      6.  8.112 /  6.  8.112
  libswresample   4.  9.100 /  4.  9.100
  libpostproc    56.  7.100 / 56.  7.100
[s16le @ 000000e2352e0980] Estimating duration from bitrate, this may be inaccurate
Guessed Channel Layout for Input Stream #0.0 : stereo
Input #0, s16le, from 'csgo\\videos\\take0000\\audio.wav':
  Duration: 01:08:34.89, bitrate: 1411 kb/s
  Stream #0:0: Audio: pcm_s16le, 44100 Hz, 2 channels, s16, 1411 kb/s
[mov,mp4,m4a,3gp,3g2,mj2 @ 000000e2352ed100] moov atom not found
x:\47437.mp4: Invalid data found when processing input

I utilize demo_quitafterplayback 1 to quit csgo automatically when demo playback is finished, so that may be part of the issue here.

**Comment by Dechno1337** [comment]
Wouldn't it be as simple as putting `"mirv_streams record end; demo_quitafterplayback 1"` assuming multiple commands can be executed like that in this situation?

**Comment by MaverickMSG** [comment]
Hm, in theory that might work; is there a way to trigger a `mirv_streams record end` when the demo finishes?  I could probably skip using demo_quitafterplayback if needed, just as long as the mp4 was written completely (and ffmpeg closed out?)

**Comment by Dechno1337** [comment]
Never mind, I misunderstood how that command behaves. 😐 

If you know how long the demo lasts you could try to schedule `mirv_streams record end` before it ends.

**Comment by MaverickMSG** [comment]
Yeah, that's part of the problem; I don't have a good way to know that.

**Comment by dtugend** [comment]
[AfxHookSource.zip](https://github.com/advancedfx/advancedfx/files/11693167/AfxHookSource.zip)

**Comment by MaverickMSG** [comment]
I can confirm this fixes the issue.  thank you @dtugend
