### ISSUE TITLE
Change player crosshair on csgo mm demo

### ISSUE THREAD

**Issue by rpr1mera** [ripieces/advancedfx#849]
Is this possible?

**Comment by Dechno1337** [comment]
HLTV demo = CS 1.6?

The game will use your crosshair settings when watching demos, no?

**Comment by rpr1mera** [comment]
My bad, I meant csgo match demo

**Comment by rpr1mera** [comment]
> HLTV demo = CS 1.6?
> 
> The game will use your crosshair settings when watching demos, no?


My bad, I meant csgo matchmaking demo

**Comment by Dechno1337** [comment]
> 
> My bad, I meant csgo matchmaking demo

Same concept though, your own crosshair settings affect the demo? Or does the demo have a crosshair bug?

**Comment by rpr1mera** [comment]
> > My bad, I meant csgo matchmaking demo
> 
> Same concept though, your own crosshair settings affect the demo? Or does the demo have a crosshair bug?

The thing is I use a big vertical/horizontal line crosshair when I use nades (to help my lineups), and regular small crosshair with weapons. Sometimes when I download my demos and watch myself I appear with the big crosshair, and I can't change it. I've tried console commands during the playing of the demo to no avail. It's like my replay it's stuck on that specific crosshair.
![fail-xhair-example](https://github.com/advancedfx/advancedfx/assets/38471001/491a5329-ae64-47cb-8f4a-0aa63d4483ac)

**Comment by Dechno1337** [comment]
I assume your nade and weapon binds have various `cl_crosshair[...]` settings/values then(?)

**Comment by rpr1mera** [comment]
> I assume your nade and weapon binds have various `cl_crosshair[...]` settings/values then(?)

Yes, so while in game my crosshair will depend on whether I pressed any of my grenade binds, my secondary or primary weapon binds.

What really goes on is I have three files xhair-primary.cfg, xhair-secondary.cfg and xhair-nades.cfg. On each corresponding bind I simply add a ";exec xhair....cfg" at the end of the bind.

**Comment by Dechno1337** [comment]
I think `mirv_block_commands` should work (in theory) 🤔 
https://github.com/advancedfx/advancedfx/wiki/Source%3Amirv_block_commands

Maybe something like this:
`mirv_block_commands add 5 "cl_crosshair\*"` or block the `exec` command if HLAE cannot detect the commands from the configs.

**Comment by rpr1mera** [comment]
I get the idea, I'll try and report back

**Comment by rpr1mera** [comment]
Tried blocking both but it didn't work

**Comment by Dechno1337** [comment]
Can you send the demo so I can check too? (or try dtugend's suggestion first) 👇

**Comment by dtugend** [comment]
You probably want to enter `cl_show_observer_crosshair 0` into console after loading the demo.
```
cl_show_observer_crosshair               : 0        : , "a", "cl"      : Show the crosshair of the player being observed. 0: off 1: friends and party 2: everyone 
```

**Comment by rpr1mera** [comment]
`cl_show_observer_crosshair 0` worked, thank you guys
