### ISSUE TITLE
[CS 1.6] how to remove grenade_trajectory ?

### ISSUE THREAD

**Issue by eGabox** [ripieces/advancedfx#855]
Hello, I have a question, I would like the trajectory of the grenade not to be seen when I record with mirv_recordmovie_start, is it possible to eliminate that from HLAE?, so that the scene can be seen more cleanly.

Here I leave a capture.
https://prnt.sc/jL6GGc39ekay

**Comment by dtugend** [comment]
Not 100% sure but I am afraid without modifications to the demo file or some hooks to the game it's not possible to hide only those, those are recorded as svc_tempentity of type TE_BEAM... into the demo and there seem to be no console commands or variables that would hide those beams.

**Comment by eGabox** [comment]
Hi, if that's the case, how could I edit the demo, what tools would I need to get rid of that?

**Comment by dtugend** [comment]
I asked in the HLAE Discord if someone else knows an existing tool that can do that, but no one had an idea for an existing tool sadly.
