### ISSUE TITLE
Error 13 AfxHook

### ISSUE THREAD

**Issue by deshrVFX** [ripieces/advancedfx#856]
Hey, cant seem to find out whats wrong, any help appreciated. Sorry for it being german.

![Screenshot_1](https://github.com/advancedfx/advancedfx/assets/138363247/a9c3654b-6eb5-4103-a4a6-24ff2cb33bb2)
![Screenshot_4](https://github.com/advancedfx/advancedfx/assets/138363247/bad61131-6a1a-440a-a305-7e279c446e90)

**Comment by deshrVFX** [comment]
Okay, i've got it now, had the help of the reshade discord, thanks anyway!

**Comment by Dechno1337** [comment]
What was the solution?

**Comment by deshrVFX** [comment]
> What was the solution? Did you need to move the ReShade32.dll to another file path?

https://github.com/advancedfx/ReShade_advancedfx/wiki#reshadeini-in-csgoexe-folder-important

had the help of this guide
