### ISSUE TITLE
hlae sometimes freezes when recording with mirv_streams

### ISSUE THREAD

**Issue by LuCree** [ripieces/advancedfx#859]
When I try to record with mirv_streams twice (recording two clips in the same game), and sometimes only once, my csgo freezes and stops responding. It happens on any demo, and on any round.

**Comment by dtugend** [comment]
Hi @LuCree - Many thanks for providing debug dump earlier. I think I with it identified a bug in HLAE and tried to address it. If you have time, replace the AfxHookSource.dll in your HLAE install with the one bellow and test if it's fixed / worse / the same, please:

[AfxHookSource.zip](https://github.com/advancedfx/advancedfx/files/12136018/AfxHookSource.zip)

You can see that the new DLL is loaded by looking at the date output from __mirv_info, should be Jul 22 2023:
```
] __mirv_info
|
| AfxHookSource (Jul 22 2023 10:28:00)
[....]
```

**Comment by dtugend** [comment]
Here is the candidate for the next release:
[AfxHookSource.zip](https://github.com/advancedfx/advancedfx/files/12136272/AfxHookSource.zip)
