### ISSUE TITLE
(TF2) Replaying / Exiting demo after using campaths crash 

### ISSUE THREAD

**Issue by 01230123abc** [ripieces/advancedfx#861]
Replaying or Exiting demo after using campaths results in TF2 crashing and giving an Engine error.

![image](https://github.com/advancedfx/advancedfx/assets/109891980/87799f82-6ba5-4c8b-8842-1fab3885d934)

**Comment by 01230123abc** [comment]
using mat_queue_mode 0 and clearing and disabling campaths before leaving, fixes it sometimes

**Comment by dtugend** [comment]
Thank you for reporting the issue and for reporting a potential workaround.
I want to solve the issue more generally for most Source 1 mods, but not sure yet if I'll manage.

**Comment by dtugend** [comment]
This was released in HLAE 2.148.3.2, if you have time and motivation verify that it works now let me know the result please =)
Thanks for reporting the issue.
