### ISSUE TITLE
mirv_cmd for CS2

### ISSUE THREAD

**Issue by Run1e** [ripieces/advancedfx#863]
For automating the game, mirv_cmd as it worked in CS:GO afx is more or less a must-have.

Would this be hard to implement for the CS2 dll?

**Comment by dtugend** [comment]
It's scheduled soonish, but since that might be not soon enough for you, here's the missing thing (ExecuteClientCmd):
https://github.com/advancedfx/advancedfx-prop/blob/prop/cs2/sdk_src/public/cdll_int.h#L94
Example: https://github.com/advancedfx/advancedfx/blob/main/AfxHookSource2/main.cpp#L775

**Comment by dtugend** [comment]
https://github.com/advancedfx/advancedfx/releases/tag/v2.148.4
