### ISSUE TITLE
CS2: mirv_snd_filter

### ISSUE THREAD

**Issue by ChetdeJong** [ripieces/advancedfx#866]
mirv_snd_filter 
to block sounds e.g. radio

**Comment by dtugend** [comment]
Please split the different tasks into separate issues.

Please explain how #865 (CS2: add spectator smooth) is useful for movie making, this is for live spectating (?) - maybe you confused it with #864 (open) - or with the mirv_campath task (which is already implemented)?

**Comment by ChetdeJong** [comment]
yeah, I thought #865 was fix for twitching animations (smoother demos), my bad. Will split it now

**Comment by ChetdeJong** [comment]
so I lately discovered that in CS2 it's actually possible to just remove certain sound events to get rid of unwanted sounds. You can list of all events with `snd_list_soundevents`. Therefore I think `mirv_snd_filter` is unnecessary, unless they remove it from game. If you think so, you can close this issue.

Example:

```
//remove end round radio
snd_remove_soundevent Announcer.CTWin.CS2_Classic
snd_remove_soundevent Announcer.TWin.CS2_Classic
snd_remove_soundevent Event.CTWin
snd_remove_soundevent Event.TERWin

//remove bomb planted/defused radio
snd_remove_soundevent Event.BombDefused
snd_remove_soundevent Event.BombDefused_Legacy1
snd_remove_soundevent Event.BombDefused_Legacy2
snd_remove_soundevent Event.BombDefused_Legacy3
snd_remove_soundevent Event.BombPlanted
snd_remove_soundevent Announcer.BombDefused.CS2_Classic
snd_remove_soundevent Announcer.BombPlanted.CS2_Classic
```

**Comment by dtugend** [comment]
Thank you.

**Comment by Dechno1337** [comment]
P.S. `mirv_cvar_unhide_all` is needed to access some of those `snd_...` commands.

**Comment by ChetdeJong** [comment]
> P.S. `mirv_cvar_unhide_all` is needed to access some of those `snd_...` commands.

I forgot to update here, but seems like they removed that snd command.
Currently its only possible to mute these events by modifying some files in vpk. 
I mean you have to decompile needed files, make changes, compile back and load them before all main vpk files.
The one with soundevents located in `pak01_dir.vpk > soundevents > vo > announcer > game_sounds_cs2_classic.vsndevts`

**Comment by dtugend** [comment]
mirv_cvar_unhide_all  works in in-game console, just not in vconsole.

**Comment by ChetdeJong** [comment]
Yeah actually.
Can be used with cfg then after `mirv_cvar_unhide_all`
