### ISSUE TITLE
CS2: mirv_pgl support

### ISSUE THREAD

**Issue by osztenkurden** [ripieces/advancedfx#867]
Just like in CS:GO <3

**Comment by Loxaris** [comment]
Epic stuff

**Comment by FlowingSPDG** [comment]
I was wondering why it's called mirv_pgl for long time, maybe it can be good timing to rename something else like ``mirv_server``?
(I assumed that PGL asked dom to make it?)

**Comment by ChetdeJong** [comment]
Should this be closed now? @dtugend 
In latest release similar functionality was added
https://github.com/advancedfx/advancedfx/releases/tag/v2.162.0

**Comment by dtugend** [comment]
I need to add entity info functions first that I prepared, otherwise it's missing a notable feature.

> Should this be closed now? @dtugend In latest release similar functionality was added https://github.com/advancedfx/advancedfx/releases/tag/v2.162.0

**Comment by dtugend** [comment]
Actually chet is right, we can already close this as done, since the missing features are tracked separately in #873 and #874
