### ISSUE TITLE
CS2: mirv_deathmsg

### ISSUE THREAD

**Issue by ChetdeJong** [ripieces/advancedfx#868]
mirv_deathmsg
basically only filter and extend time needed for most of people

**Comment by Loxaris** [comment]
Yes please! mirv_deathmsg shownumbers 2 is pretty handy command for observers doing replays 🎬

**Comment by dtugend** [comment]
> Yes please! mirv_deathmsg shownumbers 2 is pretty handy command for observers doing replays 🎬

You are probably already aware, but I forgot to mention it here, they already added a command for that a while ago:

`"cl_deathnotices_show_numbers","0",, , cl, , , , , , , , , , , , release, , , , , , , , , ,,"0: default; 1: draw names as just numbers; 2: append number on killer and victim to the name"`
