### ISSUE TITLE
CS2: mirv_spec

### ISSUE THREAD

**Issue by ChetdeJong** [ripieces/advancedfx#870]
At this moment in CS2 there are no ~`spec_mode`~ , ~~`spec_player_by_accountid`~~ as they were in CSGO. So basically no way afaik to control spectator with console. Might be useful to also have `mirv_spec` to get that functionality for automated recording, etc.

Not sure if it's complicated to add now or maybe worth to wait for full CS2 release since things might change to evade unnecessary work.

**Comment by 1mpulse** [comment]
I support, I really need this feature

**Comment by Dechno1337** [comment]
`spec_mode` is now available in CS2. (Not sure when it was added exactly.) 😅

**Comment by ChetdeJong** [comment]
> `spec_mode` is now available in CS2. (Not sure when it was added exactly.) 😅

can confirm. So only spec_player is needed then, unless Valve add it back

**Comment by Dechno1337** [comment]
> So only spec_player is needed then, unless Valve add it back

Is this relevant from the latest CS2 update?

_`Added convar cl_deathnotices_show_numbers for observers to have quick access to player's spectate index`_

Sounds like it's not quite what you are after though I guess(?)

**Comment by ChetdeJong** [comment]
there is workaround for what I need, but having option to select player by steamid (like it was in csgo natively) is more reliable. 

That said I think this feature should be low priority for now since there is a chance Valve may add it back. Others I think more important

**Comment by Dechno1337** [comment]
A recent update added more commands for observers it seems:

`spec_goto`
`spec_lock_to_accountid`
`spec_lock_to_current_player`
`spec_player`

Possibly more. So it looks like we can close this thread? 🥳
