### ISSUE TITLE
TF2: add an option to record reshade with mirv_streams

### ISSUE THREAD

**Issue by 01230123abc** [ripieces/advancedfx#871]
Since depth maps in TF2 are broken (iirc) and the only way to record them is with reshade. I believe it would be a good idea to add an option to record reshade with streams (like csgo did).

EDIT: Of course, it's not only for depth layer, but also for other effects! :p

**Comment by dtugend** [comment]
Hi. For the depth maps you can probably use the great tool Sparkly FX now:
https://github.com/cademtz/sparkly-fx
