### ISSUE TITLE
CS2: afx_interop

### ISSUE THREAD

**Issue by MichaelCampagna** [ripieces/advancedfx#872]
**afx_interop**
Achieve the similar functionality as the [afx-unity-interop](https://github.com/advancedfx/afx-unity-interop) project. Either Unity support for the newer URP would be preferred as it has replaced LWRP and would most likely have better performance than built-in render pipeline or HDRP, or preferably Unreal Engine support.

Dependencies:
mirv_calcs - positional data for camera/game entities: https://github.com/advancedfx/advancedfx/issues/873
mirv_listentities - retrieval of entity handles: https://github.com/advancedfx/advancedfx/issues/874

**Comment by dtugend** [comment]
Hi. In light of issue #896 I decided to close this issue for now, since afx_interop was a sort of complicated premium feature and benefits only a small share of HLAE users, which are mostly not so small companies.
