### ISSUE TITLE
mirv_campath formatting bug with angles (yaw, roll)?

### ISSUE THREAD

**Issue by Dechno1337** [ripieces/advancedfx#877]
This is what the in-game help in the console shows:

`mirv_input angles <yPitch> <xRoll> <zYaw>`
`mirv_campath edit angles current|(<dPitchY>|* <dYawZ>|* <dRollX>|*)`

Is `dYawZ` supposed to be the third option (exchange places with `dRollX`? It also behaves strangely when using negative values. See screenshots below for more context.

`mirv_campath edit angles`:

![CampathBug](https://github.com/advancedfx/advancedfx/assets/40070135/4daccc07-cc81-4139-ad84-54b6f389ea2d)

`mirv_input angles`:

![Campath2](https://github.com/advancedfx/advancedfx/assets/40070135/f79ca835-2d99-48b3-80b7-2449ef63d282)

Not sure what's going on, or if I am misunderstanding something. 😅

**Comment by dtugend** [comment]
There's multiple ways to get the same rotation in Euler angels.
HLAE campaths work with quaternions internally, which can result in different values that should however result in the same rotation.

Maybe there's additionally a bug here, not sure.

You can check if that's the case here by entering both variants into the mirv_campath edit angles and the result should look the same.

**Comment by Dechno1337** [comment]
How would I test it?

**Comment by dtugend** [comment]
> How would I test it?

You enter both variants into mirv_input and if you end up in same view it's ok. 
I did a quick check in the code now, didn't find an obvious mistake.

**Comment by Dechno1337** [comment]
Copying X Y Z and pitch yaw roll from `mirv_campath print` into `mirv_input positions/angles` work as intended.

Not sure if there is something else going on with `mirv_campath edit angles` but now I cannot replicate it. I will keep an eye out for it in the future, and re-open this issue if I can replicate it.
