### ISSUE TITLE
Afxhook error code 13

### ISSUE THREAD

**Issue by Mai90212** [ripieces/advancedfx#878]
I use hlae to check demo in CS2 and i use the newly updated hlae pack and i use the custom load to open CS2. But I don't know why hlae can't open and it said DLL can't be loaded and i reinstall it and check updated for many times but still it can't open.

**Comment by Dechno1337** [comment]
What does your custom loader look like?

**Comment by Mai90212** [comment]
> What does your custom loader look like?

![屏幕截图 2023-10-08 193210](https://github.com/advancedfx/advancedfx/assets/147313543/c1cee0a0-9693-498d-9f0d-35a34ca6b00c)

**Comment by Dechno1337** [comment]
>image

That is the wrong .dll for CS2.

https://github.com/advancedfx/advancedfx/wiki/AfxHookSource2#launching-counter-strike-2

(And remove `-game csgo`)

**Comment by Mai90212** [comment]
thanks, problem solved but is there any way that I can use hlae to record a clean pov view in demo like in csgo?

**Comment by dtugend** [comment]
> thanks, problem solved but is there any way that I can use hlae to record a clean pov view in demo like in csgo?

This has been requested, but is currently not possible and might remain not possible for quite some time ( https://github.com/advancedfx/advancedfx/issues/875 )

**Comment by Mai90212** [comment]
fine, thanks for helping
