### ISSUE TITLE
CS2: Recording support

### ISSUE THREAD

**Issue by Purple-CSGO** [ripieces/advancedfx#883]
As the csgo era `mirv_streams` command

**Comment by bentsignal** [comment]
🙏

**Comment by LOCKE-BYTEs** [comment]
#bringmirvstreamsback

**Comment by Purple-CSGO** [comment]
Add `baseFx` back and enable ffmpeg recording, while considering more complex streams later?

CS2 really has low fps and keeps cutting. It's not easy to fluently record with OBS ...
