### ISSUE TITLE
CommandLine Error - 2.151.1.0

### ISSUE THREAD

**Issue by JJoTech** [ripieces/advancedfx#884]
CommandLine isn't working as intended. 

**Steps**
1. Opened HLAE > Tools >Developer > Custom Loader
2. Added `-insecure` and `-allow_third_party` to the CommandLine.
3. Launched CS2 via Custom Loader.
4. Started Open Broadcast Software (OBS), added the game executable to the sources list via Game Capture and Window Capture and the game immediately closes. This is not expected behaviour. 
5. Expected behaviour: Game will allow 3rd party software to hook onto the running process and capture the display output. 
6. Launching CS2 directly via steam with the same Launch Options, it doesn't force quit when it is added to OBS.

**Conclusion**: HLAE is not correctly executing the CommandLine upon game startup. 

Display capture works and will not make the game force close as there is no direct process hook.

**Comment by dtugend** [comment]
Hi. Thanks for reporting the issue. Please upgrade to 2.151.2. Sorry that I couldn't fix it earlier, was busy.

Edit: The issue was OBS and HLAE fighting about hooking D3D11 in a way that broke it.
