### ISSUE TITLE
Half-Life 25th Anniversary Update Broke AfxHookGoldSrc

### ISSUE THREAD

**Issue by Dechno1337** [ripieces/advancedfx#885]
Edit: Checklist for testing the unreleased fixes linked below. ([AfxHookGoldSrc command list for reference](https://github.com/advancedfx/advancedfx/wiki/GoldSrc%3ACommands))

- [x] `__mirv_aim_[...]` ❔ _High accel/deaccel values sometimes cause the view to spasm, too random to replicate tho_
- [x] `__mirv_cstrike_ch_fps`
- [x] `__mirv_demozoom`
- [x] `__mirv_depth_[...]`
- [x] `__mirv_fixforcehltv`
- [ ] `__mirv_force_players_solid`
- [x] `__mirv_force_thirdperson`
- [x] `__mirv_info`
- [x] `__mirv_moveto`
- [x] `__mirv_print_pos`
- [x] `__mirv_sample_[...]`
- [x] `+mirv_aim` 📝 _Losing window focus will cause the key to be released automatically (due to a Half-Life "side effect")_
- [x] `+mirv_recordmovie` 📝 _See above (relevant when using 'optimize window visibility on capture')_
- [x] `+mirv_zoom` 📝 _See above_
- [x] `mirv_agr` ❔ _Exporting works, but not sure how accurate the data is_
- [x] `mirv_aim_[...]`
- [x] `mirv_cameraofs_cs`
- [x] `mirv_campath`
- [x] `mirv_crop_[...]`
- [x] `mirv_cstrike_deathmsg` / `mirv_deathmsg`
- [x] `mirv_cstrike_force_knife_righthand` 📝 _Only works in HLTV demos & when the hltv animation fix is enabled_
- [x] `mirv_cstrike_hltv_animation_fix`
- [x] `mirv_cstrike_smoke`
- [x] `mirv_cstrike_spectator_fix`
- [x] `mirv_decalfilter`
- [x] `mirv_depth_streams`
- [x] `mirv_depth_exr` ❔ _Exporting works but can't confirm the data_
- [ ] `mirv_disable_specmenu` ❔ _Cannot test in CS 1.6_
- [ ] `mirv_disableautodirector` ❔ _Obsolete for CS 1.6? Cannot test other games_
- [ ] `mirv_draw_sv_[...]`
- [x] `mirv_entity_[...]`
- [x] `mirv_fov`
- [x] `mirv_fx_lightmap`
- [x] `mirv_fx_noblend`
- [x] `mirv_fx_skyhd`
- [x] `mirv_fx_viewmodel_lightmap`
- [x] `mirv_fx_wh_[...]`
- [x] `mirv_fx_xtendvis`
- [x] `mirv_gameoverlay`
- [x] `mirv_input`
- [x] `mirv_listplayers`
- [x] `mirv_matte_[...]` 📝 _Didn't test all sub-commands_
- [x] `mirv_movie_bmp`
- [x] `mirv_movie_clearscreen`
- [x] `mirv_movie_depthdump`
- [x] `mirv_movie_export_sound`
- [x] `mirv_movie_ffmpeg`
- [x] `mirv_movie_filename`
- [x] `mirv_movie_fps`
- [x] `mirv_movie_hidepanels`
- [x] `mirv_movie_playdemostop`
- [x] `mirv_movie_separate_hud`
- [x] `mirv_movie_simulate_[...]`
- [ ] `mirv_movie_sound_[...]`
- [x] `mirv_movie_splitstreams`
- [x] `mirv_movie_stereo[...]`
- [x] `mirv_movie_wireframe[...]`
- [ ] `mirv_noadverts` ❔ _Cannot find a demo with ads_
- [x] `mirv_recordmovie_start/stop`
- [x] `mirv_roll`
- [x] `mirv_sample_[...]`
- [x] `mirv_showentities`
- [ ] `mirv_tas_mode`
- [x] `mirv_voice_block`
- [x] `mirv_whereami`
- [x] `mirv_zoom_[...]`

----

Original post:

![bild](https://github.com/advancedfx/advancedfx/assets/40070135/97a61710-9164-4207-83b0-f6e607b72c44)

Plus a dozen other similar messages. And a few about hw.dll 🤔 

![bild](https://github.com/advancedfx/advancedfx/assets/40070135/698c405f-187b-4c0f-bf00-916a55882dd7)

**Comment by dtugend** [comment]
There's more than 1 page of issues with that update in the Valve GitHub repository, including CS 1.6 not working e.g.: https://github.com/ValveSoftware/halflife/issues

Thus I am not sure yet when I will be working on supporting the 25th Anniversary Release, but until then people can use the "steam_legacy" branch on the betas tab:
![Half-Life betas tab steam_legacy](https://github.com/advancedfx/advancedfx/assets/3610128/5ce0bfb3-f2ea-4fc2-974f-d6e86da1dab9)

**Comment by dtugend** [comment]
Here is a current build of the git branch for testing: [(outdated)](https://github.com/advancedfx/advancedfx/files/14071684/AfxHookGoldSrc.zip)

( https://github.com/advancedfx/advancedfx/tree/hl-25th-anniverary-885 )

**Comment by dtugend** [comment]
@Dechno1337 thank you very much for testing. Here is an updated DLL:

[(outdated)](https://github.com/advancedfx/advancedfx/files/14103639/AfxHookGoldSrc.zip)

(I think we'll skip re-testing of things that already worked earlier.)

**Comment by dtugend** [comment]
[(outdated) // solved dem_forcehltv crash](https://github.com/advancedfx/advancedfx/files/14103976/AfxHookGoldSrc.zip)

**Comment by dtugend** [comment]
[(outdated) // solved mirv_input camera w/ m_rawinput 0](https://github.com/advancedfx/advancedfx/files/14129832/AfxHookGoldSrc.zip)

**Comment by dtugend** [comment]
[AfxHookGoldSrc.zip // solves mirv_voice_block crash(?)](https://github.com/advancedfx/advancedfx/files/14130019/AfxHookGoldSrc.zip)
