### ISSUE TITLE
mirv_input mouse3 mis-configured

### ISSUE THREAD

**Issue by Purple-CSGO** [ripieces/advancedfx#886]
- In Camera Input Mode
- `mouse3` is hard-coded to but does not have actual functionality
- and stops ingame mouse3 bindings like `bind mouse3 demo_togglepause`

**Comment by dtugend** [comment]
[AfxHookSource2.zip](https://github.com/advancedfx/advancedfx/files/13673100/AfxHookSource2.zip)
