### ISSUE TITLE
Flickering with mirv_campath draw in CS2 at high FPS

### ISSUE THREAD

**Issue by Dechno1337** [ripieces/advancedfx#890]
Both flickering and screen-tearing (but the tearing might be unrelated, or the flickering makes it look like tearing).
Seems to be tied to the FPS.

Workaround: `fps_max` to limit the FPS to something like <200 FPS.

**Comment by dtugend** [comment]
[AfxHookSource2.zip](https://github.com/advancedfx/advancedfx/files/13602787/AfxHookSource2.zip)

**Comment by Dechno1337** [comment]
> [AfxHookSource2.zip](https://github.com/advancedfx/advancedfx/files/13602787/AfxHookSource2.zip)

Still flickering 😭

**Comment by dtugend** [comment]
[AfxHookSource2.zip](https://github.com/advancedfx/advancedfx/files/13603522/AfxHookSource2.zip)
