### ISSUE TITLE
CSGO: auto low-quality skin texture fix

### ISSUE THREAD

**Issue by eirisocherry** [ripieces/advancedfx#894]
Fixing low-quality skin texture in CSGO demos: https://youtu.be/gmCx-XwVcOE
Demo: https://drive.google.com/file/d/1VW9cyNhkN1-uWALPXcBWA3VokveLpU3b/view?usp=sharing

If there is a way to keep all the skins in demos always high-quality without entering pov mode everytime, that would be a great feature.

Some additional information, that might help:
I have the latest HLAE version.
This fix works without HLAE anyways.
It works in any demos. Pro matches/mm/faceit with real skins or community servers/local servers with !ws plugin. It doesn't matter.

**Comment by dtugend** [comment]
Hi. Thank you for your feature suggestion. I am currently not planning to make feature additions to the CS:GO branch (especially potentially complicated ones), especially considering it's scheduled to be replaced by CS2.

**Comment by eirisocherry** [comment]
okay
