### ISSUE TITLE
CS2: campath autosave

### ISSUE THREAD

**Issue by eirisocherry** [ripieces/advancedfx#895]
Sometimes your game crashes at the most unexpected moment or you accidentally delete a campath (this can easily happen if you bounded `mirv_campath clear` or added it to your cfg)

So I think it would be nice to have a feature like this one:
`mirv_campath autosave [1/0]` - if enabled will execute `mirv_campath save campath_autosave` every 5-10 seconds.
If there is no campath it will not save anything.

if it's easy to implement, i'd like to see it in csgo too

**Comment by Dechno1337** [comment]
I think that's on the to-do list already (but related to the GUI?): https://github.com/advancedfx/advancedfx/issues/52#issuecomment-1097237082

**Comment by eirisocherry** [comment]
yeah I see, it says "for autosaving campaths on demo close", but I want a command that will work like this:

if `mirv_campath autosave 1` then every 5-10 seconds
{
campath exist?
yes: execute `mirv_campath save campath_autosave`
no: do nothing
}

**Comment by Devostated** [comment]
You could just use `mirv_campath add; mirv_campath save name.xml;` or when ever you enable, edit, play the demo, what ever, then you do a back up after each time you do something. 
every 5-10 seconds isnt a great idea, it really only should be if something is changed.

**Comment by eirisocherry** [comment]
great idea, thank you
