### ISSUE TITLE
L4D2 / HL2MP: mirv_streams record screen not working

### ISSUE THREAD

**Issue by MaverickMSG** [ripieces/advancedfx#897]
In left 4 dead 2, when recording with hlae and attempting to output to ffmpeg, hlae reports that:
`Starting recording ... AfxError: WrpConVarRef::WrpConVarRef(host_framerate): Could not get ConVar.
done.`
...however host_framerate is already set on both the command line and in configs prior to starting the recording:

host_framerate 60
mirv_streams record fps 60
mirv_streams record screen enabled 1
mirv_streams record screen settings afxFfmpegYuv420p
mirv_streams record start

This same config works fine with TF2 recording.

**Comment by dtugend** [comment]
This error is not fatal and since you set `mirv_streams record fps 60` has no impact on the recording itself
(With the settings given it should create a folder untitled_rec with take folders inside, inside the game's .exe folder.)
Is the recording not working, are there other errors? Especially errors upon startup like a popup with title Error - AfxHookSource and something about hl_addresses.cpp?

**Comment by dtugend** [comment]
Hi I checked and noticed that the HLAE documentation / wiki is incorrect / not precise:

Apparently we currently only support the following games for screen recording:
- Alien Swarm
- CS:GO
- TF2
- CSS
- CSSV34
- Insurgency2

I will need the materialsystem.dll of L4D2 to make it work (it shouldn't be hard).
I also should add an error message for non-supported games, I forgot that apparently, it just fails silently.

**Comment by MaverickMSG** [comment]
> This error is not fatal and since you set `mirv_streams record fps 60` has no impact on the recording itself (With the settings given it should create a folder untitled_rec with take folders inside, inside the game's .exe folder.) Is the recording not working, are there other errors? Especially errors upon startup like a popup with title Error - AfxHookSource and something about hl_addresses.cpp?

Yeah, after I reported the bug I realized in TF2 I was getting the same *warning* but it was working anyway.  I figured this was specific to L4D2 support.  Is it possible to add L4D support as well, if it is easy?

**Comment by dtugend** [comment]
[AfxHookSource.zip](https://github.com/advancedfx/advancedfx/files/13799405/AfxHookSource.zip)
(In case you don't want to wait for next release.)

**Comment by MaverickMSG** [comment]
Can confirm this works with Left 4 Dead 2.  When rendering In 1080p @ 60fps:
Without HLAE, outputting startmovie (tga): 52 frames/sec
With HLAE, outputting to FFMPEG: 65 frames/sec
...these numbers match almost exactly with the numbers I've obtained for TF2

**Comment by dtugend** [comment]
@MaverickMSG in case you didn't notice in the commit message / edited thread topic, this also supports HL2MP (Half-Life 2: Deathmatch):
https://github.com/advancedfx/advancedfx/wiki/AfxHookSource#launching-half-life-2-deathmatch

**Comment by MaverickMSG** [comment]
Ah, thanks for the reminder.  Just verified it worked as expected in HL2MP.  When rendering In 1080p @ 60fps:
Without HLAE, outputting startmovie (tga): 65 frames/sec
With HLAE, outputting to FFMPEG: 85 frames/sec
...as noted previously, the speed increases seen here are consistent with TF2 and L4D2.

Thank you!
