### ISSUE TITLE
Add support for mirv_block_commands in TF2

### ISSUE THREAD

**Issue by MaverickMSG** [ripieces/advancedfx#898]
When playing back demos, I'd like to prevent the demo from issuing certain commands, for instance bringing up the setting menu item as seen in this video:
https://www.youtube.com/watch?v=7ZBKN_h_ixE
demo download: https://www.igmdb.org/?page=render&download_demo_id=46120

I believe mirv_block_commands will work to solve this problem but 1) it isn't supported in TF2 and 2) I'm not sure what command from the client needs to be blocked.

**Comment by dtugend** [comment]
[AfxHookSource.zip](https://github.com/advancedfx/advancedfx/files/14535383/AfxHookSource.zip)
This will always report command stack as 1 (client) in TF2, this means you need to block individual commands.
