### ISSUE TITLE
Wav file is corrupt in L4D2 when using demo_quitafterplayback

### ISSUE THREAD

**Issue by MaverickMSG** [ripieces/advancedfx#900]
This bug is the same as https://github.com/advancedfx/advancedfx/issues/847 except it is happening in Left 4 Dead 2.

When using demo_quitafterplayback 1, the game will quit without properly closing out the .wav file, rendering the .wav file unreadable by ffmpeg.

**Comment by dtugend** [comment]
[AfxHookSource.zip](https://github.com/advancedfx/advancedfx/files/13916814/AfxHookSource.zip)
@MaverickMSG can you please test

**Comment by MaverickMSG** [comment]
Confirmed on L4D2 to be working properly.  Have not tested in HL2MP, but I'm assuming it is good there.  Thank you @dtugend
