### ISSUE TITLE
counter-strike: source v34 ffmpeg recording

### ISSUE THREAD

**Issue by p1gaz1o** [ripieces/advancedfx#901]
Hi,

I've been struggling to get ffmpeg working with css v34, is it possible? If so can i get any light pls?
I'm currently trying these commands and the recordings don't output video:

unbind "f4"

mirv_streams record name _css_clips_
mirv_streams settings add ffmpeg tx00 "-c:v prores_ks -profile:v 4 -qscale:v 0 -vendor ap10 -pix_fmt yuva444p10le -c:a pcm_s16le {QUOTE}{AFX_STREAM_PATH}\recording_tx00.mov{QUOTE}"

mirv_streams add baseFX base
mirv_streams edit base sttings tx00

bind "f3" "mirv_streams print"
bind "f4" "mirv_streams record start;mirv_campath draw enabled 0"
bind "f5" "mirv_streams record end;mirv_campath draw enabled 1"

Thank you!

**Comment by Dechno1337** [comment]
You can only use the screen recording feature in CSS with HLAE (which allows ffmpeg):
https://github.com/advancedfx/advancedfx/wiki/Source%3Amirv_streams#recording-other-games-than-csgo

**Comment by 1dryver** [comment]
> You can only use the screen recording feature in CSS with HLAE (which allows ffmpeg):
> https://github.com/advancedfx/advancedfx/wiki/Source%3Amirv_streams#recording-other-games-than-csgo

I will try that, ty!

**Comment by p1gaz1o** [comment]
> You can only use the screen recording feature in CSS with HLAE (which allows ffmpeg): https://github.com/advancedfx/advancedfx/wiki/Source%3Amirv_streams#recording-other-games-than-csgo

I got the recording working but now the codec (mirv_streams record screen settings afxFfmpegYuv420p) is bad for editing, I tried incorporating mine (ffmpeg -c:v prores_ks -profile:v 4 -qscale:v 0 -vendor ap10 -pix_fmt yuva444p10le -c:a pcm_s16le) and it doesnt work, any clue why?

**Comment by Dechno1337** [comment]
> I got the recording working but now the codec (mirv_streams record screen settings afxFfmpegYuv420p) is bad for editing, I tried incorporating mine (ffmpeg -c:v prores_ks -profile:v 4 -qscale:v 0 -vendor ap10 -pix_fmt yuva444p10le -c:a pcm_s16le) and it doesnt work, any clue why?

I think you can still use this:
> mirv_streams settings add ffmpeg tx00 "-c:v prores_ks -profile:v 4 -qscale:v 0 -vendor ap10 -pix_fmt yuva444p10le -c:a pcm_s16le {QUOTE}{AFX_STREAM_PATH}\recording_tx00.mov{QUOTE}"

`tx00` is the preset name to use instead of `afxFfmpegYuv420p`.

**Comment by p1gaz1o** [comment]
> tx00

well now is definitely recording but the footage is still in  .mp4 i'm currently using this (alias prores "mirv_streams record screen settings tx00 "-c:v prores_ks -profile:v 4 -qscale:v 0 -vendor ap10 -pix_fmt yuva444p10le -c:a pcm_s16le e:\mvm_clipsrecording_tx00.mov"") and tried this (alias prores "mirv_streams record screen settings tx00 "-c:v prores_ks -profile:v 4 -qscale:v 0 -vendor ap10 -pix_fmt yuva444p10le -c:a pcm_s16le {QUOTE}{AFX_STREAM_PATH}\recording_tx00.mov{QUOTE}"" with the same result

**Comment by Dechno1337** [comment]
> alias prores "mirv_streams record screen settings tx00"

Use that ^ (after you have added/made the custom ffmpeg preset with the previous command I mentioned)

**Comment by Dechno1337** [comment]
Solved I guess. 🙂
