### ISSUE TITLE
Game crashing after update

### ISSUE THREAD

**Issue by c58EndER** [ripieces/advancedfx#907]
(Please search existing **open and closed** issues first to verify this is a new bug report.)
Game is crashing when im try to watch demo after big cs update

**Comment by c58EndER** [comment]
https://github.com/advancedfx/advancedfx/assets/159305700/969ce866-ed6e-46c8-815b-c8c0c6436301

**Comment by dtugend** [comment]
Can you try https://github.com/advancedfx/advancedfx/releases/tag/v2.154.2

**Comment by c58EndER** [comment]
> Can you try https://github.com/advancedfx/advancedfx/releases/tag/v2.154.2

same problem :C
waiting for valve hot fix

**Comment by dtugend** [comment]
does the demo crash without HLAE too?
If yes it's a demo problem and nothing we can do.

**Comment by c58EndER** [comment]
> does the demo crash without HLAE too? If yes it's a demo problem and nothing we can do.

Yep. Game was crashed without hlae :C
Reported this problem to valve support
Thank you

**Comment by dtugend** [comment]
To be honest I doubt they'll fix it very soon, because in CS2 older demos being broken after updates happens very often due to them changing a lot of things.
