### ISSUE TITLE
Error code 2001

### ISSUE THREAD

**Issue by fkdok91** [ripieces/advancedfx#909]
![Desktop Screenshot 2024 02 07 - 20 43 31 83](https://github.com/advancedfx/advancedfx/assets/159314101/c82b9847-6374-4cf8-87ca-2f137f966f14)

**Comment by c58EndER** [comment]
> (Please search existing **open and closed** issues first to verify this is a new question.) ![Desktop Screenshot 2024 02 07 - 20 43 31 83](https://private-user-images.githubusercontent.com/159314101/303086074-c82b9847-6374-4cf8-87ca-2f137f966f14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMjg2MjIsIm5iZiI6MTcwNzMyODMyMiwicGF0aCI6Ii8xNTkzMTQxMDEvMzAzMDg2MDc0LWM4MmI5ODQ3LTYzNzQtNGNmOC04N2NhLTJmMTM3Zjk2NmYxNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QxNzUyMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YWZiNzA2MGUyNjk5NzczZGNjZjZmMGVhYzBhNTkwN2ZkMjdlOTM4ZTc2MzhlOWMzZTlkZjNmMmQxNzhlZjFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XEcqq-20lfFP1Nyyv6C32Wrl6mqUli0mOB3wdLPYt78)

Похоже что ты неправильно настроил hlae.
Зайди в инструменты, разработчик, пользовательский загрузчик и укажи правильный путь к файлам
Путь к программе: C:\Steam\steamapps\common\Counter-Strike Global Offensive\game\bin\win64\cs2.exe
DLL для иньекции: в папке hlae зайди в папку x64 и выбери файл AfxHookSource2.dll
всё должно работать

**Comment by fkdok91** [comment]
Все стоит и так , все ровно выдает одну и туже ошибку.

**Comment by fkdok91** [comment]
Причем через пользовательский загрузчик без ошибок вход, но не сохраняет AGR DEMO ( ВООБЩЕ НИ ГДЕ) . А если через ЗАПУСТИТЬ CS:GO то выдает сразу эту ошибку ,все настроено правильно (3 раза перепроверил уже)

**Comment by fkdok91** [comment]
Запускается только cs go legacy version правильно . Но толку от этого.... 
Очень надеюсь что помогут найти решение этой проблемы

**Comment by Dechno1337** [comment]
Which game are you trying to inject into?

What do your custom loader settings look like?

**Comment by fkdok91** [comment]
> В какую игру вы пытаетесь внедриться?
> 
> Как выглядят ваши пользовательские настройки загрузчика?

CS 2.  C:\Steam\steamapps\common\Counter-Strike Global Offensive\game\bin\win64\cs2.exe
AfxHookSource2.dll

**Comment by fkdok91** [comment]
![Screenshot_1](https://github.com/advancedfx/advancedfx/assets/159314101/f497311c-cfe1-4fc5-810e-a79950e1f3e3)
![Screenshot_2](https://github.com/advancedfx/advancedfx/assets/159314101/1f11e58b-e660-4cf0-b243-505379a4242a)

**Comment by Dechno1337** [comment]
> C:\Steam\steamapps\common\Counter-Strike Global Offensive\game\bin\win64\cs2.exe

`C:\Steam`? Did you mean `C:\Program Files (x86)\Steam`?

P.S. AGR is not supported in CS2, if you wanted to use that. You can use Source 2 Film Maker if you want to do 3D stuff.

**Comment by fkdok91** [comment]
> > C:\Steam\steamapps\common\Counter-Strike Глобальный Offensive\game\bin\win64\cs2.exe
> 
> `C:\Steam`? Вы имели в виду `C:\Program Files (x86)\Steam`?
> 
> P.S. AGR не поддерживается в CS2, если вы хотели это использовать. Вы можете использовать Source 2 Film Maker, если хотите создавать 3D-материалы.

can the Source 2 filmmaker be migrated to Unreal Engine 5? I'm sorry, I use Google translator.

**Comment by fkdok91** [comment]
Strangely, there are tutorials on YouTube where exactly AGR in cs go 2 is recorded (without this error, which I have). Well , I get it , thanks for the clarification , otherwise I would have been stupid for another week

**Comment by Dechno1337** [comment]
> can the Source 2 filmmaker be migrated to Unreal Engine 5?

I don't know.

> Strangely, there are tutorials on YouTube where exactly AGR in cs go 2 is recorded (without this error, which I have).

Can you link one? Because I cannot find any.
