### ISSUE TITLE
CS2: Paused demo messes up with tick/time info that HLAE gathers

### ISSUE THREAD

**Issue by Dechno1337** [ripieces/advancedfx#910]
If you try to add campaths in a paused demo, and adjust the time with commands (`demo_goto`/`gototick`) and the demo is still paused, HLAE will think the old tick is now at the new tick, which will overwrite the previous campath keyframe.

**Workaround**: A brief amount of demo time (1 frame/tick?) needs to pass (by resuming the demo playback).

**Comment by dtugend** [comment]
The campaths are not based on tick, but on client (demo time).
The time not updating when using these commands (check with mirv_campath print) would be a CS2 bug, not a HLAE bug.

Maybe it's a problem with the interpolation, if that's the case temporarily setting
```
mirv_cvar_unhide_all; cl_interpolate false
```
Might work around it too, but might have other side effects (especially if  you forget to set it back).

**Comment by Dechno1337** [comment]
`mirv_campath print` changes the "old" keyframe to the new tick - demoTime seems to change as well, but not gameTime, while the demo is paused, so not sure if it's a HLAE bug or a CS2 side effect.

Another possible side effect: Resuming the demo will cause the information to update so it changes it back to its original tick/time when the campath was first added, even if you added more campath keyframes that replaced the original.

> ```
> mirv_cvar_unhide_all; cl_interpolate false
> ```
> 
> Might work around it too, but might have other side effects (especially if you forget to set it back).

Didn't change anything as far as I could tell.

**Comment by dtugend** [comment]
I will see if I can fix it, maybe there's another game time I can use tat doesn't have that problem.

**Comment by dtugend** [comment]
I checked, this is a bug with the game, not HLAE sadly.
