### ISSUE TITLE
Hlae crashes whenever i try to launch it

### ISSUE THREAD

**Issue by whiteboycooksrice** [ripieces/advancedfx#912]
Whenever i try to open hlae after finding the new path through creator tools, it just immediately crashes

**Comment by Dechno1337** [comment]
What are your Custom Loader settings?

**Comment by dtugend** [comment]
Please also let us know what you mean by "Creator Tools" and which HLAE version you are using.

**Comment by dtugend** [comment]
Closing this in favor of #914 - if your issue is different from that one, please let us know.
