### ISSUE TITLE
how to play campath in realtime?

### ISSUE THREAD

**Issue by adamejzak** [ripieces/advancedfx#913]
how to play campath in realtime? i make campath and idk how to play in realtime

**Comment by Dechno1337** [comment]
In a demo, on your own server or on a live match as an observer?

**Comment by ajz4k** [comment]
own server or gotv

**Comment by adamejzak** [comment]
live match on my own server xD

**Comment by Dechno1337** [comment]
If you have made or loaded a campath, then it should be:
`mirv_campath enable 1; mirv_campath edit start`

**Comment by dtugend** [comment]
> live match on my own server xD

Please be aware that HLAE is not meant to be used directly on a secure server.
You can however enable a CSTV (tv_enable 1 before map load) on the CSTV port (27020) and connect to that as an observer, that will however require the new tv_secure_bypass setting on 1.

**Comment by dtugend** [comment]
I consider this answered, if not please let us know.
