### ISSUE TITLE
CS2: Improve mirv_streams record screen

### ISSUE THREAD

**Issue by dtugend** [ripieces/advancedfx#915]
- <strike>enabled by default</strike>
- set host_framerate from mirv_streams record FPS (if not default), otherwise detect host_framerate (and revert after recording)
- make startmovie / endmovie for wav calls work without mirv_cvar_unhide_all
- toggle r_always_render_all_windows 1 while recording

**Comment by Dechno1337** [comment]
* The default record FPS should probably be set to 60 or something? Or would that force `host_framerate 60` even when not recording, or does it only set that while recording?
