### ISSUE TITLE
CS2: only audio is recorded

### ISSUE THREAD

**Issue by 1mpulse** [ripieces/advancedfx#916]
```
Starting recording ... done.
Recording to "C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\game\bin\win64\temp\take0004".
[Movie] Started recording movie: movie/2024_02_28_02_12_40/advancedfx-802bb089-972b-4841-bdf3-5108175ab59d.*: framerate 60.000000
```

Settings:
```
mirv_streams record screen enabled 1

mirv_streams record screen settings ff

host_framerate 60

mirv_streams record name "temp"

mirv_streams record fps 60

mirv_streams settings edit ff options "-c:v h264_nvenc -b:v 16976944 -pix_fmt yuv420p -preset superfast -vf {QUOTE}vibrance=intensity=0.5,colorbalance=rm=0.04,curves=all=0/0 0.5/0.65 1/1{QUOTE} -y {QUOTE}{AFX_STREAM_PATH}\video.mp4{QUOTE}"
```

`temp/take0004/...` - only `audio.wav`

**Comment by dtugend** [comment]
Please first try without FFMPEG settings to make sure it's not related to problems with that.
Also check for error messages in yellow font in console after / during starting recording.

**Comment by Dechno1337** [comment]
You may need to enter/put
`mirv_streams settings edit ff options "..."` (also, isn't it `add` instead of `edit`?) 🤔 
before `mirv_streams record screen settings ff`

**Comment by 1mpulse** [comment]
> Please first try without FFMPEG settings to make sure it's not related to problems with that. Also check for error messages in yellow font in console after / during starting recording.

on default settings, also only sound. No error: 
"Starting recording ... done."

**Comment by dtugend** [comment]
Can you please provide a bit more info about:

- Graphic card and driver you use
- Operating system used
- If you are using CS2 with D3D11 (default on Windows 10 for CS2) or Vulkan (Vulkan won't work with HLAE recording / campath draw)
- if `mirv_campath draw enabled 1` works (in case you know how to make campaths)
- Also please check the console a bit further down if there's any mention of: "AFXERROR: GpuCopyResource - unspported DXGI_FORMAT: ..."

Edit: And please also:
- The HLAE version you are using (check the title bar)
- The file size in bytes of your AfxHookSource2.dll (the smaller one of the two, mine is 476672 bytes, if your's is different you are using wrong DLL) and the path to it displayed in Custom Loader

**Comment by 1mpulse** [comment]
yes, the problem was in the `-vulkan` startup parameter.
Thank you very much for your help
