### ISSUE TITLE
CS2: mirv_streams record screen records asset browser preview when using Workshop Tools

### ISSUE THREAD

**Issue by hjbdev** [ripieces/advancedfx#917]
I'm launching CS2 with the `-tools` launch option in order to get telnet working (`-netconport` launch option) for remote control of the game.

When recording with mirv_streams and ffmpeg, I get a [grey output](https://streamable.com/79t4zl), because HLAE is recording the texture preview window of the Asset Browser.
![image](https://github.com/advancedfx/advancedfx/assets/30434619/8920350b-2de1-48ce-a490-7370967feb68)

[My config](https://gist.github.com/hjbdev/54cd5e0790bcc2c4f471f20ef8217923)

There is an option to close the preview of the asset browser, and even close the asset browser completely. It seems the preview is still being rendered _somewhere_ though as neither of these have an effect.

Unfortunately for telnet to work on Windows you have to use the workshop tools until [this issue](https://github.com/ValveSoftware/csgo-osx-linux/issues/3603) is resolved.

HLAE Ver: 2.155.1.0

Thanks for all the hard work!

**Comment by dtugend** [comment]
As a workaround add `-noassetbrowser` to the launch options additionally to `-tools`.

**Comment by hjbdev** [comment]
didn't know that existed, it worked perfectly. Thank you!

**Comment by dtugend** [comment]
(Considering #896 the workaround will have to do for now.)
