### ISSUE TITLE
static cam? cs2

### ISSUE THREAD

**Issue by adamejzak** [ripieces/advancedfx#918]
Is it possible to set up a static camera with HLAE? When I use the spec_mode and spec_goto commands, my camera flies from the player to the camera position. I want the camera to just set its position, not move xD And after executing spec_goto, I'd like to activate afx_smooth_on.

**Comment by ajz4k** [comment]
and after spec_goto execute afx_smooth_on

**Comment by dtugend** [comment]
You could try `cl_obs_interp_enable 0`.

Alternatively you can enable mirv_input without smoothing at first and use the mirv_input position/angles/fov to set the desired values, before turning on the smoothing.

**Comment by ajz4k** [comment]
okay fine, i have one more question
how to bind zooming pgup/pgdown to scroll?

**Comment by dtugend** [comment]
Is the question solved? (Asking because something in here disappeared and not sure if intentional.)
