### ISSUE TITLE
[CSS] camio doesn't convert game fov to after effects fov

### ISSUE THREAD

**Issue by eirisocherry** [ripieces/advancedfx#919]
- [x] CSS camio doesn't convert game fov to after effects fov

csgo camio converts game fov to after effects fov  
> ex: mirv_fov default (90) converts to 120.922435  
![image](https://github.com/advancedfx/advancedfx/assets/115040224/48251cb4-44da-448c-af93-7d6d370ea4f4)  

but css camio doesn't  
> mirv_fov default (90) gives value of 90  
![image](https://github.com/advancedfx/advancedfx/assets/115040224/57c5f8fc-227b-4aa7-a032-308c328ce9a7)

### Useful test  
I recorded css pov (mirv_fov default) and css cine (mirv_input fov 50) using `mirv_streams record screen enabled 1`  
and tried to set after effects fov manually  

csgo camio says
90 is 120.922435  
50 is 78.901646  

I set these values but 3d tracking was still off
I played with the values a bit and noticed that if you subtract 12.5 degree from after effects fov, 3d tracking will be fixed  
120.922435-12.5=108.422435
78.901646-12.5=66.401646
Here's the result: https://github.com/advancedfx/advancedfx/assets/115040224/51700180-c168-4bdf-b44b-20377653d7eb  

I was using  
`fov_cs_debug 0` in csgo  
`demo_fov_override 0` in css  

So I'm pretty sure CSS and CSGO FOVs are different by default    

- [x] Also, could you, please, bring back `mirv_streams record cam enabled 1` command  
because `mirv_camio export start <name>` is exporting cam data to the game folder, that's not cool

**Comment by dtugend** [comment]
1. I am not sure why you need to set the FOV, since the plugin by XNWP should already do that: https://github.com/xNWP/HLAE-CamIO-To-AE (**make sure to set ScaleFov to _FALSE_ in the options**, CSS doesn't scale the FOV). If it's still setting the wrong FOV even with ScaleFov FALSE, consider to report the bug to the AE plugin author instead (not an HLAE problem).
2. `mirv_streams record cam enabled 1` has been indeed accidentally removed from non-CS:GO games, which is a bug.

**Comment by dtugend** [comment]
To be clear, camio version 2 outputs the real vertical FOV value, which for CS:GO is scaled depending on aspect ratio and for CSS is not scaled, so the output values are correct in that regard.
Converting it to the FOV convention the target platform (e.g. After Effects) uses, is not part of that, that's to be done by the importing plugin, but XNWp's plugin should work, unless there's some bug. Which plugin did you use to import?

**Comment by dtugend** [comment]
![image](https://github.com/advancedfx/advancedfx/assets/3610128/ff964a21-0e0b-4a4c-95b1-8d8991445922)
It seems you are not using the original latest version of XNWP's script, but a modified one.
Please retry with the official one by XNWP: https://github.com/xNWP/HLAE-CamIO-To-AE/releases instead
If that one works, please report the bug to where you got yours from.

**Comment by eirisocherry** [comment]
Here's a video where I use the original latest version of XNWP's script with a broken ui:  
https://github.com/advancedfx/advancedfx/assets/115040224/d71f789b-ee85-4d3d-881d-3744ea31e025

Unfortunately, XNWp's script doesn't automatically convert FOV.

**Comment by dtugend** [comment]
It does correctly, since 90 is the original FOV ans CSS doesn't scale the FOV last time I checked.

Please provide the following information:
1. What are your HLAE settings / game settings with regards to the screen resolution (width and height in pixels).
2. Did you crop / scale or otherwise change the aspect ratio of the footage? How did you record the footage?

**Comment by eirisocherry** [comment]
I found the issue, lemme record it real quick

**Comment by eirisocherry** [comment]
So, in CSS there is a `sv_restrict_aspect_ratio_fov` command which is set to `1` by default
> - This can be used to limit the effective FOV of users using wide-screen
> resolutions with aspect ratios wider than 1.85:1 (slightly wider than 16:9).
>    0 = do not cap effective FOV
>    1 = limit the effective FOV on windowed mode users using resolutions
>        greater than 1.85:1
>    2 = limit the effective FOV on both windowed mode and full-screen users

To disable the restriction you need to use `sv_restrict_aspect_ratio_fov 0` and then your FOV will be the same as in CSGO  
Resolutions must be the same you say, it's true (I was using 1920x816 in both games)  

Here's the video with `sv_restrict_aspect_ratio_fov 0`  
CSS POV: https://github.com/advancedfx/advancedfx/assets/115040224/47004fa3-54e0-4f0d-a94d-cd9fd2180a0d
CSS CINE 50 FOV: https://github.com/advancedfx/advancedfx/assets/115040224/6c804363-0755-4544-a938-299e59a84a81  

I use csgo camio values
90 is 120.922435
50 is 78.901646
and everything works now!

**Comment by eirisocherry** [comment]
> 1. I am not sure why you need to set the FOV, since the plugin by XNWP should already do that: https://github.com/xNWP/HLAE-CamIO-To-AE (**make sure to set ScaleFov to _FALSE_ in the options**, CSS doesn't scale the FOV). If it's still setting the wrong FOV even with ScaleFov FALSE, consider to report the bug to the AE plugin author instead (not an HLAE problem).

When I do this, it just sets after effects FOV to infinity  
https://github.com/advancedfx/advancedfx/assets/115040224/9c325693-f05b-4796-8fb4-c1452df5643e

I reopened After Effects, still the same issue
I tried it with CSGO camio file, still the same issue

Okay, I will report it to him.

**Comment by eirisocherry** [comment]
Are you sure you don't want to make scaledFOV=1 for css camio file, tho?  
Why not to make csgo camio and css camio just the same? It will be easier for everyone (you, users, xNWP)  

As an option you could make "scaledFOV=1" for `mirv_streams record cam enabled 1` command  
and "scaledFOV=0" for `mirv_camio export start <name>`  
or maybe just add a whole separate command such as `mirv_camio scaledFOV <1/0>`  

After Effects is a slow/buggy program (+ people may use different versions of after effects)
I think all possible calculations must be done in-game

**Comment by dtugend** [comment]
> > 1. I am not sure why you need to set the FOV, since the plugin by XNWP should already do that: https://github.com/xNWP/HLAE-CamIO-To-AE (**make sure to set ScaleFov to _FALSE_ in the options**, CSS doesn't scale the FOV). If it's still setting the wrong FOV even with ScaleFov FALSE, consider to report the bug to the AE plugin author instead (not an HLAE problem).
> 
> When I do this, it just sets after effects FOV to infinity https://github.com/advancedfx/advancedfx/assets/115040224/9c325693-f05b-4796-8fb4-c1452df5643e
> 
> I reopened After Effects, still the same issue I tried it with CSGO camio file, still the same issue
> 
> Okay, I will report it to him.

I was mistaken about how the plugin of XNWP, works, there should be no need to change the ScaleFov in the source code, this is not a bug by them, no need to report this particular issue there.

**Comment by eirisocherry** [comment]
ok

**Comment by dtugend** [comment]
Not sure when the next release will be, if you want to test and not compile it yourself from main branch:
[AfxHookSource.zip](https://github.com/advancedfx/advancedfx/files/14722785/AfxHookSource.zip)

**Comment by eirisocherry** [comment]
Thank you!

`mirv_camio export start <name>` gives you a scaled fov and 3d tracking works fine  
![Screenshot_2](https://github.com/advancedfx/advancedfx/assets/115040224/03dda52a-f29f-43e4-98a9-56e4e9e3582f)

but
- [x] when you record with `mirv_streams record cam enabled 1` cam_main.cam is empty  
![image](https://github.com/advancedfx/advancedfx/assets/115040224/6b27eaab-9b29-4dfa-9d93-414eeb915e15)  
- [x] Also `sv_restrict_aspect_ratio_fov 0` must be forced, otherwise 3d tracking won't be accurate, because by default `sv_restrict_aspect_ratio_fov` is set to `1`
> 0 = do not cap effective FOV
> 1 = limit the effective FOV on windowed mode users using resolutions
greater than 1.85:1

It's easy for me to activate the command manually, but other people may don't know about it and they will prolly immediately give up on that idea, because their 3d tracking won't work

**Comment by dtugend** [comment]
[AfxHookSource.zip](https://github.com/advancedfx/advancedfx/files/14726875/AfxHookSource.zip)
This one should work fine. However it will record cam always, even when console is open, while the video and sound is only recorded in games other than CS:GO when console is closed, but I am afraid to change that behavior for backwards compatibility reasons.

**Comment by eirisocherry** [comment]
awesome, it works now!
