### ISSUE TITLE
[CSS V84] "mirv_campath draw enabled 1" crashes the game

### ISSUE THREAD

**Issue by eirisocherry** [ripieces/advancedfx#920]
# Why I care about V84, when the latest one is V92?  
> CSS V84 (19 May 2014 – 21:04:57 UTC)  
> CSS V85 (16 September 2015 – 22:30:28 UTC)  
> CSS V92 (2 July 2021 – 20:29:06 UTC) the latest one currently  

Because valve broke demos and demo playback in CSS V85 and still haven't fixed anything up to this moment  
even tho it's a well known bug: https://github.com/ValveSoftware/Source-1-Games/issues/3112  

## Сlear example of demo playback bug
> Steam versions have the same issues, so ignore the fact I use no steam versions  

1. Opening V84 demo in CSS V84:  
https://github.com/advancedfx/advancedfx/assets/115040224/4a5befb4-a357-48c1-befe-7a65b54a12a7  
> Everything works just fine
> demo_gototick 20k ✓ 15k ✓ 10k ✓  
2. Opening V92 demo in CSS V84:  
https://github.com/advancedfx/advancedfx/assets/115040224/6de40402-ad22-45a5-a1da-0385a3764fd6  
> The demo loads much slower and on some ticks crashes with this error "Host_Error: CL_PreserveExistingEntity: missing client entity X"  
> demo_gototick 20k ✓ 15k ⨯ 14.5k ✓ 10k ✓  
3. Opening V84 demo in CSS V92:  
https://github.com/advancedfx/advancedfx/assets/115040224/8d8d142c-b658-4272-b18b-f89b56a55429  
> It instantly crashes when I use any demo_gototick and then I can't even load the demo anymore until I reopen the game  
> I just keep getting this error: "Host_Error: CL_PreserveExistingEntity: missing client entity X"  
4. Opening V92 demo in CSS V92:
https://github.com/advancedfx/advancedfx/assets/115040224/0385ffac-b778-4afa-8af6-7448b4bc316d
> Same story, the demo instantly crashes when I use any demo_gototick and then I can't even load the demo anymore until I reopen the game  
> I just keep getting this error: "Host_Error: CL_PreserveExistingEntity: missing client entity X"  

## Demo playback possible fix  
Someone made a fix for a steam version of css v92, but i'm scared to try it out, because you need to use cheat engine to activate it.  
One wrong step and you're vac banned: https://github.com/0x00000ED/CSSource_TF2_FIX_Demo_CL_PreserveExistingEntity  

# [CSS V84] "mirv_campath draw enabled 1" crashes the game  
> I hope I've convinced you to keep hlae support for css v84  
> Living without demo_gototick command is super hard  
> Let's say a moment you wanna edit is on 30000 tick, it means you will have to spend about 2 minutes just to rewind the demo
> Also there is good chance your demo will crash even if you don't use demo_gototick command  

[HLAE 2.145.7](https://github.com/advancedfx/advancedfx/releases/tag/v2.145.7):  
https://github.com/advancedfx/advancedfx/assets/115040224/7c72f1c1-ab48-4418-9b4d-a8443276c4f6  
> Work just fine with CSS V84, `mirv_campath draw enabled 1` doesn't do anything bad  

[HLAE 2.146.0](https://github.com/advancedfx/advancedfx/releases/tag/v2.146.0) and newer:  
https://github.com/advancedfx/advancedfx/assets/115040224/0ac6d14f-94f7-4b4f-9259-58d817e69cee  
> Sometimes, when I do demo_gototick, `mirv_campath draw enabled 1` crashes the game  

[HLAE 2.148.3.2](https://github.com/advancedfx/advancedfx/releases/tag/v2.148.3.2) and newer:  
https://github.com/advancedfx/advancedfx/assets/115040224/5c38f1eb-f08f-4770-8624-ee36e43d8af9  
> `mirv_campath draw enabled 1` immidiately crashes the game  

# How to install official CSS V84?  
> https://steamdb.info/app/240/depots/  

Installation for people who bought the game in steam:  
1. Open steam  
2. Press [Win + R] and type in `steam://open/console`  
3. In the console type in  
`download_depot 240 241 260467363272803259` to download the first part of the game  
`download_depot 240 232331 1065075871622074600` to download the second part of the game  
4. Go to "Steam\steamapps\content\app_240" and combine "depot_241" and "depot_232331" folders  
5. Rename combined folder to "CSS V84" and move it wherever you want  
6. Open "CSS V84" folder, create "start.bat" and paste `hl2.exe -game cstrike` line into it, save the file  
7. Open "start.bat" and enjoy the game  

> If you don't have a steam version of css, I can send you a no steam one, so you can test and fix the bug

**Comment by dtugend** [comment]
Our policy has always been to support only the latest Steam version (with CSSV34 being an exception).
I do not want to spend time supporting another versions myself.

I instead am implementing the fix the that you linked in HLAE:
[AfxHookSource.zip](https://github.com/advancedfx/advancedfx/files/14727485/AfxHookSource.zip)
Try `mirv_fix suppressClPreserveExistingEntityHostError 1`

**Comment by eirisocherry** [comment]
> Our policy has always been to support only the latest Steam version (with CSSV34 being an exception).
> I do not want to spend time supporting another versions myself.

I got you, if you could fix demo playback for the latest version it would be amazing  

When I do `demo_gototick` with `mirv_fix suppressClPreserveExistingEntityHostError 1`, the demo lasts a bit longer and closes with the same error "Host_Error: CL_PreserveExistingEntity: missing client entity X"  
https://github.com/advancedfx/advancedfx/assets/115040224/2db36762-33fc-4bad-856c-bc89a4301a55  

Here's the demo:  
[v92.zip](https://github.com/advancedfx/advancedfx/files/14727541/v92.zip)

**Comment by dtugend** [comment]
[AfxHookSource.zip](https://github.com/advancedfx/advancedfx/files/14728357/AfxHookSource.zip)
I renamed it: Try `mirv_fix suppressHostError 1`
Please note that this is not a proper fix for the problem / a workaround at best, while it does work on your demo it seems, I think it will have side effects. Probably it's a good idea to let it play from round start before recording, after using GOTO.

I don't think I have the time to make a proper fix, since Valve didn't even bother while having the source code, it would be too time consuming for me right now

**Comment by eirisocherry** [comment]
It works for the first 5k ticks, but then I get different errors like this  
![image](https://github.com/advancedfx/advancedfx/assets/115040224/de31f9b7-3158-43fd-b7fd-1a093e98b9c1)  

> I don't think I have the time to make a proper fix, since Valve didn't even bother while having the source code, it would be too time consuming for me right now  

Yeah, I knew it, that's why asked for v84 fix  


When you have time, could you, please, make a private hlae build with fixed camio that will work in CSS V84  🙏
It doesn't have to be the latest hlae version, i'm good with [2.145.7 version that works in css v84 just fine](https://github.com/advancedfx/advancedfx/releases/tag/v2.145.7) too  
I really need this fixed camio in v84

**Comment by dtugend** [comment]
https://github.com/advancedfx/advancedfx/releases/tag/v2.156.0

Add `-afxGame css_v84` to launch options.

**Comment by eirisocherry** [comment]
Thank you so much!!!!!!!! ❤️❤️❤️❤️❤️

you forgot to add `sv_restrict_aspect_ratio_fov` into scaled fov calculations  
when fov=90 and sv_restrict_aspect_ratio_fov=1, it should return ~108 not 120  
![image](https://github.com/advancedfx/advancedfx/assets/115040224/439fc47a-b15c-4544-ac60-52c0f0f913bb)  
![image](https://github.com/advancedfx/advancedfx/assets/115040224/dd5bfd6c-ce8c-47cc-875c-4d68ee268772)

**Comment by dtugend** [comment]
It's bugged, I didn't forget it, but probbly the VTable offset of IsWindowedMode is different than from current CSS and I didn't test it one more time.

As a temporary workaround you can set `sv_restrict_aspect_ratio_fov 2` when your screen resolution aspect ratio is greater than 1.85 and you are in windowed mode.

Please open a separate issue for the bug.

**Comment by dtugend** [comment]
I opened the separate issue here: https://github.com/advancedfx/advancedfx/issues/921

**Comment by eirisocherry** [comment]
> It's bugged, I didn't forget it, but probbly the VTable offset of IsWindowedMode is different than from current CSS and I didn't test it one more time.
> 
> As a temporary workaround you can set `sv_restrict_aspect_ratio_fov 2` when your screen resolution aspect ratio is greater than 1.85 and you are in windowed mode.

`sv_restrict_aspect_ratio_fov 2` works, thanks
