### ISSUE TITLE
CSSV84 sv_restrict_aspect_ratio_fov 1 is not working correctly with HLAE fov scaling

### ISSUE THREAD

**Issue by dtugend** [ripieces/advancedfx#921]

**Comment by eirisocherry** [comment]
add `sv_restrict_aspect_ratio_fov` into scaled fov calculations  
when fov=90 and sv_restrict_aspect_ratio_fov=1, it should return ~108 not 120  
![image](https://github.com/advancedfx/advancedfx/assets/115040224/439fc47a-b15c-4544-ac60-52c0f0f913bb)  
![image](https://github.com/advancedfx/advancedfx/assets/115040224/dd5bfd6c-ce8c-47cc-875c-4d68ee268772)

**Comment by eirisocherry** [comment]
sv_restrict_aspect_ratio_fov 2 works, thanks

i deleted messages from previous issue to make it a bit more clean

**Comment by dtugend** [comment]
https://github.com/advancedfx/advancedfx/releases/tag/v2.156.1

**Comment by eirisocherry** [comment]
💪
