### ISSUE TITLE
nSkinz compatibility with CS2/HLAE/Streams

### ISSUE THREAD

**Issue by AllstarAnthony** [ripieces/advancedfx#924]

**Comment by Dechno1337** [comment]
nSkinz development was stopped, and I don't think there is any skin changer for CS2 yet? Unless you are asking someone to either port over nSkinz to CS2 or make a new one.

**Comment by AllstarAnthony** [comment]
I was hoping to see nSkinz be ported over to CS2!

**Comment by dtugend** [comment]
Hi thank you for your suggestion. A skin changer is really an endeavor on it's own. So closing it as not planned for now, especially considering issue 896.

**Comment by Kryzys7** [comment]
Any future notice?
