### ISSUE TITLE
Launch Option and Env to disable steam cloud syncing

### ISSUE THREAD

**Issue by Purple-CSGO** [ripieces/advancedfx#926]
## Problem

Steam Cloud Sync Fails the game setting isolation feature (by setting `USRLOCALCSGO=/path/of/dir` env when custom loading keep game settings isolated)

## To reproduce

- If the isolated dir is `D:\cs2local`, create the empty dir
- Add a new line `USRLOCALCSGO=D:\cs2local` to `Add Environment Variables: Name=Value` section in the `Custom Loading` panel
- Launch with hlae and change settings. For example, `bind p demo_togglepause`, which is different from your current game setting.
- Enter `bind p` to console. Check if the binding is correct.
- Quit game and launch from steam. Use `bind p` again. You will see the same binding

> Sometimes the steam cloud syncing fails. You would see a `warning+cloud` icon. In this situation, isolation is not affected.

## To solve

Add ways of disabling Steam Cloud Sync temporally to hlae.

## Suggest Format

Launch Option: `-AfxDisableSteamCloud`
Environment Variable: `DisableSteamCloud=1`

> !=0: do disable
> 0: do not disable.

**Comment by dtugend** [comment]
I added it as `-afxDisableSteamStorage` since that is the interface that it disables.
When I tested it it seemed to work, but another test by someone else wouldn't hurt.

**Comment by Purple-CSGO** [comment]
Test passed here

thx~
