### ISSUE TITLE
TF2: AfxHookSource.dll is no longer loading after tf2 64bit update

### ISSUE THREAD

**Issue by delegacz** [ripieces/advancedfx#928]
Recent tf2 update changed the executable to 64bit which changed the name of the exe file to tf.exe and tf_win64.exe; HLAE no longer work properly with an error that AfxHookSource.dll could not load

**Comment by cademtz** [comment]
I got the following error message when launching `tf.exe`:
```
Failed to inject image 'C:\Program Files (x86)\HLAE\AfxHookSource.dll'.
Error code 0xC0000135
```
The error code corresponds to the macro for `STATUS_DLL_NOT_FOUND`.

After installing some of the software to build AfxHookSource and some unrelated software, however, the issue had gone away. I'm still figuring out what exactly caused this.

**Comment by cademtz** [comment]
As long as you set the loader to launch `tf.exe`, and not `tf_win64.exe`, HLAE should load.

I don't think my previous comment was a related problem :smile:

**Comment by dtugend** [comment]
https://github.com/advancedfx/advancedfx/releases/tag/v2.158.0
