### ISSUE TITLE
HLAE Error 2001

### ISSUE THREAD

**Issue by Jay-X7** [ripieces/advancedfx#931]
I read through all the previous support threads and tried all solutions,

Restarted PC,

Checked all programs are set to run NOT as admin 

And I'm not running any anticheat or other software that I'm aware would cause this error to occur.

any help would be appreciated.

ERROR TEXT BELOW:

```
AfxError #2001: 
Title: Loader failed.Description: System.ApplicationException: 64 Bit CS:GO is not supported.
   at AfxGui.LaunchCsgo.GetHookPath(Boolean isProcess64Bit)
   at AfxGui.Loader.Load(IEnumerable`1 getHookPathCollection, String programPath, String cmdLine, String environment, Boolean showErrorMessage)Inner exception: {0}```

**Comment by Jay-X7** [comment]
> I read through all the previous support threads and tried all solutions,
> 
> Restarted PC,
> 
> Checked all programs are set to run NOT as admin
> 
> And I'm not running any anticheat or other software that I'm aware would cause this error to occur.
> 

Just checked and its also not my firewall I switched windows defender off and it still causes the error.

**Comment by Jay-X7** [comment]
Could it have anything to do with the cs2.exe file not showing up in the HLAE Path (it is there in the actual folders)

IMG 1 (HLAE Path)
![image](https://github.com/advancedfx/advancedfx/assets/52521940/7ac065fd-8bc1-4362-9352-7df6e3f0fd93)

IMG 2 (File Explorer)
![image](https://github.com/advancedfx/advancedfx/assets/52521940/1a4056b1-db3d-45be-b3ea-726c1c575d2e)

**Comment by dtugend** [comment]
You are using the wrong dialogue for opening CS2, the one you use is still for the old CS:GO.

For more instructions please see AfxHookSource2 wiki page:
https://github.com/advancedfx/advancedfx/wiki/AfxHookSource2
