### ISSUE TITLE
Latest CS2 update broke AfxHookSource2

### ISSUE THREAD

**Issue by Dechno1337** [ripieces/advancedfx#936]
![bild](https://github.com/advancedfx/advancedfx/assets/40070135/a886bd82-1a1c-4cd8-9177-988b28b8da06)

And the game seems to crash/close after the CS2 intro logo.

**Comment by Plse1032** [comment]
Same

**Comment by dtugend** [comment]
https://github.com/advancedfx/advancedfx/releases/tag/v2.160.0
