### ISSUE TITLE
Pre-25th Anniversary Build AfxHookGoldSrc Error

### ISSUE THREAD

**Issue by 591280714** [ripieces/advancedfx#942]
![image](https://github.com/advancedfx/advancedfx/assets/45847377/0eea0386-aa29-4c00-bc77-574dc666a34c)
![image](https://github.com/advancedfx/advancedfx/assets/45847377/04223add-354d-4be9-979b-de2d00fa282a)
![image](https://github.com/advancedfx/advancedfx/assets/45847377/8e7ffac6-4012-42c4-a502-06971776d5f8)
![image](https://github.com/advancedfx/advancedfx/assets/45847377/c9c85bda-bbc2-4bb1-a89d-7aa277111508)
![image](https://github.com/advancedfx/advancedfx/assets/45847377/ea979727-65b4-4511-89f5-9ad92e80d366)
![image](https://github.com/advancedfx/advancedfx/assets/45847377/d6394344-6aa8-48e3-94e3-5c331755d784)
![image](https://github.com/advancedfx/advancedfx/assets/45847377/76841d58-e4c8-4e7e-aaa2-e906cf44a671)
![image](https://github.com/advancedfx/advancedfx/assets/45847377/013a9864-69e2-4ae3-8493-3dfaa7812b43)
![image](https://github.com/advancedfx/advancedfx/assets/45847377/9fdedba7-fba4-45dc-bc70-aad8844f0b7f)
![image](https://github.com/advancedfx/advancedfx/assets/45847377/e9431644-0e79-4ddd-9287-e55e2ff51afe)
![image](https://github.com/advancedfx/advancedfx/assets/45847377/3bf50ceb-e905-4dc2-ae0d-dea986352306)
![image](https://github.com/advancedfx/advancedfx/assets/45847377/6e8186a7-e486-4bc3-ae69-43076a402f96)
![image](https://github.com/advancedfx/advancedfx/assets/45847377/d006d838-0e52-4970-b1e9-779f6d9009bf)
![image](https://github.com/advancedfx/advancedfx/assets/45847377/19895d96-ebab-43b2-b244-c41449079a09)
![image](https://github.com/advancedfx/advancedfx/assets/45847377/c5ed11f7-67c3-4d4c-bca9-5e7264537438)
![image](https://github.com/advancedfx/advancedfx/assets/45847377/a1925fca-5d33-4068-9d68-7bed618818e5)
![image](https://github.com/advancedfx/advancedfx/assets/45847377/437acc00-7146-4d9e-8347-e89e17a520b7)
![image](https://github.com/advancedfx/advancedfx/assets/45847377/1ab80ac2-077f-4377-86e6-d44fbe63df2c)
![image](https://github.com/advancedfx/advancedfx/assets/45847377/b075f7f1-5301-480f-bd6d-f31c5b0d5289)
![image](https://github.com/advancedfx/advancedfx/assets/45847377/ce3502cb-eb8b-4567-b402-b3c4b6bc7c6b)
![image](https://github.com/advancedfx/advancedfx/assets/45847377/88e970c4-6486-4c38-8830-0e861c8a51c4)

**Comment by Dechno1337** [comment]
Which HLAE version are you using?

**Comment by 591280714** [comment]
> Which HLAE version are you using?
2.162.0

**Comment by 591280714** [comment]
> Which HLAE version are you using?

2.162.0

**Comment by Dechno1337** [comment]
I'm pretty sure you need to use an older version:

![bild](https://github.com/advancedfx/advancedfx/assets/40070135/27156a8b-4079-4eb4-ad11-9a8f9c694cc1)

https://github.com/advancedfx/advancedfx/releases/tag/v2.153.1

**Comment by 591280714** [comment]
> I'm pretty sure you need to use an older version:
> 
> ![bild](https://private-user-images.githubusercontent.com/40070135/329943689-27156a8b-4079-4eb4-ad11-9a8f9c694cc1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1ODE3NTUsIm5iZiI6MTcxNTU4MTQ1NSwicGF0aCI6Ii80MDA3MDEzNS8zMjk5NDM2ODktMjcxNTZhOGItNDA3OS00ZWI0LWFkMTEtOWE4ZjljNjk0Y2MxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDA2MjQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlYjljZmVhOTk2ZTA0MTBhNjc2OWYyOTI2ZDMxMDNlNmFkYjdiODZjZDVmMjk0YjI3YjkxOGVmNTk1NWIzNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HIj514RVIPR98l1DdXkkGyNYPe_yMX0Mr8qOxhnqwE8)
> 
> https://github.com/advancedfx/advancedfx/releases/tag/v2.153.1

in that case I have to lose all the updates that since 2.153.1?

**Comment by Dechno1337** [comment]
> in that case I have to lose all the updates that since 2.153.1?

I don't think AfxHookGoldSrc has recieved any new features in newer versions. What feature(s) do you want to use?

**Comment by 591280714** [comment]
> > in that case I have to lose all the updates that since 2.153.1?
> 
> I don't think AfxHookGoldSrc has recieved any new features in newer versions. What feature(s) do you want to use?

I mean, maybe some fixes?

**Comment by Dechno1337** [comment]
I think these would be the only new features/fixes that you wouldn't have access to.

![bild](https://github.com/advancedfx/advancedfx/assets/40070135/375c6824-8605-4f64-8acc-e5f755e7f25f)

![bild](https://github.com/advancedfx/advancedfx/assets/40070135/93dc51b9-d374-45f0-a008-5e7c4391debf)

Do you have any use of those?

**Comment by 591280714** [comment]
> I think these would be the only new features/fixes that you wouldn't have access to.
> 
> ![bild](https://private-user-images.githubusercontent.com/40070135/329946094-375c6824-8605-4f64-8acc-e5f755e7f25f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1ODI0NDUsIm5iZiI6MTcxNTU4MjE0NSwicGF0aCI6Ii80MDA3MDEzNS8zMjk5NDYwOTQtMzc1YzY4MjQtODYwNS00ZjY0LThhY2MtZTVmNzU1ZTdmMjVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDA2MzU0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhOWFiMmNlNmQyYjczNzhiOTdlZTIyZTRhZjA5ODQzYzU2NjBjYjBjYjJjODk4MzRjNzhlODJlOTJmZjUxMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eFb4S5Gim4DeckCBKEwH-NTS0D-ezbz33Y1KYYygTcs)
> 
> ![bild](https://private-user-images.githubusercontent.com/40070135/329946219-93dc51b9-d374-45f0-a008-5e7c4391debf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1ODI0NDUsIm5iZiI6MTcxNTU4MjE0NSwicGF0aCI6Ii80MDA3MDEzNS8zMjk5NDYyMTktOTNkYzUxYjktZDM3NC00NWYwLWEwMDgtNWU3YzQzOTFkZWJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDA2MzU0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyNGE0YjA3MDg2YWVlYmUyYjMxNDdhZTljZjM2MmFlMzczZDMyZDE4M2NiNzM4YjE5NmRkYjY2NTM1ZmY3ODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bdVuTHtJnz7TkBXb267PhiKMLfWGanUHhPLnXsnlmCU)

Is it return to old version is the only way that can solve my problems?

**Comment by Dechno1337** [comment]
> Is it return to old version is the only way that can solve my problems?

If you want to use the pre-25th anniversary build, yes. Otherwise you need to use the latest version of the game.

**Comment by 591280714** [comment]
> > Is it return to old version is the only way that can solve my problems?
> 
> If you want to use the pre-25th anniversary build, yes. Otherwise you need to use the latest version of the game.

Okay, I got it. I think I will stick to pre-25th. because 25th is full of trash..
