### ISSUE TITLE
TF2 crashes when trying to playback campaths

### ISSUE THREAD

**Issue by wastedcore** [ripieces/advancedfx#943]
![snip1](https://github.com/advancedfx/advancedfx/assets/170143009/6a42bf6f-d934-450e-84be-e9af970bde9e)
This happens in tf2 and i dont know how to fix it

**Comment by 01230123abc** [comment]
might be related to #861

**Comment by dtugend** [comment]
I am unable to recreate the issue with the latest 32 bit version of TF2 (tf.exe (not to be confused with older hl2.exe!)) and latest HLAE version (2.162.0).

Please provide more information:

1. Settings you use in HLAE Custom Loader dialogue (e.g. if you have any -dxlevel ... options inside the options, please remove them and try again)!
2. output of `version` command in TF2 console.
3. output of `__mirv_info` command in TF2 console.
4. The sequence of relevant commands / actions you use / do to cause the bug.

Edit: If you have an addons folder in your tf sub-folder of the game, please also temporarily rename it and try again (this makes sure it's not a conflict with addons / plugins).

**Comment by wastedcore** [comment]
Version Command:
Build Label:           8835751  
Network PatchVersion:  8835751   
Protocol version:           24   
Server version:        8835751
Server AppID:           232250
Client version:        8835751
Client AppID:              440
__mirv_info Command:
| AfxHookSource (May 11 2024 19:31:07)
| http://advancedfx.org/
|
| VClient: VClient017
| VEngineClient: VEngineClient013
| VEngineCvar: VEngineCvar004
| GameDirectory: C:\Program Files (x86)\Steam\steamapps\common\Team Fortress 2\tf

**Comment by dtugend** [comment]
Thanks. I have same TF2 and HLAE version.

- Can you please check the bullet points "1.", "4." and also the text after "Edit" (?)
- Addtionally please make sure that it only happens with HLAE, if it happens without HLAE too, it's not solvable from our end.

**Comment by wastedcore** [comment]
Didnt change any settings, same custom folder, same programs which i used before which was HLAE and Sparkly, they just work now. Not sure what was causing it before.

**Comment by dtugend** [comment]
Hm weird. Maybe a reboot helped with the problem. Thanks for reporting back.
