### ISSUE TITLE
CS2: issue with binds in mirv_input camera

### ISSUE THREAD

**Issue by ChetdeJong** [ripieces/advancedfx#946]
Not sure if its HLAE bug, but behavior changed since last game update.

Now if being in camera mode `mirv_input camera`, it seems like game now tracks key presses and executes stuff. 
Before last update game would ignore key binds, when being camera mode, so only HLAE camera binds would work.

Steps to produce:
1) `bind F "echo test"`
2) `mirv_input camera`
3) Press F

Expected, that it doesn't execute bind with echo, so nothing should be in console.

When using previous game build 1.40.0.8 and HLAE 2.162.0 everything work as expected.

**Comment by ChetdeJong** [comment]
Workaround for now is to remove bindings from HLAE binds, so accidentally don't execute something while being in camera mode. But that would mess with people's workflows much.

**Comment by dtugend** [comment]
https://github.com/advancedfx/advancedfx/commit/af9dc3b1c68b94b2470461820b218dad57bf329d
Will be fixed in 2.163.1 coming up shortly.
