### ISSUE TITLE
HLAE doesn't launch CS2 

### ISSUE THREAD

**Issue by lipusik** [ripieces/advancedfx#947]
System Information
Manjaro 23.1.4

Steps to reproduce:
1. Download HLAE.zip
2. Start command in terminal: wine $PATH_TO_HLAE/hlae/HLAE.exe
3. Choose proton for CSGO in Steam, after that Steam will create file cs2.exe in ~/.local/share/Steam/steamapps/common/Counter-Strike\ Global\ Offensive/game/bin/win64
4. Copy  cs2.exe like as csgo.exe
5. Try launch csgo in HLAE 
6. Get error:
```
AfxError #2001: 
Title: Loader failed.Description: System.ApplicationException: 64 Bit CS:GO is not supported.
  at AfxGui.LaunchCsgo.GetHookPath (System.Boolean isProcess64Bit) [0x0000d] in <faf62884b1524db4801e121d494ad1d1>:0 
  at AfxGui.Loader.Load (System.Collections.Generic.IEnumerable`1[T] getHookPathCollection, System.String programPath, System.String cmdLine, System.String environment, System.Boolean showErrorMessage) [0x0007a] in <faf62884b1524db4801e121d494ad1d1>:0 Inner exception: {0}```

**Comment by dtugend** [comment]
1. You are confusing CS:GO and CS2, for on how to launch CS2 see here: https://github.com/advancedfx/advancedfx/wiki/AfxHookSource2
2. I don't know if CS2 works in Wine / Proton, make sure it runs without HLAE first.

**Comment by Dechno1337** [comment]
Did it work?

**Comment by lipusik** [comment]
I couldn't run cs2 with Proton, got error "failed to initialize the steamworks sdk no steamclient021" and didn't find some solution for now
And I tried to use different Proton's versions, it wasn't work

**Comment by lipusik** [comment]
In this [issue](https://github.com/ValveSoftware/Proton/issues/2704#issuecomment-1932437468) user advises installing Steam via Wine
I will try it

**Comment by Dechno1337** [comment]
Probably didn't work?

**Comment by Dechno1337** [comment]
Closing, since this sounds like a Linux problem.
