### ISSUE TITLE
false positive coming from avast

### ISSUE THREAD

**Issue by bulkmoerls** [ripieces/advancedfx#948]
![image](https://github.com/advancedfx/advancedfx/assets/72113439/ac2d8967-7f10-4d82-a6d7-0c31782bfa4e)
![image](https://github.com/advancedfx/advancedfx/assets/72113439/c963b49e-47f9-4726-90b6-262b88527076)

please fix this

**Comment by dtugend** [comment]
Hi. I saw the issue you created. I will try to look into it later this weekend and see what I can do, but to be honest we gave up chasing each individual AV vendor all the time.

Edit: I used their false positive positive response submission form, but not sure what will happen, also it will take at least 48 hours before they might reply.
Edit2: Now also used it for the installer itself.

**Comment by dtugend** [comment]
Hi. Can you update your Avast and check with latest HLAE 2.164.0, if it got any better?
I don't know for sure to be honest, but if it didn't get better I'd recommend to add an exception for HLAE in it (including in behavior blocking) and live that way with it :(

**Comment by bulkmoerls** [comment]
> Hi. Can you update your Avast and check with latest HLAE 2.164.0, if it got any better? I don't know for sure to be honest, but if it didn't get better I'd recommend to add an exception for HLAE in it (including in behavior blocking) and live that way with it :(

thanks, no more issues.
