### ISSUE TITLE
The game keeps crashing when I opens it with HLAE

### ISSUE THREAD

**Issue by jackpozzg** [ripieces/advancedfx#949]
It crashes in the opening page “counter strike 2”

**Comment by dtugend** [comment]
This is due to CS2 update, an update is in the works and scheduled to be released in about 30 minutes.

**Comment by dtugend** [comment]
Please update to HLAE 2.164.0 (currently latest) or newer.

**Comment by jackpozzg** [comment]
It's alright now！thank you for all you do！
