### ISSUE TITLE
tf2 64 bit

### ISSUE THREAD

**Issue by 1foop** [ripieces/advancedfx#951]
Hello I use hlae for tf2 but since they updated it to 64 bit it's no longer compatible. I wonder if there could be any updated version which works with 64 bit tf2.

**Comment by Dechno1337** [comment]
The regular 32 bit version (tf.exe) should still work.

**Comment by dtugend** [comment]
32 bit should work, we currently don't have plans to add 64 bit support: https://github.com/advancedfx/advancedfx/issues/933

You might want to look into SparklyFX in case you don't know it already, should work for recording at least, not sure how you'd replace campaths though: https://github.com/cademtz/sparkly-fx

**Comment by dtugend** [comment]
https://github.com/advancedfx/advancedfx/pull/1124
