### ISSUE TITLE
"AFXERROR: Failed writing image for screen recording" (only getting audio output)

### ISSUE THREAD

**Issue by sovereigntyqt** [ripieces/advancedfx#960]
```
mirv_cvar_unhide_all

mirv_streams record screen enabled 1

mirv_streams record name "C:\Users\User\Videos"

mirv_streams record fps 1200

mirv_streams record screen settings afxFfmpegLosslessFast

mirv_streams record start

mirv_streams record end
```

afxDefault seems to be working fine.

I used the portable zip for HLAE and already had ffmpeg installed.

**Comment by Dechno1337** [comment]
There should be a more specific error above those messages in the console (as soon as the recording starts).

**Comment by dtugend** [comment]
Are you sure you have installed FFMPEG?
You can use the HLAE Installer version if unsure, it helps installing it along with HLAE for you.
If you want to use ZIP version, then you can follow the .txt file in ffmpeg sub-folder of your HLAE.

**Comment by sovereigntyqt** [comment]
> Are you sure you have installed FFMPEG? You can use the HLAE Installer version if unsure, it helps installing it along with HLAE for you. If you want to use ZIP version, then you can follow the .txt file in ffmpeg sub-folder of your HLAE.

Everything seems to work perfectly after creating the ffmpeg.ini. I thought having FFMPEG included as part of the PATH was enough. Thanks for the assistance.
