### ISSUE TITLE
how to fix hlae GetLastWin32Error = 5: Access is denied

### ISSUE THREAD

**Issue by bonuss296** [ripieces/advancedfx#963]
(Please search existing **open and closed** issues first to verify this is a new question.)
i was turn off FACEit anticheat, Vanguard, and some anticheat software but can't make HLAE work.
![Screenshot 2024-07-11 163627](https://github.com/advancedfx/advancedfx/assets/89990956/6d2a2ef2-2f22-4dc5-bdc0-114d6a7a88d0)

**Comment by Dechno1337** [comment]
What do your custom loader settings look like?

**Comment by bonuss296** [comment]
![image](https://github.com/advancedfx/advancedfx/assets/89990956/2035ecc4-b2d3-463e-9e8e-ff8f126f2ef7)
like this i do it right ?

**Comment by Dechno1337** [comment]
1. Does the path end with `cs2.exe`?
2. You don't need to have an extra AfxHookSource2.dll in there.
3. `-window` can be removed (`-sw` is for windowed mode)
4. Are you sure all anti-cheats are properly closed and still not running?

**Comment by bonuss296** [comment]
uhhh yeah i pretty sure i was turn off all anti cheat on my PC. how can i find and know all anti cheat software

**Comment by Dechno1337** [comment]
> uhhh yeah i pretty sure i was turn off all anti cheat on my PC. how can i find and know all anti cheat software

Check the task manager to see if there are still any processes running in the background.

**Comment by bonuss296** [comment]
> 

i was turn off FI anti-cheat and Vanguard Riot, what software have anti cheat i can disable ?

**Comment by dtugend** [comment]
Closing FaceIT GUI will not stop the anti-cheat, you need to go to the Anti-cheat tray icon and choose “disable driver".

> In our latest versions of the FACEIT Anti-cheat, you are given more control over the driver operation. In particular, you can go to the Anti-cheat tray icon and choose “disable driver”. This will allow you to unload our driver without uninstalling the Anti-cheat. Please keep in mind that if you do disable the driver, you will be asked to restart your PC before being able to play any of the games we protect.
https://support.faceit.com/hc/en-us/articles/9394666828188-What-is-FACEIT-Anti-cheat-and-how-does-it-work

**Comment by bonuss296** [comment]
my problem was solved thanks guys
