### ISSUE TITLE
How to edit CS2 panoramic files

### ISSUE THREAD

**Issue by tsxlts** [ripieces/advancedfx#965]
Can someone tell me how to edit CS2 panoramic files

**Comment by dtugend** [comment]
Hi. Sadly I don't know a good answer, but you could try the Discord chat, I think there's one or two people that already do edit CS2 panorama: https://www.advancedfx.org/support/

**Comment by ChetdeJong** [comment]
I have a related video:
https://youtu.be/yo9MCCq7Eqc

In short you need Source 2 Viewer for decompiling and Dota2 workshop tools for compiling files. Not all files can be easily compiled back (like the .ts .js ones), but it works for css, xml editing.

After you modify files and compile them back you have to create vpk file (can be done with Source 2 Viewer), copy it to `csgo` directory and add it to `gameinfo.gi` file before `Game csgo` line

**Comment by tsxlts** [comment]
Thank you for your help. Is there any way to modify the. ts file? @ChetdeJong

**Comment by ChetdeJong** [comment]
I haven't figured it out. 
Dota2 workshop tools just doesn't compile it back.

**Comment by tsxlts** [comment]
Or can you tell me how to modify the panoramic file to make the inspection gloves look like this?

**Comment by tsxlts** [comment]
Or can you tell me how to modify the panoramic file to make the inspection gloves look like this? @ChetdeJong 
![20240726164421](https://github.com/user-attachments/assets/7a76190e-b6ae-4c0e-8dde-b7307bcdb771)

**Comment by ChetdeJong** [comment]
no idea, sorry

**Comment by dtugend** [comment]
This is out of scope for us currently, here are a few pointers, please understand I did not have time to check if they are legit and safe to use:
- https://github.com/AspectUnk/s2-swapping (you could put this DLL into HLAE custom loader to load, but I do NOT know if it's safe to use)
- https://www.unknowncheats.me/forum/counter-strike-2-a/595359-edit-panorama-ui.html
- https://www.unknowncheats.me/forum/counter-strike-2-a/615492-skin-inspect-screenshot.html (but you know this one already)

**Comment by dtugend** [comment]
Sorry I was told this won't solve your issue probably, reopening and closing as not planned.

**Comment by dtugend** [comment]
After you decompiled xml and js, it might be possible to compile them again with resourcecompiler.exe that comes with CS2, but I didn't find much pointers for it:
- https://developer.valvesoftware.com/wiki/Dota_2_Workshop_Tools/Panorama/Javascript
- https://developer.valvesoftware.com/wiki/Resourcecompiler
