### ISSUE TITLE
Campath doing more than I want it to

### ISSUE THREAD

**Issue by Syke422** [ripieces/advancedfx#968]
first time using this and i set some key frames for the camera and it did way more than i needed it too and kind of went all over the place if you can help or wanna add me on discord to help me with the program that would be cool. my discord is: psychdotripp

comment hear before you add so I know your trying to help.

THANK YOU

**Comment by Syke422** [comment]
and explain a little bit more basically it goes past the point i wanted it to go to before going to the next if that makes sense

**Comment by dtugend** [comment]
- https://github.com/advancedfx/advancedfx/wiki/FAQ#why-does-my-campath-make-sharp-turns-or-fly-through-walls
- https://www.youtube.com/watch?v=4fJ4bDEWc1A&list=PLk6wtwbxOYbDJ9-vGhMohaIogfw7e4pmu&index=1

The problem of campath is that it always tries to be super smooth for the keyframes you give to it.
Consider to use our Discord channel (linked on support page of official website), maybe other users there have better ideas than me.
