### ISSUE TITLE
Is there a way to disable the MVP popup graphic and the "bomb has been planted" alert?

### ISSUE THREAD

**Issue by gaknippel** [ripieces/advancedfx#969]
I have tried using cl_drawhud false, cl_drawdeathnoticesonly, and other commands that I saw worked in CSGO, but I guess they don't work in CS2. 
![Screenshot 2024-08-11 215355](https://github.com/user-attachments/assets/e848b2bc-63be-45b9-8559-a4e1e85566c0)

**Comment by ChetdeJong** [comment]
Hi, last time I checked there is no command to disable them (maybe something changed, I don't know).

You can modify panorama files to hide them.
I have a related video: https://youtu.be/yo9MCCq7Eqc

**Comment by gaknippel** [comment]
thanks!

**Comment by dtugend** [comment]
(It is possible to hide all UI with `r_drawpanorama false` but then you will also lose the console until you set it to true again.)

**Comment by gaknippel** [comment]
> (It is possible to hide all UI with `r_drawpanorama false` but then you will also lose the console until you set it to true again.)

thanks man, that's just what i needed
