### ISSUE TITLE
mirv_deathmsg help players dont print XUID

### ISSUE THREAD

**Issue by roustar31** [ripieces/advancedfx#970]
use mirv_deathmsg help players,but show XUID 0
etc:
![sshot-2024-08-15- 2](https://github.com/user-attachments/assets/891684cf-96a7-4850-94b8-1778eadcfdda)

**Comment by roustar31** [comment]
After testing with CS2 version 1.40.2.4, it was found that the output was normal.
![sshot-2024-08-15- 3](https://github.com/user-attachments/assets/17676a0c-3bcf-4a8a-b427-fe23433ef015)

**Comment by Dechno1337** [comment]
I guess the latest CS2 update broke it(?) @ChetdeJong ?

**Comment by ChetdeJong** [comment]
Will check later

**Comment by ChetdeJong** [comment]
Will be fixed in next update. 

Use `userid` for now (or previous version of CS2 if possible)
