### ISSUE TITLE
CS2 Oct 2 2024 update broke HLAE

### ISSUE THREAD

**Issue by dtugend** [ripieces/advancedfx#986]

**Comment by noahsmiths** [comment]
Thank you so much for doing this so quickly 🙏

**Comment by fqishappy** [comment]
Asking politely, when this bug will be fixed?

**Comment by dtugend** [comment]
> Asking politely, when this bug will be fixed?

Current ETA 2 - 3 hours from now. ETA is ETA, meaning can be wrong.

**Comment by fqishappy** [comment]
Thank u for hard work <3

**Comment by dtugend** [comment]
https://github.com/advancedfx/advancedfx/releases/latest
