### ISSUE TITLE
Movie recording failed - Missing expected pixels error

### ISSUE THREAD

**Issue by EEnigma-Hub** [ripieces/advancedfx#988]
Hi, when I start the project with CS2, I keep getting the '[Movie] Movie recording failed! Missing expected pixels!' error in the console. Could you please assist with this issue? I’ve also attached a screenshot showing the error.

**Comment by Enigma-tht** [comment]
![Uploading Ekran görüntüsü 2024-10-03 141133.png…]()

**Comment by EEnigma-Hub** [comment]
![Ekran görüntüsü 2024-10-03 141133](https://github.com/user-attachments/assets/c8b98155-b419-4444-a5b8-32f1bfc3651b)
